import Mathlib.Algebra.Group.Prod
import Mathlib.Algebra.Module.Prod
import Mathlib.LinearAlgebra.Span.Basic
import Mathlib.LinearAlgebra.Basis.Basic
import Mathlib.Tactic
import Mathlib.Algebra.Field.Rat
import Mathlib.Data.Set.Finite.Lattice
import MyProjects.ST.MissingLinks.GC.GaloisClosureAPI

/-!
# 線形包による具体例：ガロア接続フレームワークの検証

このファイルは、GaloisClosureAPI の理論を線形包（linear span）という
具体的な数学的構造で実装し、以下を検証する：

1. 線形包が自然に GeneratorClosureGC のインスタンスとなる
2. `minBasisCount` is treated as standard-basis support, independent of `genCountLayer`
3. ガロア接続から導出される性質が実際に成り立つ

## 数学的設定

基礎集合：ℚ² （有理数係数の2次元ベクトル空間）
部分構造：ℚ² の部分空間（Submodule ℚ ℚ²）

ガロア接続：
- **Gen(s)** = span(s)：集合 s が生成する線形包
- **Cl(V)** = V.carrier：部分空間 V の台集合

ガロア接続の公理：`span(s) ≤ V ↔ s ⊆ V.carrier`

これは線形代数の基本定理：「部分空間は生成する集合の線形包」の圏論的定式化。
-/

namespace LinearSpanGC

open GaloisClosure

/-! ## Part 1: 線形包のガロア接続インスタンス -/

section LinearSpanInstance

variable {K : Type*} [Field K] {V : Type*} [AddCommGroup V] [Module K V]

/--
**線形包のガロア接続**：ベクトル空間の部分空間は自然にガロア接続を成す。

- gen(s) := Submodule.span K s （集合 s の線形包）
- cl(W) := (W : Set V) （部分空間 W の台集合）

ガロア接続の直観：
- 「s から生成される部分空間が W に含まれる」
- ⇔「s の各ベクトルが W に含まれる」
-/
instance linearSpanGC : GeneratorClosureGC V (Submodule K V) where
  gen := Submodule.span K
  cl := fun W => (W : Set V)
  gc := by
    -- GaloisConnection の定義を確認
    intro s W
    constructor
    · -- span K s ≤ W → s ⊆ ↑W
      intro h x hx
      exact h (Submodule.subset_span hx)
    · -- s ⊆ ↑W → span K s ≤ W
      intro h
      exact Submodule.span_le.mpr h
  cl_mono := by
    intro W₁ W₂ h
    exact h

/--
線形包の拡大性：集合 s は、それが生成する線形包に含まれる。

これは Submodule.subset_span そのもの。
-/
theorem linearSpan_extensive (s : Set V) : s ⊆ ↑(Submodule.span K s) :=
  subset_cl_gen (S := Submodule K V) s

/--
線形包の単調性：s ⊆ t ならば span(s) ≤ span(t)

これは Submodule.span_mono そのもの。
-/
theorem linearSpan_monotone {s t : Set V} (h : s ⊆ t) :
    Submodule.span K s ≤ Submodule.span K t :=
  gen_mono h

/--
線形包の冪等性：span(span(s)) = span(s)

証明：ガロア接続から導出される cl_cl_eq を適用。
-/
theorem linearSpan_idempotent (s : Set V) :
    Submodule.span K (↑(Submodule.span K s) : Set V) = Submodule.span K s := by
  exact Submodule.span_span (R := K) (s := s)

end LinearSpanInstance

/-! ## Part 2: Vec2Q example and `minBasisCount` (standard-basis support) -/

section Vec2QExample

/-- 有理数2次元ベクトル空間 -/
def Vec2Q : Type := ℚ × ℚ

/-- Vec2Q は ℚ 上のベクトル空間 -/
instance : AddCommGroup Vec2Q := Prod.instAddCommGroup
instance : Module ℚ Vec2Q := Prod.instModule

/-- 標準基底 e₁ = (1, 0) -/
def e₁ : Vec2Q := (1, 0)

/-- 標準基底 e₂ = (0, 1) -/
def e₂ : Vec2Q := (0, 1)

/--
**最小基底数（ランク関数）**：ベクトル v を表現するのに必要な標準基底の最小個数。

この定義は既存の Closure_Basic.lean の minBasisCount と同一。
-/
noncomputable def minBasisCount (v : Vec2Q) : ℕ :=
  if v.1 = 0 ∧ v.2 = 0 then 0
  else if v.1 = 0 ∨ v.2 = 0 then 1
  else 2

/-! ### 具体的な計算例 -/

example : minBasisCount (0, 0) = 0 := by simp [minBasisCount]
example : minBasisCount (1, 0) = 1 := by simp [minBasisCount]
example : minBasisCount (0, 1) = 1 := by simp [minBasisCount]
example : minBasisCount (1, 1) = 2 := by simp [minBasisCount]
example : minBasisCount (2, 3) = 2 := by simp [minBasisCount]

/-!
### 生成子数による層の具体的記述

ガロア接続フレームワークの `genCountLayer` を使って、
各層を具体的に記述する。
-/

/--
**層 0**：0個の元で生成 = 零ベクトルのみ
-/
theorem genCountLayer_zero :
    genCountLayer (α := Vec2Q) (S := Submodule ℚ Vec2Q) 0 = {(0, 0)} := by
  ext v
  constructor
  · intro ⟨s, hs_card, hv⟩
    -- s.card ≤ 0 より s = ∅
    have hs : s = ∅ := by
      apply Finset.card_eq_zero.mp
      exact Nat.eq_zero_of_le_zero hs_card
    subst hs
    have hv' : v = 0 := by
      simpa [gen, cl, Submodule.span_empty] using hv
    subst hv'
    rfl
  · intro hv
    subst hv
    refine ⟨∅, by simp, ?_⟩
    dsimp [gen, cl]
    exact Submodule.zero_mem _

/--
**Layer 1 (generator-count)**: elements generated by at most one vector.

This is the union of 1-dimensional spans, not the fixed-coordinate axes.
-/
theorem genCountLayer_one_subset :
    genCountLayer (α := Vec2Q) (S := Submodule ℚ Vec2Q) 1 ⊆
      {v : Vec2Q | ∃ w : Vec2Q, v ∈ Submodule.span ℚ ({w} : Set Vec2Q)} := by
  intro v ⟨s, hs_card, hv⟩
  have hs_cases := (Nat.le_one_iff_eq_zero_or_eq_one).mp hs_card
  cases hs_cases with
  | inl h0 =>
    have hs : s = ∅ := by
      exact Finset.card_eq_zero.mp h0
    subst hs
    have hv' : v = 0 := by
      simpa [gen, cl, Submodule.span_empty] using hv
    refine ⟨0, ?_⟩
    subst hv'
    apply Submodule.subset_span
    simp
  | inr h1 =>
    rcases Finset.card_eq_one.mp h1 with ⟨w, rfl⟩
    refine ⟨w, ?_⟩
    simpa [gen, cl] using hv

/--
**層 2**：2個以下の元で生成 = ℚ² 全体

直観：{e₁, e₂} で ℚ² 全体が生成される。
-/
theorem genCountLayer_two :
    genCountLayer (α := Vec2Q) (S := Submodule ℚ Vec2Q) 2 = Set.univ := by
  ext v
  constructor
  · intro _; trivial
  · intro _
    refine ⟨{v}, ?_, ?_⟩
    · -- {v}.ncard ≤ 2
      simp
    · -- v ∈ span{v}
      apply Submodule.subset_span
      simp

/-!
### `minBasisCount` as a separate rank-like function

`genCountLayer` counts generators, while `minBasisCount` counts nonzero coordinates
in the fixed standard basis. We record a coarse upper bound rather than an equality.
-/

/--
被覆性：すべてのベクトルは層 2 に含まれる。
-/
theorem vec2q_covering : ∀ v : Vec2Q, ∃ n : ℕ,
    v ∈ genCountLayer (α := Vec2Q) (S := Submodule ℚ Vec2Q) n := by
  intro v
  refine ⟨2, ?_⟩
  rw [genCountLayer_two]
  trivial

/--
The generator-count tower only yields a coarse upper bound for `Vec2Q`.

`minBasisCount` measures standard-basis support, so it is not identified with `minLayer`.
-/
theorem minLayer_le_two (v : Vec2Q) :
    (structureTowerFromGC vec2q_covering).minLayer v ≤ 2 := by
  classical
  have hv : v ∈ genCountLayer (α := Vec2Q) (S := Submodule ℚ Vec2Q) 2 := by
    rw [genCountLayer_two]
    trivial
  exact Nat.find_min' (vec2q_covering v) hv

end Vec2QExample

/-! ## Part 3: ガロア接続の性質の検証 -/

section PropertyVerification

variable {K : Type*} [Field K] {V : Type*} [AddCommGroup V] [Module K V]

/--
**検証1**：線形包の等冪性がガロア接続から導出される。

この定理は、抽象的な cl_cl_eq の具体例である。
-/
theorem span_span_eq (s : Set V) :
    (Submodule.span K (↑(Submodule.span K s) : Set V)) = Submodule.span K s := by
  exact (Submodule.span_span (R := K) (s := s))

/--
**検証2**：ガロア接続の随伴性が具体的に成り立つ。

`span K s ≤ W ↔ s ⊆ ↑W`
-/
theorem gc_verification (s : Set V) (W : Submodule K V) :
    Submodule.span K s ≤ W ↔ s ⊆ (W : Set V) := by
  exact (gc (α := V) (S := Submodule K V)).le_iff_le

/--
**Verification 3**: `closureIter` stabilizes in finitely many steps.

In this framework it stabilizes at level `1` from idempotence,
so the finite-dimensional assumption is not needed.
-/
theorem closureIter_stabilizes (s : Set V) :
    ∃ N : ℕ, ∀ n ≥ N, closureIter (S := Submodule K V) n s =
      closureIter (S := Submodule K V) N s := by
  simpa using (closureIter_eventually_constant (α := V) (S := Submodule K V) s)

end PropertyVerification

/-! ## Part 4: 教育的まとめ -/

section EducationalSummary

/-!
### 学習のポイント

1. **ガロア接続の威力**
   - 抽象的な公理（Gen(s) ≤ t ↔ s ⊆ Cl(t)）から
   - 具体的な性質（単調性、冪等性）が自動的に導出される

2. **線形包の本質**
   - 「生成」と「閉包」の双対性
   - 部分空間の包含関係 ⇔ 生成する集合の包含関係

3. **構造塔との統合**
   - genCountLayer を使った層の定義
   - minLayer = 「最小生成子数」の圏論的理解

4. **既存理論との整合性**
   - `minBasisCount` retained as standard-basis support
   - RankTower.lean の rank 関数と同一視

### 次のステップ

1. 他の具体例への適用
   - 部分群の生成
   - イデアルの生成
   - 位相的閉包

2. 圏論的一般化
   - モナド・余モナドの完全な形式化
   - 随伴関手の明示的構成

3. 計算可能性
   - minLayer の効率的計算アルゴリズム
   - 有限次元の場合の決定手続き
-/

end EducationalSummary

end LinearSpanGC
