/-
Copyright (c) 2025
Authors: Structure Tower Project
-/

import Mathlib.Data.Nat.Basic
import Mathlib.Data.Set.Basic
import MyProjects.ST.CAT2_complete

/-
# Gemini: Filtration Towers for Discrete Probability

This module extracts the discrete-time probabilistic content of `CAT2_complete`.
We reinterpret the canonical natural-number tower as the natural filtration on
`ℕ`, record that `minLayer` behaves like a stopping time, and study how tower
morphisms encode non-anticipative maps.  Finally we describe the product tower,
highlighting the distinction between Cartesian products of sets and σ-algebra
products.

Key definitions / lemmas:
* `FiltrationTowerNat` — natural filtration on `ℕ` (alias of `natTowerMin`)
* `minLayer_is_stopping_time` — the canonical stopping-time property
* `succ_not_hom_with_id_indexMap` — `Nat.succ` fails to respect minimal layers
* `layer_nat_prod` — explicit description of the product tower layers
-/

noncomputable section

open Classical

open Set

universe u v

namespace MyProjects
namespace ST

open CategoryTheory
open StructureTowerWithMin

/-- The discrete natural filtration on `ℕ`, viewed as a structure tower.
    Each layer `n` consists of the finite initial segment `{0, 1, …, n}` and
    the minimal layer simply records when a point first becomes visible. -/
def FiltrationTowerNat : StructureTowerWithMin.{0, 0} :=
  natTowerMin

/-- Sanity check: the filtration tower coincides definitionally with `natTowerMin`. -/
example : FiltrationTowerNat = natTowerMin :=
  rfl

/-- In any structure tower, the `minLayer` assignment satisfies the stopping-time
condition: the event “`minLayer ≤ i`” already belongs to the layer `i`. -/
theorem minLayer_is_stopping_time (T : StructureTowerWithMin.{u, v}) :
    ∀ i : T.Index, {x : T.carrier | T.minLayer x ≤ i} ⊆ T.layer i := by
  intro i x hx
  have hx_mem : x ∈ T.layer (T.minLayer x) := T.minLayer_mem x
  exact (T.monotone hx) hx_mem

/-- The successor map anticipates information and therefore cannot be a morphism
between natural filtration towers when the time index map is the identity. -/
theorem succ_not_hom_with_id_indexMap :
    ¬ ∃ (f : FiltrationTowerNat ⟶ FiltrationTowerNat),
        f.map = Nat.succ ∧ f.indexMap = _root_.id := by
  intro h
  rcases h with ⟨f, hf_map, hf_index⟩
  have hcontr : Nat.succ 0 = 0 := by
    simpa [FiltrationTowerNat, natTowerMin, hf_map, hf_index] using
      f.minLayer_preserving (0 : ℕ)
  exact Nat.succ_ne_zero 0 hcontr

/-- The self-product of the natural filtration tower. -/
def FiltrationTowerNatProd : StructureTowerWithMin.{0, 0} :=
  StructureTowerWithMin.prod FiltrationTowerNat FiltrationTowerNat

/-- The layers of the product tower are rectangles given by componentwise bounds. -/
lemma layer_nat_prod (i j : ℕ) :
    FiltrationTowerNatProd.layer ⟨i, j⟩ =
      {p : ℕ × ℕ | p.1 ≤ i ∧ p.2 ≤ j} := by
  ext p
  constructor
  · intro h
    simpa [FiltrationTowerNatProd, FiltrationTowerNat, natTowerMin] using h
  · intro h
    simpa [FiltrationTowerNatProd, FiltrationTowerNat, natTowerMin] using h

/-
The product in `StructureTowerWithMin` captures rectangular generating sets,
rather than the σ-algebra generated by them.  Probabilistically, this highlights
that additional closure under countable unions and complements is needed to
recover the classical product filtration.
-/

end ST
end MyProjects
