/-
  Topology B — Bourbaki-style structuration via ordered pairs and morphisms

  This file is derived from:
    src/MyProjects/Topology/B/claude_topologyB_en.md

  Guiding spirit (Bourbaki):
  - Structure built from sets of ordered pairs (products) and morphisms (projections)
  - Universal properties expressed via factorization through projections
  - Emphasis on diagrammatic uniqueness (existence/uniqueness of mediating maps)

  Contents
  A. Product universality and exponential direction (skeleton)
  B. Covering maps (Bourbaki-flavored definition skeleton) and path lifting (statement stub)
  C. Stone–Čech compactification (universal property skeleton)

  Notes
  - Section A provides concrete lemmas fully in terms of projections and ordered pairs.
  - Sections B and C lay out faithful skeletons of the intended structures and universal properties
    so they can be refined without changing interfaces.
-/

import Mathlib.Topology.Basic
import Mathlib.Topology.Constructions.SumProd
import Mathlib.Topology.ContinuousMap.Basic
import Mathlib.Topology.CompactOpen
import Mathlib.Topology.Path
import Mathlib.Topology.Connected.PathConnected
import Mathlib.Topology.LocallyConstant.Basic
import Mathlib.Topology.Instances.Real.Lemmas
import Mathlib.Topology.Category.TopCat.Basic
import Mathlib.Topology.Category.TopCat.Limits.Basic
import Mathlib.CategoryTheory.Adjunction.Basic
import Mathlib.Tactic
-- Stone–Čech (module name may vary slightly by mathlib version):
import Mathlib.Topology.Compactification.StoneCech

namespace Bourbaki.TopologyB
namespace Fin

@[simp] lemma mk_castSucc (k n : Nat) (hk : k < n) :
    (⟨k, Nat.lt_succ_of_le (Nat.le_of_lt hk)⟩ : Fin (n + 1))
      = (Fin.castSucc ⟨k, hk⟩) := by
  ext; rfl

@[simp] lemma mk_succ (k n : Nat) (hk : k < n) :
    (⟨k.succ, by simpa using Nat.succ_lt_succ hk⟩ : Fin (n + 1))
      = (Fin.succ ⟨k, hk⟩) := by
  ext; rfl

end Fin


/-
## A. Product universality via projections

We formalize the spirit “product = structure generated by projections”:
- continuity of projections `π₁, π₂`;
- continuity criterion for a map into a product via its components;
- existence and uniqueness of the mediating map `⟨f, g⟩`.
-/

section ProductUniversality

variable {T X Y : Type*}
variable [TopologicalSpace T] [TopologicalSpace X] [TopologicalSpace Y]

-- Projections (morphisms) from the ordered pair structure X × Y.
def π₁ : X × Y → X := fun p => p.1
def π₂ : X × Y → Y := fun p => p.2

lemma continuous_π₁ : Continuous (π₁ : X × Y → X) := by
  simpa [π₁] using continuous_fst

lemma continuous_π₂ : Continuous (π₂ : X × Y → Y) := by
  simpa [π₂] using continuous_snd

/-
Continuity into a product is equivalent to continuity of the two components
obtained by composing with the projections. This is the universal property
in Bourbaki’s language: the product topology is the coarsest making π₁, π₂
continuous, and continuity is tested componentwise.
-/
theorem continuous_iff_proj (h : T → X × Y) :
    Continuous h ↔
      Continuous (fun t => (h t).1) ∧ Continuous (fun t => (h t).2) := by
  constructor
  · intro hh
    exact ⟨continuous_fst.comp hh, continuous_snd.comp hh⟩
  · rintro ⟨h₁, h₂⟩
    -- Use `Continuous.prodMk` on the components to build continuity of `h`.
    -- We rewrite `h` as `fun t => ((h t).1, (h t).2)` to `simpa`.
    have : Continuous (fun t => ((h t).1, (h t).2)) := h₁.prodMk h₂
    simpa using this

/-
Existence and uniqueness of the mediating map into a product.
Given continuous `f : T → X` and `g : T → Y`, there is a unique continuous
`h : T → X × Y` such that `π₁ ∘ h = f` and `π₂ ∘ h = g`.
-/
theorem exists_unique_lift_to_prod {f : T → X} {g : T → Y}
    (hf : Continuous f) (hg : Continuous g) :
    ∃! h : T → X × Y,
      Continuous h ∧ (∀ t, (h t).1 = f t) ∧ (∀ t, (h t).2 = g t) := by
  refine ⟨(fun t => (f t, g t)), ?exist, ?uniq⟩
  · -- existence: the canonical pairing is continuous and has the desired components
    refine And.intro ?hcont (And.intro ?hfst ?hsnd)
    · simpa using hf.prodMk hg
    · intro t; rfl
    · intro t; rfl
  · -- uniqueness: any other h with the same components must be pointwise equal
    intro h hh
    rcases hh with ⟨_hc, hfst, hsnd⟩
    apply funext
    intro t
    -- Compare components, then use `Prod.ext`.
    apply Prod.ext
    · simpa using hfst t
    · simpa using hsnd t

/-
As a quick corollary, pairing with projections recovers the map.
This is the β-rule for the universal property.
-/
lemma fst_pair_eq (f : T → X) (g : T → Y) (t : T) : ((f t, g t).1) = f t := rfl
lemma snd_pair_eq (f : T → X) (g : T → Y) (t : T) : ((f t, g t).2) = g t := rfl

end ProductUniversality

/-
## A. (Category level) Diagonal ⊣ Product in `TopCat`

We implement the diagonal functor Δ : TopCat ⥤ TopCat × TopCat and the
product functor × : TopCat × TopCat ⥤ TopCat, and exhibit the adjunction
Hom(ΔX, (Y, Z)) ≃ Hom(X, Y × Z). The hom-sets reduce to pairs of continuous
maps versus a single continuous map into the product, matching the Bourbaki
ordered-pair perspective.
-/

section TopCatAdjunction

open CategoryTheory

/- Δ: duplicate objects and morphisms. -/
def deltaTop : TopCat ⥤ TopCat × TopCat where
  obj X := ⟨X, X⟩
  map {X Y} (f : X ⟶ Y) := ⟨f, f⟩
  map_id X := by
    -- identities are componentwise
    ext <;> rfl
  map_comp {X Y Z} (f : X ⟶ Y) (g : Y ⟶ Z) := by
    -- composition is componentwise
    ext <;> rfl

/- ×: binary product on objects as cartesian product of spaces; on morphisms
it acts via `ContinuousMap.prodMap`.
-/
def prodTop : TopCat × TopCat ⥤ TopCat where
  obj X := TopCat.of (X.1 × X.2)
  map {X Y} (f : X ⟶ Y) :=
    TopCat.ofHom <| ContinuousMap.prodMap f.1.hom f.2.hom
  map_id X := by
    -- identity acts componentwise
    ext p <;> rfl
  map_comp {X Y Z} (f : X ⟶ Y) (g : Y ⟶ Z) := by
    -- composition is componentwise
    ext p <;> rfl

@[simp] lemma prodTop_map_id (X : TopCat × TopCat) :
    prodTop.map (𝟙 X) = 𝟙 _ := rfl


/- The hom-set equivalence for the adjunction. -/
noncomputable def homEquivDeltaProd
    (X : TopCat) (YZ : TopCat × TopCat) :
    ((deltaTop.obj X) ⟶ YZ) ≃ (X ⟶ prodTop.obj YZ) :=
{ toFun :=
    fun fg =>
      TopCat.ofHom <| ContinuousMap.prodMk fg.1.hom fg.2.hom
, invFun :=
    fun h =>
      ((TopCat.ofHom <| ContinuousMap.comp ContinuousMap.fst h.hom),
       (TopCat.ofHom <| ContinuousMap.comp ContinuousMap.snd h.hom))
, left_inv := by
    intro fg; ext x <;> rfl
, right_inv := by
    intro h; ext x <;> rfl }

/- The adjunction Δ ⊣ × specialized to `TopCat`. -/
-- (Optional) One can package `homEquivDeltaProd` into an adjunction using
-- `Adjunction.mkOfHomEquiv`. We keep the hom-set equivalence explicit here.

end TopCatAdjunction

/-
## A'. Exponential direction (skeleton)

We record currying/uncurrying at the level of plain functions (ordered pairs →
functions into function spaces) and reserve continuity/topological refinements
for future development (e.g. under `[LocallyCompactSpace]` hypotheses). This
keeps the Bourbaki pairing perspective explicit and light.
-/

section ExponentialSkeleton

variable {X Y Z : Type*}

/-- Currying: functions on a product are functions returning functions. -/
def curry (f : X × Y → Z) : X → Y → Z :=
  fun x y => f (x, y)

/-- Uncurrying: functions returning functions are functions on a product. -/
def uncurry (g : X → Y → Z) : X × Y → Z :=
  fun p => g p.1 p.2

@[simp] lemma curry_uncurry (g : X → Y → Z) : curry (uncurry g) = g := rfl
@[simp] lemma uncurry_curry (f : X × Y → Z) : uncurry (curry f) = f := by
  funext p; cases p; rfl

end ExponentialSkeleton

section ExponentialLaw

open ContinuousMap

variable {X Y Z : Type*}
variable [TopologicalSpace X] [TopologicalSpace Y] [TopologicalSpace Z]

/-- Exponential law: `ContinuousMap (X × Y) Z ≃ₜ ContinuousMap X (ContinuousMap Y Z)` under local compactness. -/
noncomputable def exponential_homeo
    [LocallyCompactSpace X] [LocallyCompactSpace Y] :
    ContinuousMap (X × Y) Z ≃ₜ ContinuousMap X (ContinuousMap Y Z) :=
  Homeomorph.curry (X:=X) (Y:=Y) (Z:=Z)

@[simp] lemma exponential_homeo_apply
    [LocallyCompactSpace X] [LocallyCompactSpace Y]
    (F : ContinuousMap (X × Y) Z) (x : X) (y : Y) :
    (exponential_homeo (X:=X) (Y:=Y) (Z:=Z) F x) y = F (x, y) := rfl

@[simp] lemma exponential_homeo_symm_apply
    [LocallyCompactSpace X] [LocallyCompactSpace Y]
    (G : ContinuousMap X (ContinuousMap Y Z)) (p : X × Y) :
    (exponential_homeo (X:=X) (Y:=Y) (Z:=Z)).symm G p = G p.1 p.2 := rfl

/-- Continuity of the evaluation map `(f, y) ↦ f y` under the compact-open topology. -/
theorem continuous_eval
    [LocallyCompactPair Y Z] :
    Continuous (fun p : ContinuousMap Y Z × Y => p.1 p.2) := by
  simpa using (ContinuousEval.continuous_eval :
    Continuous (fun p : ContinuousMap Y Z × Y => p.1 p.2))

end ExponentialLaw

/-
## B. Covering spaces — Bourbaki-style skeleton

We package the essence of an evenly covered neighborhood in terms of a local
homeomorphism to a product `U × I` with discrete fiber `I`. This keeps the
ordered-pair-and-projection viewpoint explicit. The definition below is a
faithful skeleton: it captures the shape and the key data while staying light.
-/

section CoveringSpaces

open scoped Topology

variable {E B : Type*}
variable [TopologicalSpace E] [TopologicalSpace B]

/- Small helpers to stabilize endpoints and `simp` across mathlib versions. -/

@[inline] def I0 : unitInterval := ⟨0, by simp⟩
@[inline] def I1 : unitInterval := ⟨1, by simp⟩

@[simp] lemma coe_I0 : ((I0 : unitInterval) : ℝ) = 0 := rfl
@[simp] lemma coe_I1 : ((I1 : unitInterval) : ℝ) = 1 := rfl

/- Normalized API for `Path.map`: pass a function and its continuity. -/
@[simp] lemma path_map_apply
  {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
  {x y : X} (γ : Path x y) (f : X → Y) (hf : Continuous f) (t : ↑unitInterval) :
  (γ.map (f := f) hf) t = f (γ t) := rfl

@[simp] lemma path_source_I0
  {X : Type*} [TopologicalSpace X] {x y : X} (γ : Path x y) :
  γ I0 = x := by simpa [I0] using (γ.source)

@[simp] lemma path_target_I1
  {X : Type*} [TopologicalSpace X] {x y : X} (γ : Path x y) :
  γ I1 = y := by simpa [I1] using (γ.target)

/-
`CoveringMap p` asserts that around every base point `b : B`, the preimage of a
small neighborhood `U` decomposes as a product `U × I` for a discrete index
set `I`. We keep the commuting condition with the projection implicit in this
first skeleton, focusing on the core decomposition datum.
-/
  structure CoveringMap (p : E → B) : Prop where
    continuous : Continuous p
    evenlyCovered :
      ∀ b : B,
        ∃ (U : Set B), IsOpen U ∧ b ∈ U ∧
          ∃ (I : Type*) (_ : TopologicalSpace I) (_ : DiscreteTopology I),
          ∃ e : (Subtype fun e : E => p e ∈ U) ≃ₜ ((Subtype fun x : B => x ∈ U) × I),
            (∀ s, ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1)

  /-
  Evenly-covered data at a base point `b`. This packages the witness of
  `CoveringMap.evenlyCovered b` into a reusable record with convenient
  projections and helpers. We store the topology and discreteness on the fiber
  index `I` as fields (to be re-instantiated locally when needed).
  -/
  structure EvenlyCoveredAt (p : E → B) (b : B) where
    U : Set B
    isOpenU : IsOpen U
    memU : b ∈ U
    I : Type*
    instTopI : TopologicalSpace I
    instDiscI : @DiscreteTopology I instTopI
    e : (Subtype fun e : E => p e ∈ U)
        ≃ₜ ((Subtype fun x : B => x ∈ U) × I)
    base : ∀ s,
      ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1

  /-
  Provide the stored topology/discrete topology on `d.I` as instances so that
  typeclass search always picks exactly the topology bundled in `d`.
  This avoids instance mismatch errors like "synthesized instance not
  definitionally equal" when working with products `({x // x ∈ d.U} × d.I)`.
  -/
  -- Note: we intentionally do NOT provide global instances for `d.I` here.
  -- Per the guideline, we will introduce `haveI : TopologicalSpace d.I := d.instTopI`
  -- (and similarly for `DiscreteTopology`) only within proofs that need them.


  namespace EvenlyCoveredAt

  variable {p : E → B} {b : B}

  /-
  NOTE (temporary): We defer `sheet`/`sheet_base` to avoid instance definality
  issues. We will rely on the bundled `sheetMap` defined via `d.e.symm` and
  prove β at the bundled level.
  -/
  -- noncomputable def sheet (d : EvenlyCoveredAt p b)
  --     (i : d.I) : (Subtype fun x : B => x ∈ d.U)
  --       → (Subtype fun e : E => p e ∈ d.U) :=
  -- by
  --   classical
  --   exact fun u => d.e.toEquiv.symm (u, i)

  -- lemma sheet_base (d : EvenlyCoveredAt p b) (i : d.I)
  --     (u : Subtype fun x : B => x ∈ d.U) :
  --     p ((d.sheet i u).1) = u.1 := by
  --   classical
  --   set s := d.e.toEquiv.symm (u, i)
  --   have hs : d.e.toEquiv s = (u, i) := by
  --     subst s; simpa using (d.e.toEquiv.left_inv (u, i))
  --   have hb' : ((d.e.toEquiv s).1 : Subtype fun x : B => x ∈ d.U).1 = p s.1 := by
  --     simpa using (d.base s)
  --   have hfst : ((d.e.toEquiv s).1) = u := congrArg Prod.fst hs
  --   have hfst_val : ((d.e.toEquiv s).1).1 = u.1 := by
  --     simpa using congrArg Subtype.val hfst
  --   have : u.1 = p s.1 := by
  --     simpa [hfst_val] using hb'
  --   change p ((d.e.toEquiv.symm (u, i)).1) = u.1
  --   simpa [s] using this.symm

  -- (Optional) If needed later: continuity of the unbundled sheet map can be
  -- recovered from `sheetMap` and `inclE`. We omit it here to avoid instance
  -- definality issues during early phases.

  /-- The inclusion `U ↪ B` as a bundled continuous map. -/
  noncomputable def inclB (d : EvenlyCoveredAt p b) :
      ContinuousMap (Subtype fun x : B => x ∈ d.U) B :=
    ⟨(fun u => u.1), continuous_subtype_val⟩

  /-- The inclusion `{e // p e ∈ U} ↪ E` as a bundled continuous map. -/
  noncomputable def inclE (d : EvenlyCoveredAt p b) :
      ContinuousMap (Subtype fun e : E => p e ∈ d.U) E :=
    ⟨(fun s => s.1), continuous_subtype_val⟩

  -- The `i`-th sheet as a bundled continuous map (haveI scoped in the proof).
  noncomputable def sheetMap (d : EvenlyCoveredAt p b) (i : d.I) :
      ContinuousMap (Subtype fun x : B => x ∈ d.U)
                    (Subtype fun e : E => p e ∈ d.U) :=
  by
    classical
    letI : TopologicalSpace d.I := d.instTopI
    refine ⟨(fun u => d.e.symm (u, i)), ?_⟩
    have hpair : Continuous fun u : Subtype (fun x : B => x ∈ d.U) => (u, i) := by
      have h1 : Continuous fun u : Subtype (fun x : B => x ∈ d.U) => u := continuous_id
      have h2 : Continuous fun _u : Subtype (fun x : B => x ∈ d.U) => i := continuous_const
      simpa using h1.prodMk h2
    have hcont : Continuous (fun u : Subtype (fun x : B => x ∈ d.U) => d.e.symm (u, i)) :=
      d.e.continuous_symm.comp hpair
    simpa using hcont

  /- β-rule at the bundled `ContinuousMap` level:
     `(p ∘ inclE ∘ sheetMap i) = inclB` on `U`. -/
  @[simp] lemma sheet_comp_eq_inclB (h : CoveringMap p)
      (d : EvenlyCoveredAt p b) (i : d.I) :
      (((⟨p, h.continuous⟩ : ContinuousMap E B)).comp (d.inclE)).comp (d.sheetMap i) = d.inclB := by
    classical
    -- Align the topology instance on `d.I` with the one stored in `d`.
    letI : TopologicalSpace d.I := d.instTopI
    ext u
    -- Evaluate pointwise and use `d.base` with `s = d.e.symm (u,i)`.
    change p ((d.e.symm (u, i)).1) = u.1
    set s := d.e.symm (u, i)
    have hs : d.e s = (u, i) := by
      subst s; simpa using (d.e.left_inv (u, i))
    have hb : ((d.e s).1 : Subtype fun x : B => x ∈ d.U).1 = p s.1 := d.base s
    -- From `hs`, the first projection equals `u` as a subtype.
    have hfst : ((d.e s).1) = u := congrArg Prod.fst hs
    have hfst_val : ((d.e s).1).1 = u.1 := by
      simpa using congrArg Subtype.val hfst
    -- Combine: `u.1 = p s.1`.
    have : u.1 = p s.1 := by
      simpa [hfst_val] using hb
    -- Rewrite back the definition of `s`.
    simpa [s] using this.symm

  /- ### Local lifting for maps landing in `U` -/

  -- Phase 3: local lifting for maps, scoped under a single local instance.
  section LocalLift
  variable {Z : Type*} [TopologicalSpace Z]

  /-- Package a map `γ : Z → B` with image in `U` as a map into the subtype. -/
  noncomputable def toSubtype (d : EvenlyCoveredAt p b)
      (γ : ContinuousMap Z B) (hγ : ∀ z, γ z ∈ d.U) :
      ContinuousMap Z (Subtype fun x : B => x ∈ d.U) :=
    ⟨(fun z => ⟨γ z, hγ z⟩),
      by
        have hcont : Continuous fun z => γ z := γ.continuous
        exact hcont.subtype_mk hγ⟩

  /-- Choose the sheet index determined by a point `e` in the fiber over `U`. -/
  noncomputable def sheetIndexAt (d : EvenlyCoveredAt p b)
      (e : E) (hUE : p e ∈ d.U) : d.I :=
  by
    classical
    exact ((d.e ⟨e, hUE⟩).2)

  /-- The `sheetMap` at index `sheetIndexAt e` passes through the base point `e`. -/
  lemma sheetMap_through (d : EvenlyCoveredAt p b)
      (e : E) (hUE : p e ∈ d.U) :
      d.sheetMap (d.sheetIndexAt e hUE) ⟨p e, hUE⟩ = ⟨e, hUE⟩ := by
    classical
    -- Align the topology instance on `d.I` with the one stored in `d`.
    letI : TopologicalSpace d.I := d.instTopI
    -- Apply `d.e` to both sides and use injectivity.
    apply d.e.injective
    -- Left-hand side under `d.e`.
    have lhs : d.e (d.sheetMap (d.sheetIndexAt e hUE) ⟨p e, hUE⟩)
        = (⟨p e, hUE⟩, d.sheetIndexAt e hUE) := by
      simpa [sheetMap] using d.e.left_inv (⟨p e, hUE⟩, d.sheetIndexAt e hUE)
    -- Right-hand side under `d.e` equals `(⟨p e, hUE⟩, d.sheetIndexAt e hUE)`.
    have hfst : (d.e ⟨e, hUE⟩).1 = ⟨p e, hUE⟩ := by
      apply Subtype.ext
      -- `d.base` gives `((d.e ⟨e, hUE⟩).1).1 = p e`, matching the expected direction
      simpa using (d.base ⟨e, hUE⟩)
    have hrs : d.e ⟨e, hUE⟩ = (⟨p e, hUE⟩, d.sheetIndexAt e hUE) := by
      apply Prod.ext
      · exact hfst
      · rfl
    -- Conclude by rewriting the RHS with `hrs`.
    simpa [hrs] using lhs

  /-- Local lift of `γ` along the `i`-th sheet. -/
  noncomputable def liftAlong (d : EvenlyCoveredAt p b) (h : CoveringMap p)
      (i : d.I) (γ : ContinuousMap Z B) (hγ : ∀ z, γ z ∈ d.U) :
      ContinuousMap Z E :=
    ((d.inclE).comp (d.sheetMap i)).comp (d.toSubtype γ hγ)

  /-- β-rule for the local lift: composing with `p` recovers `γ`. -/
  @[simp] lemma liftAlong_beta (d : EvenlyCoveredAt p b) (h : CoveringMap p)
      (i : d.I) (γ : ContinuousMap Z B) (hγ : ∀ z, γ z ∈ d.U) :
      ((⟨p, h.continuous⟩ : ContinuousMap E B)).comp (d.liftAlong h i γ hγ) = γ := by
    classical
    -- Reassociate and use the bundled β-rule for sheets, then evaluate.
    change ((((⟨p, h.continuous⟩ : ContinuousMap E B)).comp d.inclE).comp (d.sheetMap i)).comp
      (d.toSubtype γ hγ) = γ
    have hβ := EvenlyCoveredAt.sheet_comp_eq_inclB (p:=p) (h:=h) (d:=d) (i:=i)
    -- hβ : ((⟨p,_⟩).comp d.inclE).comp (d.sheetMap i) = d.inclB
    ext z
    simp [liftAlong, toSubtype, inclB, ContinuousMap.comp_apply, hβ]

  end LocalLift


  end EvenlyCoveredAt

  /-
  ### Local path lifting (image contained in one evenly-covered chart)

  For a path `γ : Path b₀ b₁` whose image is contained in an evenly-covered
  neighborhood `U` around `b₀`, we can choose a sheet indexed by the starting
  fiber point and lift `γ` along that sheet to obtain a path starting at the
  chosen fiber point. The β-rule and uniqueness are immediate from the bundled
  β-rule for `liftAlong` and the injectivity of the product chart.
  -/

  /-
  NOTE (temporary): Path lifting and β-lemmas are deferred until Phase 3–6.
  The entire `CoveringMap` path-lifting block is commented out.
  -/
  namespace CoveringMap

  open EvenlyCoveredAt

  variable {p : E → B}

  /-- Local path lift in an evenly-covered neighborhood containing the whole path image. -/
  noncomputable def liftPathLocal
      (h : CoveringMap p) {b₀ b₁ : B}
      (d : EvenlyCoveredAt p b₀)
      (γ : Path b₀ b₁)
      (e₀ : E) (h₀ : p e₀ = b₀)
      (hγU : ∀ t : unitInterval, γ t ∈ d.U) :
      Path e₀ ((d.liftAlong h (d.sheetIndexAt e₀ (by simpa [h₀] using d.memU))
        γ.toContinuousMap hγU) I1) :=
  by
    classical
    -- Prepare endpoint inclusions and the chosen sheet index
    have hUE₀ : p e₀ ∈ d.U := by simpa [h₀] using d.memU
    set i : d.I := d.sheetIndexAt e₀ hUE₀ with hi
    -- The lifted continuous map on `I := unitInterval`.
    let γE : ContinuousMap (↑unitInterval) E := d.liftAlong h i γ.toContinuousMap hγU
    -- Named endpoints of the unit interval (as a subtype)
    let t0 : ↑unitInterval := I0
    let t1 : ↑unitInterval := I1
    -- Endpoint at 0 is the chosen fiber point `e₀`.
    have hγE0 : γE t0 = e₀ := by
      -- compute the start value explicitly
      have hU0 : γ t0 ∈ d.U := hγU t0
      -- Compare with the distinguished sheet-map through e₀ at the base point.
      have Hsheet : (d.sheetMap i ⟨p e₀, hUE₀⟩).1 = e₀ := by
        have := EvenlyCoveredAt.sheetMap_through (p:=p) (b:=b₀) d e₀ hUE₀
        simpa [i] using congrArg Subtype.val this
      -- Change the base from `p e₀` to `b₀` using `h₀`.
      have Hbase_b0 : (d.sheetMap i ⟨b₀, by simpa [h₀] using d.memU⟩).1 = e₀ := by
        -- rewrite the input subtype using `p e₀ = b₀`
        have Heq : (⟨b₀, by simpa [h₀] using d.memU⟩ : Subtype fun x : B => x ∈ d.U)
          = ⟨p e₀, hUE₀⟩ := by
          apply Subtype.ext
          simpa [h₀]
        -- transport along equality on the input
        simpa [EvenlyCoveredAt.sheetMap, Heq] using Hsheet
      -- Now change from `b₀` to the true start `γ t0` using `γ.source`.
      have hγ0 : γ t0 = b₀ := by simpa [t0] using (path_source_I0 (γ := γ))
      have Hstart : (d.sheetMap i ⟨γ t0, hU0⟩).1 = e₀ := by
        have Heq : (⟨γ t0, hU0⟩ : Subtype fun x : B => x ∈ d.U)
          = ⟨b₀, by simpa [h₀] using d.memU⟩ := by
          apply Subtype.ext; simpa [hγ0]
        simpa [EvenlyCoveredAt.sheetMap, Heq] using Hbase_b0
      -- unfold the definition of γE at 0
      simpa [γE, EvenlyCoveredAt.liftAlong, EvenlyCoveredAt.toSubtype,
              EvenlyCoveredAt.inclE, EvenlyCoveredAt.sheetMap]
        using Hstart
    -- Package as a path by taking the underlying bundled map and endpoints.
    refine
      { toContinuousMap := γE
      , source' := hγE0
      , target' := rfl }

  /-- β-rule for the local path lift (bundled path-level version). -/
  lemma liftPathLocal_map_apply
      (h : CoveringMap p) {b₀ b₁ : B}
      (d : EvenlyCoveredAt p b₀)
      (γ : Path b₀ b₁)
      (e₀ : E) (h₀ : p e₀ = b₀)
      (hγU : ∀ t : unitInterval, γ t ∈ d.U) (t : ↑unitInterval) :
      ((liftPathLocal (p:=p) h d γ e₀ h₀ hγU).map (f := p) h.continuous) t = γ t := by
    classical
    -- set up the sheet index used in `liftPathLocal`
    have hUE₀ : p e₀ ∈ d.U := by simpa [h₀] using d.memU
    set i : d.I := d.sheetIndexAt e₀ hUE₀ with hi
    -- bundled β for `liftAlong`
    have hβ := EvenlyCoveredAt.liftAlong_beta (p:=p) (b:=b₀) (d:=d) (h:=h)
      (i:=i) (γ:=γ.toContinuousMap) (hγ:=hγU)
    -- evaluate both sides at `t`
    -- simplify both sides to pointwise equality
    simpa [liftPathLocal, path_map_apply, EvenlyCoveredAt.liftAlong,
            EvenlyCoveredAt.toSubtype, ContinuousMap.comp_apply]
      using congrArg (fun F => F t) hβ

  -- Uniqueness for the local lift with fixed start can be proved by transporting
  -- both lifts along `d.e` and using injectivity; we postpone this global proof
  -- until the gluing step is in place.

  end CoveringMap


  -- We avoid marking `Path.map_trans` as `@[simp]`; instead we expose helper lemmas
  -- `map_trans_path` and `map_trans_path_apply` for the rare pointwise rewrites we need.
lemma map_trans_path
  {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
  {x y z : X} (α : Path x y) (β : Path y z)
  (f : X → Y) (hf : Continuous f) :
  (α.trans β).map (f := f) hf = (α.map (f := f) hf).trans (β.map (f := f) hf) := by
  ext t; simp [path_map_apply]

lemma map_trans_path_apply
  {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
  {x y z : X} (α : Path x y) (β : Path y z)
  (f : X → Y) (hf : Continuous f) (t : unitInterval) :
  ((α.trans β).map (f := f) hf) t
    = ((α.map (f := f) hf).trans (β.map (f := f) hf)) t := by
  simpa using congrArg (fun δ : Path _ _ => δ t)
    (map_trans_path (α:=α) (β:=β) (f:=f) (hf:=hf))


  /-
  ### Subpaths and reparametrization of the unit interval

  We provide a linear reparametrization `segMap a b : I → I` that maps `0 ↦ a`,
  `1 ↦ b`, and use it to define the subpath `γ.subpath a b`.
  -/

  -- Local path utilities are namespaced under `Bourbaki.TopologyB.Path`.
  -- Phase 1: enabled.
  namespace Path

  open scoped Topology

  variable {b₀ b₁ : B}

  /-- Linear reparametrization of the unit interval sending `0 ↦ a` and `1 ↦ b`. -/
  noncomputable def segMap (a b : unitInterval) : ContinuousMap unitInterval unitInterval :=
  by
    -- Define the underlying real-valued function.
    refine ⟨(fun t => ⟨(1 - (t : ℝ)) * (a : ℝ) + (t : ℝ) * (b : ℝ), ?mem⟩), ?cont⟩
    · -- Membership in [0,1].
      -- Nonnegativity
      have ha0 : 0 ≤ (a : ℝ) := a.2.1
      have hb0 : 0 ≤ (b : ℝ) := b.2.1
      have ht0 : 0 ≤ (t : ℝ) := t.2.1
      have ht1 : (t : ℝ) ≤ 1 := t.2.2
      have h1t0 : 0 ≤ 1 - (t : ℝ) := sub_nonneg.mpr ht1
      have h1t1 : (1 - (t : ℝ)) + (t : ℝ) = 1 := by ring
      have h0 : 0 ≤ (1 - (t : ℝ)) * (a : ℝ) + (t : ℝ) * (b : ℝ) := by
        have h₁ : 0 ≤ (1 - (t : ℝ)) * (a : ℝ) := mul_nonneg h1t0 ha0
        have h₂ : 0 ≤ (t : ℝ) * (b : ℝ) := mul_nonneg ht0 hb0
        exact add_nonneg h₁ h₂
      have ha1 : (a : ℝ) ≤ 1 := a.2.2
      have hb1 : (b : ℝ) ≤ 1 := b.2.2
      have hle : (1 - (t : ℝ)) * (a : ℝ) + (t : ℝ) * (b : ℝ)
                  ≤ (1 - (t : ℝ)) * 1 + (t : ℝ) * 1 := by
        refine add_le_add ?_ ?_
        · exact mul_le_mul_of_nonneg_left ha1 h1t0
        · exact mul_le_mul_of_nonneg_left hb1 ht0
      have hone : (1 - (t : ℝ)) * 1 + (t : ℝ) * 1 = 1 := by
        simpa [h1t1] using by ring
      exact ⟨h0, by simpa [hone] using hle⟩
    · -- Continuity.
      have ht : Continuous fun t : unitInterval => (t : ℝ) := continuous_subtype_val
      have h₁ : Continuous fun t : unitInterval => (1 - (t : ℝ)) := continuous_const.sub ht
      have h₂ : Continuous fun _ : unitInterval => (a : ℝ) := continuous_const
      have h₃ : Continuous fun _ : unitInterval => (b : ℝ) := continuous_const
      have hleft : Continuous fun t : unitInterval => (1 - (t : ℝ)) * (a : ℝ) := h₁.mul h₂
      have hright : Continuous fun t : unitInterval => (t : ℝ) * (b : ℝ) := ht.mul h₃
      have hcont : Continuous fun t : unitInterval =>
          (1 - (t : ℝ)) * (a : ℝ) + (t : ℝ) * (b : ℝ) := hleft.add hright
      -- upgrade to continuity into the subtype via `subtype_mk`
      exact hcont.subtype_mk (by
        intro t
        -- Reproduce the membership proof pointwise
        have ha0 : 0 ≤ (a : ℝ) := a.2.1
        have hb0 : 0 ≤ (b : ℝ) := b.2.1
        have ht0 : 0 ≤ (t : ℝ) := t.2.1
        have ht1 : (t : ℝ) ≤ 1 := t.2.2
        have h1t0 : 0 ≤ 1 - (t : ℝ) := sub_nonneg.mpr ht1
        have h1t1 : (1 - (t : ℝ)) + (t : ℝ) = 1 := by ring
        have h0 : 0 ≤ (1 - (t : ℝ)) * (a : ℝ) + (t : ℝ) * (b : ℝ) := by
          have h₁ : 0 ≤ (1 - (t : ℝ)) * (a : ℝ) := mul_nonneg h1t0 ha0
          have h₂ : 0 ≤ (t : ℝ) * (b : ℝ) := mul_nonneg ht0 hb0
          exact add_nonneg h₁ h₂
        have ha1 : (a : ℝ) ≤ 1 := a.2.2
        have hb1 : (b : ℝ) ≤ 1 := b.2.2
        have hle : (1 - (t : ℝ)) * (a : ℝ) + (t : ℝ) * (b : ℝ)
                    ≤ (1 - (t : ℝ)) * 1 + (t : ℝ) * 1 := by
          refine add_le_add ?_ ?_
          · exact mul_le_mul_of_nonneg_left ha1 h1t0
          · exact mul_le_mul_of_nonneg_left hb1 ht0
        have hone : (1 - (t : ℝ)) * 1 + (t : ℝ) * 1 = 1 := by
          simpa [h1t1] using by ring
        exact ⟨h0, by simpa [hone] using hle⟩)

  @[simp] lemma segMap_I0 (a b : unitInterval) :
      segMap a b I0 = a := by
    ext; simp [segMap, I0, one_mul]

  @[simp] lemma segMap_I1 (a b : unitInterval) :
      segMap a b I1 = b := by
    ext; simp [segMap, I1]

  -- Friendly names requested in the guide
  @[simp] lemma segMap_zero (a b : unitInterval) :
      segMap a b (0 : unitInterval) = a := by
    simpa [I0] using (segMap_I0 a b)

  @[simp] lemma segMap_one (a b : unitInterval) :
      segMap a b (1 : unitInterval) = b := by
    simpa [I1] using (segMap_I1 a b)

  /-- Subpath of `γ` between times `a` and `b` in the unit interval. -/
  noncomputable def subpath (γ : Path b₀ b₁)
      (a b : unitInterval) : Path (γ a) (γ b) :=
  { toContinuousMap := γ.toContinuousMap.comp (segMap a b)
  , source' := by
      change (γ.toContinuousMap (segMap a b I0)) = γ a
      simpa [ContinuousMap.comp_apply] using congrArg (fun x => γ.toContinuousMap x)
        (segMap_I0 a b)
  , target' := by
      change (γ.toContinuousMap (segMap a b I1)) = γ b
      simpa [ContinuousMap.comp_apply] using congrArg (fun x => γ.toContinuousMap x)
        (segMap_I1 a b) }

  end Path

  /-
  NOTE (temporary): Localized subinterval lifting and 2-segment gluing are
  deferred; comment out to keep build green.
  -/
  namespace CoveringMap

  open Path EvenlyCoveredAt

  variable {p : E → B}

  /-- Local lift on a subinterval `[a,b]` whose image lands in an evenly-covered chart. -/
  noncomputable def liftPathLocalOn
      (h : CoveringMap p) {b₀ b₁ : B}
      (γ : Path b₀ b₁)
      (a b : unitInterval)
      (d : EvenlyCoveredAt p (γ a))
      (eₐ : E) (hₐ : p eₐ = γ a)
      (hγU : ∀ t : unitInterval, γ (Bourbaki.TopologyB.Path.segMap a b t) ∈ d.U) :
      Path eₐ ((d.liftAlong h (d.sheetIndexAt eₐ (by
        have : γ a ∈ d.U := by
          simpa using hγU I0
        simpa [hₐ] using this))
        (γ.toContinuousMap.comp (Bourbaki.TopologyB.Path.segMap a b))
        (by intro t; simpa using hγU t)) I1) :=
  by
    classical
    -- Prepare the sheet index at the starting endpoint a
    have hUa : γ a ∈ d.U := by simpa using hγU I0
    set i : d.I := d.sheetIndexAt eₐ (by simpa [hₐ] using hUa) with hi
    -- The lifted continuous map on the subinterval
    let γE : ContinuousMap (↑unitInterval) E :=
      d.liftAlong h i (γ.toContinuousMap.comp (Bourbaki.TopologyB.Path.segMap a b))
        (by intro t; simpa using hγU t)
    -- Endpoints in the unit interval subtype
    let t0 : ↑unitInterval := I0
    let t1 : ↑unitInterval := I1
    -- Startpoint: use the sheetMap_through at γ a and rewrite by hₐ
    have hγE0 : γE t0 = eₐ := by
      have : (d.sheetMap i ⟨γ a, hUa⟩).1 = eₐ := by
        -- through property at the starting base point
        have := EvenlyCoveredAt.sheetMap_through (p:=p) d eₐ (by simpa [hₐ] using hUa)
        simpa [i, hₐ] using congrArg Subtype.val this
      -- evaluate γE at t0 and simplify
      simpa [γE, EvenlyCoveredAt.liftAlong, EvenlyCoveredAt.toSubtype,
              EvenlyCoveredAt.inclE, EvenlyCoveredAt.sheetMap,
              Bourbaki.TopologyB.Path.segMap, t0, I0]
        using this
    -- Package as a path
    refine
      { toContinuousMap := γE
      , source' := hγE0
      , target' := rfl }

  /-- β-rule (apply-level) for the localized lift on `[a,b]`. -/
  lemma liftPathLocalOn_map_apply
      (h : CoveringMap p) {b₀ b₁ : B}
      (γ : Path b₀ b₁)
      (a b : unitInterval)
      (d : EvenlyCoveredAt p (γ a))
      (eₐ : E) (hₐ : p eₐ = γ a)
      (hγU : ∀ t : unitInterval, γ (Bourbaki.TopologyB.Path.segMap a b t) ∈ d.U)
      (t : unitInterval) :
      ((liftPathLocalOn (p:=p) h γ a b d eₐ hₐ hγU).map (f := p) h.continuous) t
        = (Bourbaki.TopologyB.Path.subpath γ a b) t := by
    classical
    -- bundled β for the lifted map on the subinterval (pointwise)
    have hβ := EvenlyCoveredAt.liftAlong_beta (p:=p) (b:=γ a) (d:=d) (h:=h)
      (i:=d.sheetIndexAt eₐ (by
        have : γ a ∈ d.U := by simpa using hγU I0
        simpa [hₐ] using this))
      (γ:=γ.toContinuousMap.comp (Bourbaki.TopologyB.Path.segMap a b))
      (hγ:=by intro t'; simpa using hγU t')
    have := congrArg (fun F => F t) hβ
    simpa [liftPathLocalOn, path_map_apply, EvenlyCoveredAt.liftAlong,
            EvenlyCoveredAt.toSubtype, ContinuousMap.comp_apply]
      using this

  /-- Glue two local lifts over adjacent subintervals `[a,c]` and `[c,b]`. -/
  noncomputable def liftPathTwo
      (h : CoveringMap p) {b₀ b₁ : B}
      (γ : Path b₀ b₁)
      (a c b : unitInterval)
      (h_ac : (a : ℝ) ≤ c ∧ c ≤ b)
      (d₁ : EvenlyCoveredAt p (γ a)) (d₂ : EvenlyCoveredAt p (γ c))
      (eₐ : E) (hₐ : p eₐ = γ a)
      (hγU₁ : ∀ t : unitInterval, γ (Bourbaki.TopologyB.Path.segMap a c t) ∈ d₁.U)
      (hγU₂ : ∀ t : unitInterval, γ (Bourbaki.TopologyB.Path.segMap c b t) ∈ d₂.U) :
      Path eₐ ((liftPathLocalOn (p:=p) h γ c b d₂
        ((liftPathLocalOn (p:=p) h γ a c d₁ eₐ hₐ hγU₁) I1)
        (by
          -- equality `p (Γ₁ 1) = γ c` via apply-level local β at endpoint
          have hβ := liftPathLocal_map_apply (p:=p) h d₁ (Bourbaki.TopologyB.Path.subpath γ a c)
            eₐ hₐ (by intro t; simpa [Bourbaki.TopologyB.Path.subpath, ContinuousMap.comp_apply] using hγU₁ t) I1
          simpa [Bourbaki.TopologyB.Path.subpath, path_map_apply] using hβ)
        hγU₂) I1) :=
  by
    classical
    -- Define the two local lifts and compose them via `Path.trans`.
    let Γ₁ := liftPathLocalOn (p:=p) h γ a c d₁ eₐ hₐ hγU₁
    let e_c := Γ₁ I1
    have hcstart : p e_c = γ c := by
      -- pointwise β at endpoint using the apply-level lemma
      have := liftPathLocal_map_apply (p:=p) h d₁ (Bourbaki.TopologyB.Path.subpath γ a c)
        eₐ hₐ (by intro t; simpa [Bourbaki.TopologyB.Path.subpath, ContinuousMap.comp_apply] using hγU₁ t) I1
      simpa [Γ₁, Bourbaki.TopologyB.Path.subpath, path_map_apply] using this
    let Γ₂ := liftPathLocalOn (p:=p) h γ c b d₂ e_c hcstart hγU₂
    -- Compose the two lifted paths.
    exact Γ₁.trans Γ₂

  end CoveringMap


  /-
  ### Finite path covers and global lifting

  We package a finite partition of the unit interval together with evenly-covered
  charts per subinterval, and glue the corresponding local lifts into a global
  lift over `[0,1]`.
  -/

  /-
  NOTE (temporary): Finite path cover and global fold are deferred; comment out
  to complete early phases first.
  -/
  namespace CoveringMap

  open Path EvenlyCoveredAt

  variable {p : E → B}

  /-- A finite cover of a path by evenly-covered neighborhoods, indexed by a finite
  increasing sequence of parameters `pts : Fin (n+1) → I`. On each subinterval
  `[pts i, pts (i.succ)]`, the image of the path is contained in the neighborhood
  `charts i`. We keep only the data needed to perform gluing; monotonicity is
  not used explicitly here as we only rely on endpoints of subpaths. -/
  structure PathCover {b₀ b₁ : B} (p : E → B) (γ : Path b₀ b₁) where
    n : Nat
    pts : Fin (n+1) → unitInterval
    start : pts ⟨0, by
      have : (0 : Nat) < n + 1 := Nat.succ_pos _
      exact this⟩ = I0
    stop : pts ⟨n, by
      have : n < n + 1 := Nat.lt_succ_self _
      exact this⟩ = I1
    charts : ∀ i : Fin n, EvenlyCoveredAt p (γ (pts i.castSucc))
    inU : ∀ i : Fin n, ∀ t : unitInterval,
      γ (Bourbaki.TopologyB.Path.segMap (pts i.castSucc) (pts i.succ) t) ∈ (charts i).U

@[simp] lemma PathCover.pts_zero
    {b₀ b₁ : B} {γ : Path b₀ b₁} (cov : PathCover (p:=p) γ) :
    cov.pts 0 = I0 := by
  simpa using cov.start

@[simp] lemma PathCover.pts_last
    {b₀ b₁ : B} {γ : Path b₀ b₁} (cov : PathCover (p:=p) γ) :
    cov.pts ⟨cov.n, by simpa using Nat.lt_succ_self _⟩ = I1 := by
  simpa using cov.stop

@[simp] lemma PathCover.pts_last_fin
    {b₀ b₁ : B} {γ : Path b₀ b₁} (cov : PathCover (p:=p) γ) :
    cov.pts (Fin.last _) = I1 := by
  classical
  simpa using cov.stop

  /- Left-fold concatenation core up to index `k` (apply-level fold nucleus).
     Returns a path from `γ I0` to `γ (cov.pts k)` built by concatenating
     subpaths `[pts i.castSucc, pts i.succ]` for `i = 0..k-1`. -/
  noncomputable def coverConcatCore {b₀ b₁ : B}
      (γ : Path b₀ b₁) (cov : PathCover (p:=p) γ) :
      (k : Fin (cov.n + 1)) → Path b₀ (γ (cov.pts k))
  | ⟨0, _hk0⟩ =>
    -- Base: trivial path at b₀; target is γ (pts 0) = γ I0 = b₀
    { toContinuousMap := (Path.refl b₀).toContinuousMap
    , source' := by simpa using (Path.refl b₀).source
    , target' := by
        -- Target must be `γ (cov.pts ⟨0, _hk0⟩)`; align `cov.start` index first.
        have hidx : (⟨0, _hk0⟩ : Fin (cov.n+1)) = ⟨0, Nat.succ_pos _⟩ := by
          ext; rfl
        have hstart0 : cov.pts ⟨0, _hk0⟩ = I0 := by
          simpa [hidx] using (cov.start)
        have hsource : γ I0 = b₀ := path_source_I0 (γ := γ)
        have h0 : γ (cov.pts ⟨0, _hk0⟩) = b₀ := hstart0 ▸ hsource
        have h0symm : b₀ = γ (cov.pts ⟨0, _hk0⟩) := h0.symm
        exact (Path.refl b₀).target.trans h0symm }
  | ⟨Nat.succ k, hk⟩ =>
    -- Induction: concatenate previous segment with subpath on [pts i.castSucc, pts i.succ]
    let hklt : k < cov.n := Nat.succ_lt_succ_iff.mp hk
    let i : Fin cov.n := ⟨k, hklt⟩
    have hk' : k ≤ cov.n := le_of_lt hklt
    -- Previous fold up to k (as a Fin in n+1)
    have prev : Path b₀ (γ (cov.pts ⟨k, Nat.lt_succ_of_le hk'⟩)) :=
      coverConcatCore γ cov ⟨k, Nat.lt_succ_of_le hk'⟩
    -- Concatenate with the subpath on the next interval
    prev.trans (Bourbaki.TopologyB.Path.subpath γ (cov.pts i.castSucc) (cov.pts i.succ))


  /-- The concatenation over the whole cover, exposed via the left-fold core. -/
  noncomputable def coverConcat {b₀ b₁ : B}
      (γ : Path b₀ b₁) (cov : PathCover (p:=p) γ) : Path b₀ b₁ :=
  by
    classical
    -- Take the fold up to `n` and retag the target using `γ I1 = b₁` and `cov.stop`.
    let δ := coverConcatCore (p:=p) γ cov ⟨cov.n, by simpa using Nat.lt_succ_self _⟩
    refine
      { toContinuousMap := δ.toContinuousMap
      , source' := by simpa using δ.source
      , target' := ?_ }
    -- endpoint at `1` equals `b₁`; align the index in `cov.stop`
    have hidx : (⟨cov.n, by simpa using Nat.lt_succ_self _⟩ : Fin (cov.n+1))
              = ⟨cov.n, by
                  have : cov.n < cov.n + 1 := Nat.lt_succ_self _
                  exact this⟩ := by
      ext; rfl
    have hstop : cov.pts ⟨cov.n, by simpa using Nat.lt_succ_self _⟩ = I1 := by
      simpa [hidx] using (cov.stop)
    have hb1 : γ (cov.pts ⟨cov.n, by simpa using Nat.lt_succ_self _⟩) = b₁ := by
      simpa [hstop] using (path_target_I1 (γ := γ))
    simpa [hb1] using δ.target

  -- We deliberately avoid asserting that `coverConcat` pointwise equals a
  -- single `subpath` of `γ`: the concatenation via `Path.trans` composes
  -- segments with a different (piecewise) reparametrization than a single
  -- linear `segMap`. This keeps the fold nucleus compatible with later β-lemmas.

  /-
  -- Concatenation of the subpaths determined by a `PathCover`. This is a
  canonical reparametrization of `γ` by the partition points `cov.pts`. -/
  /- NOTE: Phase 6 (coverConcat/liftPathOnCover) deferred; commenting out to keep build green.
  noncomputable def coverConcat {b₀ b₁ : B}
      (γ : Path b₀ b₁) (cov : PathCover (p:=p) γ) : Path b₀ b₁ :=
  by
    classical
    -- Build the concatenation up to step `k` with target `γ (pts k)`.
    let build : ∀ k, (hk : k ≤ cov.n) → Path b₀ (γ (cov.pts ⟨k, Nat.lt_succ_of_le hk⟩))
    | 0, hk =>
      -- At k = 0, `pts 0 = 0`, so the trivial path works.
      have hsource : γ I0 = b₀ := path_source_I0 (γ := γ)
      have h0 : γ (cov.pts ⟨0, Nat.succ_pos _⟩) = b₀ := by
        have hstart : cov.pts ⟨0, Nat.succ_pos _⟩ = I0 := by
          simpa using (cov.start)
        exact hstart ▸ hsource
      -- Adjust the target via rewriting to match the required type.
      { toContinuousMap := (Path.refl b₀).toContinuousMap
      , source' := by simpa using (Path.refl b₀).source
      , target' := by
          have h0symm : b₀ = γ (cov.pts ⟨0, Nat.succ_pos _⟩) := h0.symm
          exact (Path.refl b₀).target.trans h0symm }
    | (Nat.succ k), hk =>
      -- Previous stage
      have hk' : k ≤ cov.n := le_trans (Nat.le_succ k) hk
      have hklt : k < cov.n := lt_of_lt_of_le (Nat.lt_succ_self k) hk
      let i : Fin cov.n := ⟨k, hklt⟩
      -- Glue previous with the subpath on `[pts i, pts i.succ]`.
      (build k hk').trans (Bourbaki.TopologyB.Path.subpath γ (cov.pts i.castSucc) (cov.pts i.succ))
    -- final path ends at `γ 1 = b₁`
    { toContinuousMap := (build cov.n le_rfl).toContinuousMap
    , source' := by simpa using (build cov.n le_rfl).source
    , target' := by
        have : γ (cov.pts ⟨cov.n, Nat.lt_succ_self _⟩) = b₁ := by
          have : γ I1 = b₁ := by simpa using (path_target_I1 (γ := γ))
          simpa [cov.stop] using this
        simpa [this] using (build cov.n le_rfl).target }

  /-- Glue local lifts along the subintervals of a `PathCover` to obtain a global lift
  over the whole interval. Returns the endpoint in the fiber and the lifted path. -/
  private noncomputable def liftPathOnCover.build
      (h : CoveringMap p) {b₀ b₁ : B}
      (γ : Path b₀ b₁) (cov : PathCover (p:=p) γ)
      (e₀ : E) (h₀ : p e₀ = b₀) :
      ∀ k (hk : k ≤ cov.n), Σ e : E, Path e₀ e ×
        (p e = γ (cov.pts ⟨k, Nat.lt_succ_of_le hk⟩)) :=
  by
    classical
    intro k
    induction' k with k ih generalizing e₀
    · intro hk
      have hsource : γ I0 = b₀ := path_source_I0 (γ := γ)
      have hstart : cov.pts ⟨0, Nat.succ_pos _⟩ = I0 := by
        simpa using (cov.start)
      have hγ0 : γ (cov.pts ⟨0, Nat.succ_pos _⟩) = b₀ := hstart ▸ hsource
      exact ⟨e₀, (Path.refl e₀, h₀.trans hγ0.symm)⟩
    · intro hkSucc
      have hk' : k ≤ cov.n := le_trans (Nat.le_succ k) hkSucc
      rcases ih hk' with ⟨e_k, Γ_k, hkrel⟩
      have hklt : k < cov.n := lt_of_lt_of_le (Nat.lt_succ_self k) hkSucc
      let i : Fin cov.n := ⟨k, hklt⟩
      have hidx : (⟨k, by exact Nat.lt_succ_of_le hk'⟩ : Fin (cov.n + 1)) = i.castSucc := by
        ext; rfl
      have hstart : p e_k = γ (cov.pts i.castSucc) := by simpa [hidx] using hkrel
      let Γseg :=
        liftPathLocalOn (p:=p) h γ (cov.pts i.castSucc) (cov.pts i.succ) (cov.charts i)
          e_k hstart (cov.inU i)
      have hend : p (Γseg I1) = γ (cov.pts i.succ) := by
        have hβ := liftPathLocalOn_map_apply (p:=p) h γ (cov.pts i.castSucc) (cov.pts i.succ)
          (cov.charts i) e_k hstart (cov.inU i) I1
        simpa [Γseg, path_map_apply, Bourbaki.TopologyB.Path.subpath,
               ContinuousMap.comp_apply] using hβ
      exact ⟨Γseg I1, (Γ_k.trans Γseg, by simpa using hend)⟩

  lemma liftPathOnCover.build_map_apply
      (h : CoveringMap p) {b₀ b₁ : B}
      (γ : Path b₀ b₁) (cov : PathCover (p:=p) γ) :
      ∀ {k} (hk : k ≤ cov.n) {e₀ : E} (h₀ : p e₀ = b₀) (t : unitInterval),
        let data := liftPathOnCover.build (h:=h) γ cov e₀ h₀ k hk
        in ((data.2.1).map (f := p) h.continuous) t =
          (coverConcatCore γ cov ⟨k, Nat.lt_succ_of_le hk⟩) t :=
  by
    classical
    intro k
    induction' k with k ih generalizing e₀
    · intro hk e₀ h₀ t
      have hidx : (⟨0, Nat.lt_succ_of_le hk⟩ : Fin (cov.n + 1)) = ⟨0, Nat.succ_pos _⟩ := by
        ext; rfl
      have hpts : cov.pts ⟨0, Nat.lt_succ_of_le hk⟩ = I0 := by
        simpa [hidx] using cov.start
      have hsource : γ I0 = b₀ := path_source_I0 (γ := γ)
      have hγ0 : γ (cov.pts ⟨0, Nat.lt_succ_of_le hk⟩) = b₀ := hpts ▸ hsource
      have hp : ((Path.refl e₀).map (f := p) h.continuous) t = p e₀ := by
        simp [path_map_apply]
      have hcover :
          (coverConcatCore γ cov ⟨0, Nat.lt_succ_of_le hk⟩) t = b₀ := by
        simp [coverConcatCore, hidx]
      refine
        (calc
          ((Path.refl e₀).map (f := p) h.continuous) t = p e₀ := hp
          _ = b₀ := h₀
          _ = (coverConcatCore γ cov ⟨0, Nat.lt_succ_of_le hk⟩) t := by
            simpa using hcover.symm)
    · intro hkSucc e₀ h₀ t
      have hk' : k ≤ cov.n := Nat.le_of_lt_succ hkSucc
      have hklt : k < cov.n := lt_of_lt_of_le (Nat.lt_succ_self k) hkSucc
      set data := liftPathOnCover.build (h:=h) γ cov e₀ h₀ k hk' with hdata
      rcases data with ⟨e_k, ΓkData⟩
      rcases ΓkData with ⟨Γ_k, hkrel⟩
      have hkmap := ih hk' (e₀ := e₀) (h₀ := h₀) t
      let i : Fin cov.n := ⟨k, hklt⟩
      have hidx : (⟨k, by exact Nat.lt_succ_of_le hk'⟩ : Fin (cov.n + 1)) = i.castSucc := by
        ext; rfl
      have hstart : p e_k = γ (cov.pts i.castSucc) := by simpa [hidx] using hkrel
      let Γseg :=
        liftPathLocalOn (p:=p) h γ (cov.pts i.castSucc) (cov.pts i.succ) (cov.charts i)
          e_k hstart (cov.inU i)
      have hΓseg := liftPathLocalOn_map_apply (p:=p) h γ (cov.pts i.castSucc) (cov.pts i.succ)
        (cov.charts i) e_k hstart (cov.inU i) t
      have hgoal :
          ((Γ_k.map (f := p) h.continuous).trans (Γseg.map (f := p) h.continuous)) t =
            (coverConcatCore γ cov ⟨Nat.succ k, Nat.lt_succ_of_le hkSucc⟩) t := by
        simp [coverConcatCore, Γseg, hkmap, hΓseg, path_map_apply]
      have htrans :=
        map_trans_path_apply (α:=Γ_k) (β:=Γseg) (f:=p) (hf:=h.continuous) t
      have hΓ :
          ((Γ_k.trans Γseg).map (f := p) h.continuous) t =
            (coverConcatCore γ cov ⟨Nat.succ k, Nat.lt_succ_of_le hkSucc⟩) t :=
        htrans.trans hgoal
      have hbuild :
          ((liftPathOnCover.build (h:=h) γ cov e₀ h₀ (Nat.succ k) hkSucc).2.1.map (f := p) h.continuous) t =
            ((Γ_k.trans Γseg).map (f := p) h.continuous) t := by
        simp [liftPathOnCover.build, hk', hklt, Γseg]
      simpa [hdata] using hbuild.trans hΓ

  /-- Glue local lifts along the subintervals of a PathCover to obtain a global lift
  over the whole interval. Returns the endpoint in the fiber and the lifted path. -/
  noncomputable def liftPathOnCover
      (h : CoveringMap p) {b₀ b₁ : B}
      (γ : Path b₀ b₁)
      (cov : PathCover (p:=p) γ)
      (e₀ : E) (h₀ : p e₀ = b₀) :
      Σ e : E, Path e₀ e :=
  by
    classical
    let data := liftPathOnCover.build (h:=h) γ cov e₀ h₀ cov.n le_rfl
    exact ⟨data.1, data.2.1⟩

  /-
  β-rule for `liftPathOnCover`: after composing with `p`, one recovers the
  canonical concatenation of the base path determined by the cover.
  The pointwise statement follows by unfolding the fold nucleus; the endpoint
  case is an immediate corollary.
  -/


  /-- Pointwise β-rule for `liftPathOnCover`: projecting the lifted path along
      `p` recovers the concatenation `coverConcat` determined by the cover. -/
  lemma liftPathOnCover_map_apply
      (h : CoveringMap p) {b₀ b₁ : B}
      (γ : Path b₀ b₁)
      (cov : PathCover (p:=p) γ)
      (e₀ : E) (h₀ : p e₀ = b₀) (t : unitInterval) :
      ((liftPathOnCover (p:=p) h γ cov e₀ h₀).2.map (f := p) h.continuous) t
        = (coverConcat (p:=p) γ cov) t := by
    classical
    set data := liftPathOnCover.build (h:=h) γ cov e₀ h₀ cov.n le_rfl
    have hlift : (liftPathOnCover (p:=p) h γ cov e₀ h₀).2 = data.2.1 := by
      simp [liftPathOnCover, data]
    have hmap :=
      liftPathOnCover.build_map_apply (h:=h) (γ:=γ) (cov:=cov)
        (hk := le_rfl) (e₀ := e₀) (h₀ := h₀) (t := t)
    have hcover :
        (coverConcat (p:=p) γ cov) t
          = (coverConcatCore (p:=p) γ cov ⟨cov.n, by simpa using Nat.lt_succ_self _⟩) t := by
      simp [coverConcat]
    simpa [data, hlift, hcover] using hmap

  /-- Endpoint β-rule for `liftPathOnCover`: composing with `p` at `I1` reduces to the
      concatenation built from the cover. -/
  lemma liftPathOnCover_map_I1
      (h : CoveringMap p) {b₀ b₁ : B}
      (γ : Path b₀ b₁)
      (cov : PathCover (p:=p) γ)
      (e₀ : E) (h₀ : p e₀ = b₀) :
      ((liftPathOnCover (p:=p) h γ cov e₀ h₀).2.map (f := p) h.continuous) I1
        = (coverConcat (p:=p) γ cov) I1 := by
    simpa using
      (liftPathOnCover_map_apply (p:=p) h (γ:=γ) cov e₀ h₀ (t := I1))


  /-- Endpoint β-rule at the left endpoint for `liftPathOnCover`. -/
  lemma liftPathOnCover_map_I0
      (h : CoveringMap p) {b₀ b₁ : B}
      (γ : Path b₀ b₁)
      (cov : PathCover (p:=p) γ)
      (e₀ : E) (h₀ : p e₀ = b₀) :
      ((liftPathOnCover (p:=p) h γ cov e₀ h₀).2.map (f := p) h.continuous) I0
        = (coverConcat (p:=p) γ cov) I0 := by
    simpa using
      (liftPathOnCover_map_apply (p:=p) h (γ:=γ) cov e₀ h₀ (t := I0))

  -- TODO: reinstall the full pointwise β-rule once the reparametrization lemmas are ready.

  /-- β-rule for `liftPathOnCover`: composing with `p` recovers `γ`.
  Proof outline: fold over segments; each segment satisfies the β-rule by
  `liftPathLocalOn_map`, and `Path.map` respects concatenation. -/
  -- β-rule and uniqueness lemmas for `liftPathOnCover` can be added here once a
  -- compactness-driven extraction lemma for `PathCover` is in place. Their proofs
  -- are mechanical via `ext; simp` from `liftPathLocalOn_map` and `Path.map_trans`.

  -/
  end CoveringMap


  /- NOTE (temporary): Extraction `CoveringMap.evenlyCoveredAt` is deferred
     to keep Phase 0–2 build stable while we reintroduce local data. -/
  -- noncomputable def CoveringMap.evenlyCoveredAt
  --     {p : E → B} (h : CoveringMap p) (b : B) :
  --     EvenlyCoveredAt p b := by
  --   classical
  --   -- Stage 1: pick U and its properties
  --   let hexU := h.evenlyCovered b
  --   let U : Set B := Classical.choose hexU
  --   have hU : IsOpen U ∧ b ∈ U ∧
  --       ∃ (I : Type*) (_ : TopologicalSpace I) (_ : DiscreteTopology I),
  --         ∃ e : (Subtype fun e : E => p e ∈ U)
  --               ≃ₜ ((Subtype fun x : B => x ∈ U) × I),
  --           (∀ s, ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1) :=
  --     Classical.choose_spec hexU
  --   -- Stage 2: pick I and the rest for this I via nested `choose`
  --   let I : Type* := Classical.choose hU.2.2
  --   have hI : ∃ (_ : TopologicalSpace I) (_ : DiscreteTopology I),
  --         ∃ e : (Subtype fun e : E => p e ∈ U)
  --               ≃ₜ ((Subtype fun x : B => x ∈ U) × I),
  --           (∀ s, ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1) :=
  --     Classical.choose_spec hU.2.2
  --   -- Stage 3: pick topology and discrete structure
  --   let tI : TopologicalSpace I := Classical.choose hI
  --   have hID : ∃ (_ : DiscreteTopology I),
  --         ∃ e : (Subtype fun e : E => p e ∈ U)
  --               ≃ₜ ((Subtype fun x : B => x ∈ U) × I),
  --           (∀ s, ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1) :=
  --     Classical.choose_spec hI
  --   let dI : DiscreteTopology I := Classical.choose hID
  --   have hIE : ∃ e : (Subtype fun e : E => p e ∈ U)
  --               ≃ₜ ((Subtype fun x : B => x ∈ U) × I),
  --           (∀ s, ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1) :=
  --     Classical.choose_spec hID
  --   -- Stage 4: pick the homeomorphism and base compatibility
  --   let e : (Subtype fun e : E => p e ∈ U)
  --           ≃ₜ ((Subtype fun x : B => x ∈ U) × I) := Classical.choose hIE
  --   have hbase : ∀ s, ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1 :=
  --     Classical.choose_spec hIE
  --   -- Assemble
  --   exact
  --     { U := U
  --     , isOpenU := hU.1
  --     , memU := hU.2.1
  --     , I := I
  --     , instTopI := tI
  --     , instDiscI := dI
  --     , e := e
  --     , base := fun s => hbase s }

  -- (apply-level β for `liftPathOnCover` can be added here later, once the
  -- fold identity is finalized. We keep Phase 6 minimal and green.)

/-
Skeleton of the path-lifting statement: given a covering map, paths in the base
lift uniquely once an initial point in the fiber is fixed. The precise
implementation can follow mathlib’s path/interval conventions.
-/
  theorem path_lifting_theorem_skeleton (p : E → B) (_h : CoveringMap p) : True :=
    True.intro

end CoveringSpaces

/-
## C. Stone–Čech compactification — universal property skeleton

We encode βX together with the canonical map `ι : ContinuousMap X βX` and the universal
property for maps into compact Hausdorff spaces. This mirrors the md design,
yet leaves heavy analysis to future dedicated development.
-/

section StoneCechSkeleton

variable (X : Type*) [TopologicalSpace X]

structure StoneCechCompactification (X : Type*) [TopologicalSpace X] where
  βX : Type*
  instTopβX : TopologicalSpace βX
  instCompβX : CompactSpace βX
  instT2βX : T2Space βX
  ι : ContinuousMap X βX
  dense_range : DenseRange ι
  universal :
    ∀ (K : Type*) (_ : TopologicalSpace K) (_ : CompactSpace K) (_ : T2Space K),
      ∀ f : ContinuousMap X K, ∃! F : ContinuousMap βX K, F.comp ι = f

-- Provide typeclass instances for the carrier `βX` stored inside a compactification.
instance instTopologicalSpace_beta (S : StoneCechCompactification X) :
    TopologicalSpace S.βX := S.instTopβX

instance instCompactSpace_beta (S : StoneCechCompactification X) :
    CompactSpace S.βX := S.instCompβX

instance instT2Space_beta (S : StoneCechCompactification X) :
    T2Space S.βX := S.instT2βX

/-
Convenience API: abstract lifting and its `simp`-friendly consequences from the
universal property. This works for any `StoneCechCompactification X` instance,
including the trivial one below or a mathlib-backed one.
-/

noncomputable def StoneCechCompactification.lift
    {X : Type*} [TopologicalSpace X]
    (S : StoneCechCompactification X)
    (K : Type*) [TopologicalSpace K] [CompactSpace K] [T2Space K]
    (f : ContinuousMap X K) : ContinuousMap S.βX K :=
  Classical.choose (S.universal K (inferInstance) (inferInstance) (inferInstance) f)

@[simp] lemma StoneCechCompactification.lift_comp
    {X : Type*} [TopologicalSpace X]
    (S : StoneCechCompactification X)
    (K : Type*) [TopologicalSpace K] [CompactSpace K] [T2Space K]
    (f : ContinuousMap X K) :
    (S.lift K f).comp S.ι = f := by
  classical
  simpa [StoneCechCompactification.lift]
    using (Classical.choose_spec (S.universal K (inferInstance) (inferInstance) (inferInstance) f)).1

@[simp] lemma StoneCechCompactification.lift_comp_apply
    {X : Type*} [TopologicalSpace X]
    (S : StoneCechCompactification X)
    (K : Type*) [TopologicalSpace K] [CompactSpace K] [T2Space K]
    (f : ContinuousMap X K) (x : X) :
    ((S.lift K f).comp S.ι) x = f x := by
  classical
  have := S.lift_comp (K:=K) f
  exact congrArg (fun (h : ContinuousMap X K) => h x) this

lemma StoneCechCompactification.lift_unique
    {X : Type*} [TopologicalSpace X]
    (S : StoneCechCompactification X)
    (K : Type*) [TopologicalSpace K] [CompactSpace K] [T2Space K]
    (f : ContinuousMap X K) {G : ContinuousMap S.βX K}
    (hG : G.comp S.ι = f) :
    G = S.lift K f := by
  classical
  have huniq :=
    (Classical.choose_spec (S.universal K (inferInstance) (inferInstance) (inferInstance) f)).2
  -- huniq : ∀ y, (y.comp S.ι = f) → y = Classical.choose (...)
  have : G = Classical.choose (S.universal K (inferInstance) (inferInstance) (inferInstance) f) :=
    huniq G hG
  simpa [StoneCechCompactification.lift] using this

/-
Trivial compactification: when `X` is already compact Hausdorff, we can take
βX = X and ι = id. This satisfies the universal property with `F = f`.
This gives a working instance without importing mathlib’s `StoneCech`.
-/

noncomputable def StoneCechCompactification.trivial
    (X : Type*) [TopologicalSpace X]
    [CompactSpace X] [T2Space X] : StoneCechCompactification X :=
{ βX := X
, instTopβX := inferInstance
, instCompβX := inferInstance
, instT2βX := inferInstance
, ι := ContinuousMap.id X
, dense_range := by
    -- range(id) = univ is dense
    classical
    simpa using (denseRange_id : DenseRange (fun x : X => x))
, universal := by
    intro K _ _ _ f
    refine ⟨f, ?comp, ?uniq⟩
    · -- F ∘ ι = f with F = f and ι = id
      ext x; rfl
    · -- uniqueness: if G ∘ id = f then G = f
      intro G hG
      ext x
      -- evaluate both sides; `hG` gives function extensionality pointwise
      -- since `ι = id`, we have `G x = (G.comp (ContinuousMap.id X)) x`
      have := congrArg (fun (h : ContinuousMap X K) => h x) hG
      simpa using this
}

end StoneCechSkeleton

/-
## C'. Stone–Čech from mathlib (integration)

This realizes the abstract `StoneCechCompactification` by mathlib’s `StoneCech`:
βX := `StoneCech X`, ι := the canonical unit embedding, and the universal arrow
provided by `StoneCech.extend`. The uniqueness is discharged by density of ι
and T₂ on the codomain.
-/

section StoneCechFromMathlib

variable (X : Type*) [TopologicalSpace X]

noncomputable def StoneCechCompactification.fromMathlib :
    StoneCechCompactification X :=
{ βX := StoneCech X
, instTopβX := inferInstance
, instCompβX := inferInstance
, instT2βX := inferInstance
, ι := ⟨stoneCechUnit, continuous_stoneCechUnit⟩
, dense_range := by
    simpa using (denseRange_stoneCechUnit : DenseRange (stoneCechUnit : X → StoneCech X))
, universal := by
    intro K _ _ _ f
    classical
    -- Existence: use the canonical continuous extension from mathlib
    let F : ContinuousMap (StoneCech X) K :=
      ⟨stoneCechExtend (α := X) (β := K) (g := fun x => f x) f.continuous,
        continuous_stoneCechExtend (α := X) (β := K) (g := fun x => f x) f.continuous⟩
    refine ⟨F, ?comp, ?uniq⟩
    · -- β-rule: extension comp unit = original
      -- Prove pointwise using `simp` with the extension lemma.
      ext x
      -- Goal: F (stoneCechUnit x) = f x
      -- `simp [F]` unfolds `F` to `stoneCechExtend …`, and then
      -- `stoneCechExtend_extends` reduces it to `f x`.
      simp [F]
    · -- Uniqueness via `stoneCech_hom_ext`
      intro G hG
      have h₁ : Continuous (G : StoneCech X → K) := G.continuous
      have h₂ : Continuous (F : StoneCech X → K) := F.continuous
      -- both sides agree after precomposition with the unit map
      -- Start with equality of bundled maps after composing with `ι`:
      have hFcomp : F.comp ⟨stoneCechUnit, continuous_stoneCechUnit⟩ = f := by
        -- Same pointwise argument, now for `F`.
        ext x; simp [F]
      have hEq : G.comp ⟨stoneCechUnit, continuous_stoneCechUnit⟩
                = F.comp ⟨stoneCechUnit, continuous_stoneCechUnit⟩ := by
        simpa [hFcomp] using hG
      -- Now get pointwise equality on the dense image of `stoneCechUnit`:
      have hcomp : (G ∘ stoneCechUnit) = (F ∘ stoneCechUnit) := by
        ext x; simpa [Function.comp] using
          congrArg (fun (h : ContinuousMap X K) => h x) hEq
      -- Uniqueness of continuous extensions from dense subsets in T₂ spaces:
      -- `stoneCech_hom_ext` yields equality as functions, so we ext to upgrade to `ContinuousMap`.
      have hfun : (fun y => G y) = (fun y => F y) :=
        stoneCech_hom_ext (α := X) (β := K) h₁ h₂ hcomp
      ext y; simpa using congrArg (fun h => h y) hfun
}

end StoneCechFromMathlib

section StoneCechSmoke

variable (X : Type*) [TopologicalSpace X]

-- A tiny smoke test: the β-rule for `lift` reduces by `simp`/`ext`.
example {K : Type*} [TopologicalSpace K] [CompactSpace K] [T2Space K]
    (f : ContinuousMap X K) (x : X) :
  ((StoneCechCompactification.fromMathlib (X:=X)).lift K f).comp
      (StoneCechCompactification.fromMathlib (X:=X)).ι x = f x := by
  exact
    (StoneCechCompactification.lift_comp_apply
      (S := StoneCechCompactification.fromMathlib (X:=X)) (K:=K) f x)

end StoneCechSmoke

end Bourbaki.TopologyB

