/-
  Topology B — Bourbaki-style structuration via ordered pairs and morphisms

  This file is derived from:
    src/MyProjects/Topology/B/claude_topologyB_en.md

  Guiding spirit (Bourbaki):
  - Structure built from sets of ordered pairs (products) and morphisms (projections)
  - Universal properties expressed via factorization through projections
  - Emphasis on diagrammatic uniqueness (existence/uniqueness of mediating maps)

  Contents
  A. Product universality and exponential direction (skeleton)
  B. Covering maps (Bourbaki-flavored definition skeleton) and path lifting (statement stub)
  C. Stone–Čech compactification (universal property skeleton)

  Notes
  - Section A provides concrete lemmas fully in terms of projections and ordered pairs.
  - Sections B and C lay out faithful skeletons of the intended structures and universal properties
    so they can be refined without changing interfaces.
-/

import Mathlib.Topology.Basic
import Mathlib.Topology.Constructions.SumProd
import Mathlib.Topology.ContinuousMap.Basic
import Mathlib.Topology.CompactOpen
import Mathlib.Topology.Path
import Mathlib.Topology.Connected.PathConnected
import Mathlib.Topology.LocallyConstant.Basic
import Mathlib.Topology.Instances.Real.Lemmas
import Mathlib.Topology.Category.TopCat.Basic
import Mathlib.Topology.Category.TopCat.Limits.Basic
import Mathlib.CategoryTheory.Adjunction.Basic
import Mathlib.Tactic
-- Stone–Čech (module name may vary slightly by mathlib version):
import Mathlib.Topology.Compactification.StoneCech

namespace Bourbaki.TopologyB


/-
## A. Product universality via projections

We formalize the spirit “product = structure generated by projections”:
- continuity of projections `π₁, π₂`;
- continuity criterion for a map into a product via its components;
- existence and uniqueness of the mediating map `⟨f, g⟩`.
-/

section ProductUniversality

variable {T X Y : Type*}
variable [TopologicalSpace T] [TopologicalSpace X] [TopologicalSpace Y]

-- Projections (morphisms) from the ordered pair structure X × Y.
def π₁ : X × Y → X := fun p => p.1
def π₂ : X × Y → Y := fun p => p.2

lemma continuous_π₁ : Continuous (π₁ : X × Y → X) := by
  simpa [π₁] using continuous_fst

lemma continuous_π₂ : Continuous (π₂ : X × Y → Y) := by
  simpa [π₂] using continuous_snd

/-
Continuity into a product is equivalent to continuity of the two components
obtained by composing with the projections. This is the universal property
in Bourbaki’s language: the product topology is the coarsest making π₁, π₂
continuous, and continuity is tested componentwise.
-/
theorem continuous_iff_proj (h : T → X × Y) :
    Continuous h ↔
      Continuous (fun t => (h t).1) ∧ Continuous (fun t => (h t).2) := by
  constructor
  · intro hh
    exact ⟨continuous_fst.comp hh, continuous_snd.comp hh⟩
  · rintro ⟨h₁, h₂⟩
    -- Use `Continuous.prodMk` on the components to build continuity of `h`.
    -- We rewrite `h` as `fun t => ((h t).1, (h t).2)` to `simpa`.
    have : Continuous (fun t => ((h t).1, (h t).2)) := h₁.prodMk h₂
    simpa using this

/-
Existence and uniqueness of the mediating map into a product.
Given continuous `f : T → X` and `g : T → Y`, there is a unique continuous
`h : T → X × Y` such that `π₁ ∘ h = f` and `π₂ ∘ h = g`.
-/
theorem exists_unique_lift_to_prod {f : T → X} {g : T → Y}
    (hf : Continuous f) (hg : Continuous g) :
    ∃! h : T → X × Y,
      Continuous h ∧ (∀ t, (h t).1 = f t) ∧ (∀ t, (h t).2 = g t) := by
  refine ⟨(fun t => (f t, g t)), ?exist, ?uniq⟩
  · -- existence: the canonical pairing is continuous and has the desired components
    refine And.intro ?hcont (And.intro ?hfst ?hsnd)
    · simpa using hf.prodMk hg
    · intro t; rfl
    · intro t; rfl
  · -- uniqueness: any other h with the same components must be pointwise equal
    intro h hh
    rcases hh with ⟨_hc, hfst, hsnd⟩
    apply funext
    intro t
    -- Compare components, then use `Prod.ext`.
    apply Prod.ext
    · simpa using hfst t
    · simpa using hsnd t

/-
As a quick corollary, pairing with projections recovers the map.
This is the β-rule for the universal property.
-/
lemma fst_pair_eq (f : T → X) (g : T → Y) (t : T) : ((f t, g t).1) = f t := rfl
lemma snd_pair_eq (f : T → X) (g : T → Y) (t : T) : ((f t, g t).2) = g t := rfl

end ProductUniversality

/-
## A. (Category level) Diagonal ⊣ Product in `TopCat`

We implement the diagonal functor Δ : TopCat ⥤ TopCat × TopCat and the
product functor × : TopCat × TopCat ⥤ TopCat, and exhibit the adjunction
Hom(ΔX, (Y, Z)) ≃ Hom(X, Y × Z). The hom-sets reduce to pairs of continuous
maps versus a single continuous map into the product, matching the Bourbaki
ordered-pair perspective.
-/

section TopCatAdjunction

open CategoryTheory

/- Δ: duplicate objects and morphisms. -/
def deltaTop : TopCat ⥤ TopCat × TopCat where
  obj X := ⟨X, X⟩
  map {X Y} (f : X ⟶ Y) := ⟨f, f⟩
  map_id X := by
    -- identities are componentwise
    ext <;> rfl
  map_comp {X Y Z} (f : X ⟶ Y) (g : Y ⟶ Z) := by
    -- composition is componentwise
    ext <;> rfl

/- ×: binary product on objects as cartesian product of spaces; on morphisms
it acts via `ContinuousMap.prodMap`.
-/
def prodTop : TopCat × TopCat ⥤ TopCat where
  obj X := TopCat.of (X.1 × X.2)
  map {X Y} (f : X ⟶ Y) :=
    (⟨(fun p : X.1 × X.2 => (f.1 p.1, f.2 p.2)), by
      -- continuity by components
      have h1 : Continuous fun p : X.1 × X.2 => f.1 p.1 := by
        simpa using ((ContinuousMap.continuous (f.1)).comp continuous_fst)
      have h2 : Continuous fun p : X.1 × X.2 => f.2 p.2 := by
        simpa using ((ContinuousMap.continuous (f.2)).comp continuous_snd)
      exact h1.prodMk h2⟩ : ContinuousMap (X.1 × X.2) (Y.1 × Y.2))
  map_id X := by
    -- identity acts componentwise
    ext p <;> rfl
  map_comp {X Y Z} (f : X ⟶ Y) (g : Y ⟶ Z) := by
    -- composition is componentwise
    ext p <;> rfl

/- The hom-set equivalence for the adjunction. -/
noncomputable def homEquivDeltaProd
    (X : TopCat) (YZ : TopCat × TopCat) :
    ((deltaTop.obj X) ⟶ YZ) ≃ (X ⟶ prodTop.obj YZ) :=
{ toFun :=
    fun fg =>
      (⟨(fun x => (fg.1 x, fg.2 x)), by
        simpa using ((ContinuousMap.continuous (fg.1)).prodMk (ContinuousMap.continuous (fg.2)))⟩ :
        ContinuousMap X (YZ.1 × YZ.2))
, invFun :=
    fun h =>
      ((⟨(fun x => (h x).1), by
          simpa using (continuous_fst.comp (ContinuousMap.continuous h))⟩ : ContinuousMap X YZ.1),
       (⟨(fun x => (h x).2), by
          simpa using (continuous_snd.comp (ContinuousMap.continuous h))⟩ : ContinuousMap X YZ.2))
, left_inv := by
    intro fg; ext x <;> rfl
, right_inv := by
    intro h; ext p <;> rfl }

/- The adjunction Δ ⊣ × specialized to `TopCat`. -/
-- (Optional) One can package `homEquivDeltaProd` into an adjunction using
-- `Adjunction.mkOfHomEquiv`. We keep the hom-set equivalence explicit here.

end TopCatAdjunction

/-
## A'. Exponential direction (skeleton)

We record currying/uncurrying at the level of plain functions (ordered pairs →
functions into function spaces) and reserve continuity/topological refinements
for future development (e.g. under `[LocallyCompactSpace]` hypotheses). This
keeps the Bourbaki pairing perspective explicit and light.
-/

section ExponentialSkeleton

variable {X Y Z : Type*}

/-- Currying: functions on a product are functions returning functions. -/
def curry (f : X × Y → Z) : X → Y → Z :=
  fun x y => f (x, y)

/-- Uncurrying: functions returning functions are functions on a product. -/
def uncurry (g : X → Y → Z) : X × Y → Z :=
  fun p => g p.1 p.2

@[simp] lemma curry_uncurry (g : X → Y → Z) : curry (uncurry g) = g := rfl
@[simp] lemma uncurry_curry (f : X × Y → Z) : uncurry (curry f) = f := by
  funext p; cases p; rfl

end ExponentialSkeleton

section ExponentialLaw

open ContinuousMap

variable {X Y Z : Type*}
variable [TopologicalSpace X] [TopologicalSpace Y] [TopologicalSpace Z]

/-- Exponential law: `ContinuousMap (X × Y) Z ≃ₜ ContinuousMap X (ContinuousMap Y Z)` under local compactness. -/
noncomputable def exponential_homeo
    [LocallyCompactSpace X] [LocallyCompactSpace Y] :
    ContinuousMap (X × Y) Z ≃ₜ ContinuousMap X (ContinuousMap Y Z) :=
  Homeomorph.curry (X:=X) (Y:=Y) (Z:=Z)

@[simp] lemma exponential_homeo_apply
    [LocallyCompactSpace X] [LocallyCompactSpace Y]
    (F : ContinuousMap (X × Y) Z) (x : X) (y : Y) :
    (exponential_homeo (X:=X) (Y:=Y) (Z:=Z) F x) y = F (x, y) := rfl

@[simp] lemma exponential_homeo_symm_apply
    [LocallyCompactSpace X] [LocallyCompactSpace Y]
    (G : ContinuousMap X (ContinuousMap Y Z)) (p : X × Y) :
    (exponential_homeo (X:=X) (Y:=Y) (Z:=Z)).symm G p = G p.1 p.2 := rfl

/-- Continuity of the evaluation map `(f, y) ↦ f y` under the compact-open topology. -/
theorem continuous_eval
    [LocallyCompactPair Y Z] :
    Continuous (fun p : ContinuousMap Y Z × Y => p.1 p.2) := by
  simpa using (ContinuousEval.continuous_eval :
    Continuous (fun p : ContinuousMap Y Z × Y => p.1 p.2))

end ExponentialLaw

/-
## B. Covering spaces — Bourbaki-style skeleton

We package the essence of an evenly covered neighborhood in terms of a local
homeomorphism to a product `U × I` with discrete fiber `I`. This keeps the
ordered-pair-and-projection viewpoint explicit. The definition below is a
faithful skeleton: it captures the shape and the key data while staying light.
-/


section CoveringSpaces

open scoped Topology

variable {E B : Type*}
variable [TopologicalSpace E] [TopologicalSpace B]

/- Small helpers to stabilize endpoints and `simp` across mathlib versions. -/

@[inline] def I0 : unitInterval := ⟨0, by simp⟩
@[inline] def I1 : unitInterval := ⟨1, by simp⟩

@[simp] lemma coe_I0 : ((I0 : unitInterval) : ℝ) = 0 := rfl
@[simp] lemma coe_I1 : ((I1 : unitInterval) : ℝ) = 1 := rfl

/- Normalized API for `Path.map`: pass a function and its continuity. -/
@[simp] lemma path_map_apply
  {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
  {x y : X} (γ : Path x y) (f : X → Y) (hf : Continuous f) (t : unitInterval) :
  (γ.map (f := f) hf) t = f (γ t) := rfl

@[simp] lemma path_source_I0
  {X : Type*} [TopologicalSpace X] {x y : X} (γ : Path x y) :
  γ Bourbaki.TopologyB.I0 = x := by
  -- 構造体のフィールド等式を“直接”使う：
  -- Path を分解すると `srcγ : γ.toContinuousMap I0 = x` が得られる
  cases' γ with toγ srcγ tgtγ
  simpa [Bourbaki.TopologyB.I0] using srcγ

@[simp] lemma path_target_I1
  {X : Type*} [TopologicalSpace X] {x y : X} (γ : Path x y) :
  γ Bourbaki.TopologyB.I1 = y := by
  cases' γ with toγ srcγ tgtγ
  simpa [Bourbaki.TopologyB.I1] using tgtγ


/-- パスレベル：`map` は `trans` と可換 -/
lemma map_trans_path
  {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
  {x y z : X} (α : Path x y) (β : Path y z)
  (f : X → Y) (hf : Continuous f) :
  (α.trans β).map (f := f) hf = (α.map (f := f) hf).trans (β.map (f := f) hf) := by
  ext t; simp [path_map_apply]

/-- 点評価版：`map` は `trans` と可換（`t` で評価） -/
lemma map_trans_path_apply
  {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
  {x y z : X} (α : Path x y) (β : Path y z)
  (f : X → Y) (hf : Continuous f) (t : unitInterval) :
  ((α.trans β).map (f := f) hf) t
    = ((α.map (f := f) hf).trans (β.map (f := f) hf)) t := by
  have H := map_trans_path (α:=α) (β:=β) (f:=f) (hf:=hf)
  simpa using congrArg (fun δ : Path _ _ => δ t) H




/-
`CoveringMap p` asserts that around every base point `b : B`, the preimage of a
small neighborhood `U` decomposes as a product `U × I` for a discrete index
set `I`. We keep the commuting condition with the projection implicit in this
first skeleton, focusing on the core decomposition datum.
-/
  structure CoveringMap (p : E → B) : Prop where
    continuous : Continuous p
    evenlyCovered :
      ∀ b : B,
        ∃ (U : Set B), IsOpen U ∧ b ∈ U ∧
          ∃ (I : Type*) (_ : TopologicalSpace I) (_ : DiscreteTopology I),
          ∃ e : (Subtype fun e : E => p e ∈ U) ≃ₜ ((Subtype fun x : B => x ∈ U) × I),
            (∀ s, ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1)

  /-
  Evenly-covered data at a base point `b`. This packages the witness of
  `CoveringMap.evenlyCovered b` into a reusable record with convenient
  projections and helpers. We store the topology and discreteness on the fiber
  index `I` as fields (to be re-instantiated locally when needed).
  -/
  structure EvenlyCoveredAt (p : E → B) (b : B) where
    U : Set B
    isOpenU : IsOpen U
    memU : b ∈ U
    I : Type*
    instTopI : TopologicalSpace I
    instDiscI : @DiscreteTopology I instTopI
    e : (Subtype fun e : E => p e ∈ U)
        ≃ₜ ((Subtype fun x : B => x ∈ U) × I)
    base : ∀ s,
      ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1

  /-
  Provide the stored topology/discrete topology on `d.I` as instances so that
  typeclass search always picks exactly the topology bundled in `d`.
  This avoids instance mismatch errors like "synthesized instance not
  definitionally equal" when working with products `({x // x ∈ d.U} × d.I)`.
  -/
  -- Note: we intentionally do NOT provide global instances for `d.I` here.
  -- Per the guideline, we will introduce `haveI : TopologicalSpace d.I := d.instTopI`
  -- (and similarly for `DiscreteTopology`) only within proofs that need them.


  namespace EvenlyCoveredAt

  variable {p : E → B} {b : B}

  /-
  NOTE (temporary): We defer `sheet`/`sheet_base` to avoid instance definality
  issues. We will rely on the bundled `sheetMap` defined via `d.e.symm` and
  prove β at the bundled level.
  -/
  -- noncomputable def sheet (d : EvenlyCoveredAt p b)
  --     (i : d.I) : (Subtype fun x : B => x ∈ d.U)
  --       → (Subtype fun e : E => p e ∈ d.U) :=
  -- by
  --   classical
  --   exact fun u => d.e.toEquiv.symm (u, i)

  -- lemma sheet_base (d : EvenlyCoveredAt p b) (i : d.I)
  --     (u : Subtype fun x : B => x ∈ d.U) :
  --     p ((d.sheet i u).1) = u.1 := by
  --   classical
  --   set s := d.e.toEquiv.symm (u, i)
  --   have hs : d.e.toEquiv s = (u, i) := by
  --     subst s; simpa using (d.e.toEquiv.left_inv (u, i))
  --   have hb' : ((d.e.toEquiv s).1 : Subtype fun x : B => x ∈ d.U).1 = p s.1 := by
  --     simpa using (d.base s)
  --   have hfst : ((d.e.toEquiv s).1) = u := congrArg Prod.fst hs
  --   have hfst_val : ((d.e.toEquiv s).1).1 = u.1 := by
  --     simpa using congrArg Subtype.val hfst
  --   have : u.1 = p s.1 := by
  --     simpa [hfst_val] using hb'
  --   change p ((d.e.toEquiv.symm (u, i)).1) = u.1
  --   simpa [s] using this.symm

  -- (Optional) If needed later: continuity of the unbundled sheet map can be
  -- recovered from `sheetMap` and `inclE`. We omit it here to avoid instance
  -- definality issues during early phases.

  /-- The inclusion `U ↪ B` as a bundled continuous map. -/
  noncomputable def inclB (d : EvenlyCoveredAt p b) :
      ContinuousMap (Subtype fun x : B => x ∈ d.U) B :=
    ⟨(fun u => u.1), continuous_subtype_val⟩

  /-- The inclusion `{e // p e ∈ U} ↪ E` as a bundled continuous map. -/
  noncomputable def inclE (d : EvenlyCoveredAt p b) :
      ContinuousMap (Subtype fun e : E => p e ∈ d.U) E :=
    ⟨(fun s => s.1), continuous_subtype_val⟩

  -- The `i`-th sheet as a bundled continuous map (haveI scoped in the proof).
  noncomputable def sheetMap (d : EvenlyCoveredAt p b) (i : d.I) :
      ContinuousMap (Subtype fun x : B => x ∈ d.U)
                    (Subtype fun e : E => p e ∈ d.U) :=
  by
    classical
    letI : TopologicalSpace d.I := d.instTopI
    refine ⟨(fun u => d.e.symm (u, i)), ?_⟩
    have hpair : Continuous fun u : Subtype (fun x : B => x ∈ d.U) => (u, i) := by
      have h1 : Continuous fun u : Subtype (fun x : B => x ∈ d.U) => u := continuous_id
      have h2 : Continuous fun _u : Subtype (fun x : B => x ∈ d.U) => i := continuous_const
      simpa using h1.prodMk h2
    have hcont : Continuous (fun u : Subtype (fun x : B => x ∈ d.U) => d.e.symm (u, i)) :=
      d.e.continuous_symm.comp hpair
    simpa using hcont

  /- β-rule at the bundled `ContinuousMap` level:
     `(p ∘ inclE ∘ sheetMap i) = inclB` on `U`. -/
  @[simp] lemma sheet_comp_eq_inclB (h : CoveringMap p)
      (d : EvenlyCoveredAt p b) (i : d.I) :
      (((⟨p, h.continuous⟩ : ContinuousMap E B)).comp (d.inclE)).comp (d.sheetMap i) = d.inclB := by
    classical
    -- Align the topology instance on `d.I` with the one stored in `d`.
    letI : TopologicalSpace d.I := d.instTopI
    ext u
    -- Evaluate pointwise and use `d.base` with `s = d.e.symm (u,i)`.
    change p ((d.e.symm (u, i)).1) = u.1
    set s := d.e.symm (u, i)
    have hs : d.e s = (u, i) := by
      subst s; simpa using (d.e.left_inv (u, i))
    have hb : ((d.e s).1 : Subtype fun x : B => x ∈ d.U).1 = p s.1 := d.base s
    -- From `hs`, the first projection equals `u` as a subtype.
    have hfst : ((d.e s).1) = u := congrArg Prod.fst hs
    have hfst_val : ((d.e s).1).1 = u.1 := by
      simpa using congrArg Subtype.val hfst
    -- Combine: `u.1 = p s.1`.
    have : u.1 = p s.1 := by
      simpa [hfst_val] using hb
    -- Rewrite back the definition of `s`.
    simpa [s] using this.symm



  /- ### Local lifting for maps landing in `U` -/

  -- Phase 3: local lifting for maps, scoped under a single local instance.
  section LocalLift
  variable {Z : Type*} [TopologicalSpace Z]

  /-- Package a map `γ : Z → B` with image in `U` as a map into the subtype. -/
  noncomputable def toSubtype (d : EvenlyCoveredAt p b)
      (γ : ContinuousMap Z B) (hγ : ∀ z, γ z ∈ d.U) :
      ContinuousMap Z (Subtype fun x : B => x ∈ d.U) :=
    ⟨(fun z => ⟨γ z, hγ z⟩),
      by
        have hcont : Continuous fun z => γ z := γ.continuous
        exact hcont.subtype_mk hγ⟩

  /-- Choose the sheet index determined by a point `e` in the fiber over `U`. -/
  noncomputable def sheetIndexAt (d : EvenlyCoveredAt p b)
      (e : E) (hUE : p e ∈ d.U) : d.I :=
  by
    classical
    exact ((d.e ⟨e, hUE⟩).2)

  /-- The `sheetMap` at index `sheetIndexAt e` passes through the base point `e`. -/
  lemma sheetMap_through (d : EvenlyCoveredAt p b)
      (e : E) (hUE : p e ∈ d.U) :
      d.sheetMap (d.sheetIndexAt e hUE) ⟨p e, hUE⟩ = ⟨e, hUE⟩ := by
    classical
    -- Align the topology instance on `d.I` with the one stored in `d`.
    letI : TopologicalSpace d.I := d.instTopI
    -- Apply `d.e` to both sides and use injectivity.
    apply d.e.injective
    -- Left-hand side under `d.e`.
    have lhs : d.e (d.sheetMap (d.sheetIndexAt e hUE) ⟨p e, hUE⟩)
        = (⟨p e, hUE⟩, d.sheetIndexAt e hUE) := by
      simpa [sheetMap] using d.e.left_inv (⟨p e, hUE⟩, d.sheetIndexAt e hUE)
    -- Right-hand side under `d.e` equals `(⟨p e, hUE⟩, d.sheetIndexAt e hUE)`.
    have hfst : (d.e ⟨e, hUE⟩).1 = ⟨p e, hUE⟩ := by
      apply Subtype.ext
      -- `d.base` gives `((d.e ⟨e, hUE⟩).1).1 = p e`, matching the expected direction
      simpa using (d.base ⟨e, hUE⟩)
    have hrs : d.e ⟨e, hUE⟩ = (⟨p e, hUE⟩, d.sheetIndexAt e hUE) := by
      apply Prod.ext
      · exact hfst
      · rfl
    -- Conclude by rewriting the RHS with `hrs`.
    simpa [hrs] using lhs

  /-- Local lift of `γ` along the `i`-th sheet. -/
  noncomputable def liftAlong (d : EvenlyCoveredAt p b) (h : CoveringMap p)
      (i : d.I) (γ : ContinuousMap Z B) (hγ : ∀ z, γ z ∈ d.U) :
      ContinuousMap Z E :=
    ((d.inclE).comp (d.sheetMap i)).comp (d.toSubtype γ hγ)

  /-- β-rule for the local lift: composing with `p` recovers `γ`. -/
  @[simp] lemma liftAlong_beta (d : EvenlyCoveredAt p b) (h : CoveringMap p)
      (i : d.I) (γ : ContinuousMap Z B) (hγ : ∀ z, γ z ∈ d.U) :
      ((⟨p, h.continuous⟩ : ContinuousMap E B)).comp (d.liftAlong h i γ hγ) = γ := by
    classical
    -- Reassociate and use the bundled β-rule for sheets, then evaluate.
    change ((((⟨p, h.continuous⟩ : ContinuousMap E B)).comp d.inclE).comp (d.sheetMap i)).comp
      (d.toSubtype γ hγ) = γ
    have hβ := EvenlyCoveredAt.sheet_comp_eq_inclB (p:=p) (h:=h) (d:=d) (i:=i)
    -- hβ : ((⟨p,_⟩).comp d.inclE).comp (d.sheetMap i) = d.inclB
    ext z
    simp [liftAlong, toSubtype, inclB, ContinuousMap.comp_apply, hβ]

  end LocalLift

  /-!
  Auxiliary e-level β for `liftAlong` and a uniqueness-on-a-fixed-sheet
  principle. These avoid introducing `sheet` objects and stick to bundled
  maps and `e.injective`.
  -/

  /-- e-level β: transporting the `liftAlong` by the chart `e` yields the
  pair `(u, i)` with base point `u` and fixed sheet index `i`. -/
  lemma liftAlong_e_apply
      (d : EvenlyCoveredAt p b) (h : CoveringMap p)
      (i : d.I) {Z : Type*} [TopologicalSpace Z]
      (γ : ContinuousMap Z B) (hγ : ∀ z, γ z ∈ d.U) (z : Z) :
      d.e ⟨(d.liftAlong (p:=p) h i γ hγ) z,
            by
              -- Membership via the bundled sheet β at `s := (toSubtype γ hγ) z`.
              classical
              let s := (d.toSubtype γ hγ) z
              have hβp := EvenlyCoveredAt.sheet_comp_eq_inclB (p:=p) (h:=h) (d:=d) (i:=i)
              have hpeq : p (((d.inclE).comp (d.sheetMap i)) s) = s.1 := by
                simpa [ContinuousMap.comp_apply, EvenlyCoveredAt.inclB]
                  using congrArg (fun F => F s) hβp
              -- Convert `s.2 : s.1 ∈ d.U` to the required goal using `congrArg`.
              have hxEq : (p (d.inclE ((d.sheetMap i) s)) ∈ d.U) = (s.1 ∈ d.U) := by
                simpa [ContinuousMap.comp_apply] using congrArg (fun x => x ∈ d.U) hpeq
              exact Eq.mp (hxEq.symm) s.2
        ⟩
        = (⟨γ z, hγ z⟩, i) :=
  by
    classical
    letI : TopologicalSpace d.I := d.instTopI
    -- Abbreviate the base point in the chart.
    let u : Subtype (fun x : B => x ∈ d.U) := ⟨γ z, hγ z⟩
    -- Show the lifted subtype point coincides with `sheetMap i u`.
    have hs : (⟨(d.liftAlong (p:=p) h i γ hγ) z,
                by
                  have hβp := EvenlyCoveredAt.sheet_comp_eq_inclB (p:=p) (h:=h) (d:=d) (i:=i)
                  have hpeq : p (((d.inclE).comp (d.sheetMap i)) u) = u.1 := by
                    simpa [ContinuousMap.comp_apply, EvenlyCoveredAt.inclB]
                      using congrArg (fun F => F u) hβp
                  have hxEq : (p (d.inclE ((d.sheetMap i) u)) ∈ d.U) = (u.1 ∈ d.U) := by
                    simpa [ContinuousMap.comp_apply] using congrArg (fun x => x ∈ d.U) hpeq
                  exact Eq.mp (hxEq.symm) u.2⟩
              : Subtype (fun e' : E => p e' ∈ d.U))
            = d.sheetMap i u := by
      apply Subtype.ext
      -- Underlying E-values are definitionally equal.
      simp [u, EvenlyCoveredAt.liftAlong, EvenlyCoveredAt.toSubtype,
            ContinuousMap.comp_apply, EvenlyCoveredAt.inclE, EvenlyCoveredAt.sheetMap]
    -- Apply `e` and use left-inverse for `(u, i)`.
    have hRight : d.e (d.sheetMap i u) = (u, i) := by
      simpa [EvenlyCoveredAt.sheetMap] using d.e.left_inv (u, i)
    have hL : d.e
        (⟨(d.liftAlong (p:=p) h i γ hγ) z,
          by
            -- Membership via sheet β at `s := (toSubtype γ hγ) z`.
            classical
            let s := (d.toSubtype γ hγ) z
            have hβp := EvenlyCoveredAt.sheet_comp_eq_inclB (p:=p) (h:=h) (d:=d) (i:=i)
            have hpeq : p (((d.inclE).comp (d.sheetMap i)) s) = s.1 := by
              simpa [ContinuousMap.comp_apply, EvenlyCoveredAt.inclB]
                using congrArg (fun F => F s) hβp
            have hxEq : (p (d.inclE ((d.sheetMap i) s)) ∈ d.U) = (s.1 ∈ d.U) := by
              simpa [ContinuousMap.comp_apply] using congrArg (fun x => x ∈ d.U) hpeq
            exact Eq.mp (hxEq.symm) s.2⟩)
        = (u, i) := by
      simpa [hs] using hRight
    simpa [u]

  /-- Uniqueness on a fixed sheet: any continuous lift with the same base
  `γ` and second coordinate constantly `i` coincides with `liftAlong` on `i`. -/
  lemma liftAlong_unique_in_sheet
      (d : EvenlyCoveredAt p b) (h : CoveringMap p)
      (i : d.I) {Z : Type*} [TopologicalSpace Z]
      (γ : ContinuousMap Z B) (hγ : ∀ z, γ z ∈ d.U)
      (δ : ContinuousMap Z E)
      (hβ : ((⟨p, h.continuous⟩ : ContinuousMap E B)).comp δ = γ)
      (hsheet : ∀ z, (d.e ⟨δ z, by
                        have hx0 := congrArg (fun F => F z) hβ
                        have hx : p (δ z) = γ z := by
                          simpa [ContinuousMap.comp_apply] using hx0
                        have hxEq : (p (δ z) ∈ d.U) = (γ z ∈ d.U) := by
                          simpa [hx]
                        exact Eq.mp hxEq.symm (hγ z)⟩).2 = i) :
      δ = d.liftAlong (p:=p) h i γ hγ :=
  by
    classical
    letI : TopologicalSpace d.I := d.instTopI
    ext z
    set sL : Subtype (fun e' : E => p e' ∈ d.U) :=
      ⟨δ z, by
        have hx := congrArg (fun F => F z) hβ
        have hx' : p (δ z) = γ z := by
          simpa [ContinuousMap.comp_apply] using hx
        have hxEq : (p (δ z) ∈ d.U) = (γ z ∈ d.U) := by
          simpa [hx']
        exact Eq.mp hxEq.symm (hγ z)⟩
    set sR : Subtype (fun e' : E => p e' ∈ d.U) :=
      ⟨(d.liftAlong (p:=p) h i γ hγ) z,
        by
          -- Use the sheet β at `s := (toSubtype γ hγ) z` to get membership.
          classical
          let s := (d.toSubtype γ hγ) z
          have hβp := EvenlyCoveredAt.sheet_comp_eq_inclB (p:=p) (h:=h) (d:=d) (i:=i)
          have hpeq : p (((d.inclE).comp (d.sheetMap i)) s) = s.1 := by
            simpa [ContinuousMap.comp_apply, EvenlyCoveredAt.inclB]
              using congrArg (fun F => F s) hβp
          have hxEq : (p (d.inclE ((d.sheetMap i) s)) ∈ d.U) = (s.1 ∈ d.U) := by
            simpa [ContinuousMap.comp_apply] using congrArg (fun x => x ∈ d.U) hpeq
          -- rewrite the goal via `liftAlong` def to the LHS of `hxEq` and close by `s.2`.
          simpa [EvenlyCoveredAt.liftAlong, EvenlyCoveredAt.toSubtype, ContinuousMap.comp_apply]
            using Eq.mp (hxEq.symm) s.2⟩
    have hL : d.e sL = (⟨γ z, hγ z⟩, i) := by
      have h2 : (d.e sL).2 = i := by simpa [sL] using hsheet z
      have hb : ((d.e sL).1 : Subtype fun x : B => x ∈ d.U).1 = p sL.1 := d.base sL
      have hx : p sL.1 = γ z := by
        have hx0 := congrArg (fun F => F z) hβ
        simpa [sL, ContinuousMap.comp_apply] using hx0
      have hfst : (d.e sL).1 = ⟨γ z, hγ z⟩ := by
        apply Subtype.ext; simpa [hx] using hb
      exact Prod.ext hfst h2
    have hR : d.e sR = (⟨γ z, hγ z⟩, i) :=
      d.liftAlong_e_apply (p:=p) (h:=h) (i:=i) (γ:=γ) (hγ:=hγ) z
    have hs : sL = sR := d.e.injective (by simpa [sL, sR] using hL.trans hR.symm)
    -- extract equality of underlying values
    have := congrArg Subtype.val hs
    simpa [sL, sR] using this


  end EvenlyCoveredAt

  /-
  ### Local path lifting (image contained in one evenly-covered chart)

  For a path `γ : Path b₀ b₁` whose image is contained in an evenly-covered
  neighborhood `U` around `b₀`, we can choose a sheet indexed by the starting
  fiber point and lift `γ` along that sheet to obtain a path starting at the
  chosen fiber point. The β-rule and uniqueness are immediate from the bundled
  β-rule for `liftAlong` and the injectivity of the product chart.
  -/

  /-
  NOTE (temporary): Path lifting and β-lemmas are deferred until Phase 3–6.
  The entire `CoveringMap` path-lifting block is commented out.
  -/
  namespace CoveringMap


  open EvenlyCoveredAt

  variable {p : E → B}

  /-- Local path lift in an evenly-covered neighborhood containing the whole path image. -/
  noncomputable def liftPathLocal
      (h : CoveringMap p) {b₀ b₁ : B}
      (d : EvenlyCoveredAt p b₀)
      (γ : Path b₀ b₁)
      (e₀ : E) (h₀ : p e₀ = b₀)
      (hγU : ∀ t : unitInterval, γ t ∈ d.U) :
      Path e₀ ((d.liftAlong h (d.sheetIndexAt e₀ (by simpa [h₀] using d.memU))
        γ.toContinuousMap hγU) I1) :=
  by
    classical
    -- Prepare endpoint inclusions and the chosen sheet index
    have hUE₀ : p e₀ ∈ d.U := by simpa [h₀] using d.memU
    set i : d.I := d.sheetIndexAt e₀ hUE₀ with hi
    -- The lifted continuous map on `I := unitInterval`.
    let γE : ContinuousMap (↑unitInterval) E := d.liftAlong h i γ.toContinuousMap hγU
    -- Named endpoints of the unit interval (as a subtype)
    let t0 : ↑unitInterval := I0
    let t1 : ↑unitInterval := I1
    -- Endpoint at 0 is the chosen fiber point `e₀`.
    have hγE0 : γE t0 = e₀ := by
      -- compute the start value explicitly
      have hU0 : γ t0 ∈ d.U := hγU t0
      -- Compare with the distinguished sheet-map through e₀ at the base point.
      have Hsheet : (d.sheetMap i ⟨p e₀, hUE₀⟩).1 = e₀ := by
        have := EvenlyCoveredAt.sheetMap_through (p:=p) (b:=b₀) d e₀ hUE₀
        simpa [i] using congrArg Subtype.val this
      -- Change the base from `p e₀` to `b₀` using `h₀`.
      have Hbase_b0 : (d.sheetMap i ⟨b₀, by simpa [h₀] using d.memU⟩).1 = e₀ := by
        -- rewrite the input subtype using `p e₀ = b₀`
        have Heq : (⟨b₀, by simpa [h₀] using d.memU⟩ : Subtype fun x : B => x ∈ d.U)
          = ⟨p e₀, hUE₀⟩ := by
          apply Subtype.ext
          simpa [h₀]
        -- transport along equality on the input
        simpa [EvenlyCoveredAt.sheetMap, Heq] using Hsheet
      -- Now change from `b₀` to the true start `γ t0` using `γ.source`.
      have hγ0 : γ t0 = b₀ := by simpa [t0] using (path_source_I0 (γ := γ))
      have Hstart : (d.sheetMap i ⟨γ t0, hU0⟩).1 = e₀ := by
        have Heq : (⟨γ t0, hU0⟩ : Subtype fun x : B => x ∈ d.U)
          = ⟨b₀, by simpa [h₀] using d.memU⟩ := by
          apply Subtype.ext; simpa [hγ0]
        simpa [EvenlyCoveredAt.sheetMap, Heq] using Hbase_b0
      -- unfold the definition of γE at 0
      simpa [γE, EvenlyCoveredAt.liftAlong, EvenlyCoveredAt.toSubtype,
              EvenlyCoveredAt.inclE, EvenlyCoveredAt.sheetMap]
        using Hstart
    -- Package as a path by taking the underlying bundled map and endpoints.
    refine
      { toContinuousMap := γE
      , source' := hγE0
      , target' := rfl }

  /-- β-rule for the local path lift (bundled path-level version). -/
  lemma liftPathLocal_map_apply
      (h : CoveringMap p) {b₀ b₁ : B}
      (d : EvenlyCoveredAt p b₀)
      (γ : Path b₀ b₁)
      (e₀ : E) (h₀ : p e₀ = b₀)
      (hγU : ∀ t : unitInterval, γ t ∈ d.U) (t : ↑unitInterval) :
      ((liftPathLocal (p:=p) h d γ e₀ h₀ hγU).map (f := p) h.continuous) t = γ t := by
    classical
    -- set up the sheet index used in `liftPathLocal`
    have hUE₀ : p e₀ ∈ d.U := by simpa [h₀] using d.memU
    set i : d.I := d.sheetIndexAt e₀ hUE₀ with hi
    -- bundled β for `liftAlong`
    have hβ := EvenlyCoveredAt.liftAlong_beta (p:=p) (b:=b₀) (d:=d) (h:=h)
      (i:=i) (γ:=γ.toContinuousMap) (hγ:=hγU)
    -- evaluate both sides at `t`
    -- simplify both sides to pointwise equality
    simpa [liftPathLocal, path_map_apply, EvenlyCoveredAt.liftAlong,
            EvenlyCoveredAt.toSubtype, ContinuousMap.comp_apply]
      using congrArg (fun F => F t) hβ

  -- Uniqueness for the local lift with fixed start can be proved by transporting
  -- both lifts along `d.e` and using injectivity; we postpone this global proof
  -- until the gluing step is in place.

  end CoveringMap


  -- We avoid adding a general `@[simp]` lemma for `Path.map_trans` here to keep
  -- dependencies light; in the few places we need it, we use `ext; rfl`.

  /-
  ### Subpaths and reparametrization of the unit interval

  We provide a linear reparametrization `segMap a b : I → I` that maps `0 ↦ a`,
  `1 ↦ b`, and use it to define the subpath `γ.subpath a b`.
  -/

  -- Local path utilities are namespaced under `Bourbaki.TopologyB.Path`.
  -- Phase 1: enabled.
  namespace Path

  open scoped Topology

  variable {b₀ b₁ : B}

  /-- Linear reparametrization of the unit interval sending `0 ↦ a` and `1 ↦ b`. -/
  noncomputable def segMap (a b : unitInterval) : ContinuousMap unitInterval unitInterval :=
  by
    -- Define the underlying real-valued function.
    refine ⟨(fun t => ⟨(1 - (t : ℝ)) * (a : ℝ) + (t : ℝ) * (b : ℝ), ?mem⟩), ?cont⟩
    · -- Membership in [0,1].
      -- Nonnegativity
      have ha0 : 0 ≤ (a : ℝ) := a.2.1
      have hb0 : 0 ≤ (b : ℝ) := b.2.1
      have ht0 : 0 ≤ (t : ℝ) := t.2.1
      have ht1 : (t : ℝ) ≤ 1 := t.2.2
      have h1t0 : 0 ≤ 1 - (t : ℝ) := sub_nonneg.mpr ht1
      have h1t1 : (1 - (t : ℝ)) + (t : ℝ) = 1 := by ring
      have h0 : 0 ≤ (1 - (t : ℝ)) * (a : ℝ) + (t : ℝ) * (b : ℝ) := by
        have h₁ : 0 ≤ (1 - (t : ℝ)) * (a : ℝ) := mul_nonneg h1t0 ha0
        have h₂ : 0 ≤ (t : ℝ) * (b : ℝ) := mul_nonneg ht0 hb0
        exact add_nonneg h₁ h₂
      have ha1 : (a : ℝ) ≤ 1 := a.2.2
      have hb1 : (b : ℝ) ≤ 1 := b.2.2
      have hle : (1 - (t : ℝ)) * (a : ℝ) + (t : ℝ) * (b : ℝ)
                  ≤ (1 - (t : ℝ)) * 1 + (t : ℝ) * 1 := by
        refine add_le_add ?_ ?_
        · exact mul_le_mul_of_nonneg_left ha1 h1t0
        · exact mul_le_mul_of_nonneg_left hb1 ht0
      have hone : (1 - (t : ℝ)) * 1 + (t : ℝ) * 1 = 1 := by
        simpa [h1t1] using by ring
      exact ⟨h0, by simpa [hone] using hle⟩
    · -- Continuity.
      have ht : Continuous fun t : unitInterval => (t : ℝ) := continuous_subtype_val
      have h₁ : Continuous fun t : unitInterval => (1 - (t : ℝ)) := continuous_const.sub ht
      have h₂ : Continuous fun _ : unitInterval => (a : ℝ) := continuous_const
      have h₃ : Continuous fun _ : unitInterval => (b : ℝ) := continuous_const
      have hleft : Continuous fun t : unitInterval => (1 - (t : ℝ)) * (a : ℝ) := h₁.mul h₂
      have hright : Continuous fun t : unitInterval => (t : ℝ) * (b : ℝ) := ht.mul h₃
      have hcont : Continuous fun t : unitInterval =>
          (1 - (t : ℝ)) * (a : ℝ) + (t : ℝ) * (b : ℝ) := hleft.add hright
      -- upgrade to continuity into the subtype via `subtype_mk`
      exact hcont.subtype_mk (by
        intro t
        -- Reproduce the membership proof pointwise
        have ha0 : 0 ≤ (a : ℝ) := a.2.1
        have hb0 : 0 ≤ (b : ℝ) := b.2.1
        have ht0 : 0 ≤ (t : ℝ) := t.2.1
        have ht1 : (t : ℝ) ≤ 1 := t.2.2
        have h1t0 : 0 ≤ 1 - (t : ℝ) := sub_nonneg.mpr ht1
        have h1t1 : (1 - (t : ℝ)) + (t : ℝ) = 1 := by ring
        have h0 : 0 ≤ (1 - (t : ℝ)) * (a : ℝ) + (t : ℝ) * (b : ℝ) := by
          have h₁ : 0 ≤ (1 - (t : ℝ)) * (a : ℝ) := mul_nonneg h1t0 ha0
          have h₂ : 0 ≤ (t : ℝ) * (b : ℝ) := mul_nonneg ht0 hb0
          exact add_nonneg h₁ h₂
        have ha1 : (a : ℝ) ≤ 1 := a.2.2
        have hb1 : (b : ℝ) ≤ 1 := b.2.2
        have hle : (1 - (t : ℝ)) * (a : ℝ) + (t : ℝ) * (b : ℝ)
                    ≤ (1 - (t : ℝ)) * 1 + (t : ℝ) * 1 := by
          refine add_le_add ?_ ?_
          · exact mul_le_mul_of_nonneg_left ha1 h1t0
          · exact mul_le_mul_of_nonneg_left hb1 ht0
        have hone : (1 - (t : ℝ)) * 1 + (t : ℝ) * 1 = 1 := by
          simpa [h1t1] using by ring
        exact ⟨h0, by simpa [hone] using hle⟩)

  @[simp] lemma segMap_I0 (a b : unitInterval) :
      segMap a b I0 = a := by
    ext; simp [segMap, I0, one_mul]

  @[simp] lemma segMap_I1 (a b : unitInterval) :
      segMap a b I1 = b := by
    ext; simp [segMap, I1]

  -- Friendly names requested in the guide
  @[simp] lemma segMap_zero (a b : unitInterval) :
      segMap a b (0 : unitInterval) = a := by
    simpa [I0] using (segMap_I0 a b)

  @[simp] lemma segMap_one (a b : unitInterval) :
      segMap a b (1 : unitInterval) = b := by
    simpa [I1] using (segMap_I1 a b)

  /-- Subpath of `γ` between times `a` and `b` in the unit interval. -/
  noncomputable def subpath (γ : Path b₀ b₁)
      (a b : unitInterval) : Path (γ a) (γ b) :=
  { toContinuousMap := γ.toContinuousMap.comp (segMap a b)
  , source' := by
      change (γ.toContinuousMap (segMap a b I0)) = γ a
      simpa [ContinuousMap.comp_apply] using congrArg (fun x => γ.toContinuousMap x)
        (segMap_I0 a b)
  , target' := by
      change (γ.toContinuousMap (segMap a b I1)) = γ b
      simpa [ContinuousMap.comp_apply] using congrArg (fun x => γ.toContinuousMap x)
        (segMap_I1 a b) }

  /-- Retag a path by changing its endpoints along equalities. -/
  noncomputable def retag {X : Type*} [TopologicalSpace X]
      {x y x' y' : X} (γ : Path x y) (hx : x = x') (hy : y = y') :
      Path x' y' :=
  { toContinuousMap := γ.toContinuousMap
  , source' := by simpa [hx] using γ.source'
  , target' := by simpa [hy] using γ.target' }

  @[simp] lemma retag_apply {X : Type*} [TopologicalSpace X]
      {x y x' y' : X} (γ : Path x y) (hx : x = x') (hy : y = y') (t : unitInterval) :
      (retag (γ:=γ) hx hy) t = γ t := rfl

  lemma retag_trans {X : Type*} [TopologicalSpace X]
      {x y z x' y' z' : X}
      (α : Path x y) (β : Path y z)
      (hx : x = x') (hy : y = y') (hz : z = z') :
      (retag (γ:=α.trans β) hx hz)
        = (retag (γ:=α) hx hy).trans (retag (γ:=β) hy hz) := by
    ext t <;> rfl


  end Path

  /-
  NOTE (temporary): Localized subinterval lifting and 2-segment gluing are
  deferred; comment out to keep build green.
  -/
  namespace CoveringMap

  open Path EvenlyCoveredAt

  variable {p : E → B}

  /-- Local lift on a subinterval `[a,b]` whose image lands in an evenly-covered chart. -/
  noncomputable def liftPathLocalOn
      (h : CoveringMap p) {b₀ b₁ : B}
      (γ : Path b₀ b₁)
      (a b : unitInterval)
      (d : EvenlyCoveredAt p (γ a))
      (eₐ : E) (hₐ : p eₐ = γ a)
      (hγU : ∀ t : unitInterval, γ (Bourbaki.TopologyB.Path.segMap a b t) ∈ d.U) :
      Path eₐ ((d.liftAlong h (d.sheetIndexAt eₐ (by
        have : γ a ∈ d.U := by
          simpa using hγU I0
        simpa [hₐ] using this))
        (γ.toContinuousMap.comp (Bourbaki.TopologyB.Path.segMap a b))
        (by intro t; simpa using hγU t)) I1) :=
  by
    classical
    -- Prepare the sheet index at the starting endpoint a
    have hUa : γ a ∈ d.U := by simpa using hγU I0
    set i : d.I := d.sheetIndexAt eₐ (by simpa [hₐ] using hUa) with hi
    -- The lifted continuous map on the subinterval
    let γE : ContinuousMap (↑unitInterval) E :=
      d.liftAlong h i (γ.toContinuousMap.comp (Bourbaki.TopologyB.Path.segMap a b))
        (by intro t; simpa using hγU t)
    -- Endpoints in the unit interval subtype
    let t0 : ↑unitInterval := I0
    let t1 : ↑unitInterval := I1
    -- Startpoint: use the sheetMap_through at γ a and rewrite by hₐ
    have hγE0 : γE t0 = eₐ := by
      have : (d.sheetMap i ⟨γ a, hUa⟩).1 = eₐ := by
        -- through property at the starting base point
        have := EvenlyCoveredAt.sheetMap_through (p:=p) d eₐ (by simpa [hₐ] using hUa)
        simpa [i, hₐ] using congrArg Subtype.val this
      -- evaluate γE at t0 and simplify
      simpa [γE, EvenlyCoveredAt.liftAlong, EvenlyCoveredAt.toSubtype,
              EvenlyCoveredAt.inclE, EvenlyCoveredAt.sheetMap,
              Bourbaki.TopologyB.Path.segMap, t0, I0]
        using this
    -- Package as a path
    refine
      { toContinuousMap := γE
      , source' := hγE0
      , target' := rfl }

  /-- β-rule (apply-level) for the localized lift on `[a,b]`. -/
  lemma liftPathLocalOn_map_apply
      (h : CoveringMap p) {b₀ b₁ : B}
      (γ : Path b₀ b₁)
      (a b : unitInterval)
      (d : EvenlyCoveredAt p (γ a))
      (eₐ : E) (hₐ : p eₐ = γ a)
      (hγU : ∀ t : unitInterval, γ (Bourbaki.TopologyB.Path.segMap a b t) ∈ d.U)
      (t : unitInterval) :
      ((liftPathLocalOn (p:=p) h γ a b d eₐ hₐ hγU).map (f := p) h.continuous) t
        = (Bourbaki.TopologyB.Path.subpath γ a b) t := by
    classical
    -- bundled β for the lifted map on the subinterval (pointwise)
    have hβ := EvenlyCoveredAt.liftAlong_beta (p:=p) (b:=γ a) (d:=d) (h:=h)
      (i:=d.sheetIndexAt eₐ (by
        have : γ a ∈ d.U := by simpa using hγU I0
        simpa [hₐ] using this))
      (γ:=γ.toContinuousMap.comp (Bourbaki.TopologyB.Path.segMap a b))
      (hγ:=by intro t'; simpa using hγU t')
    have := congrArg (fun F => F t) hβ
    simpa [liftPathLocalOn, path_map_apply, EvenlyCoveredAt.liftAlong,
            EvenlyCoveredAt.toSubtype, ContinuousMap.comp_apply]
      using this

  /-- Glue two local lifts over adjacent subintervals `[a,c]` and `[c,b]`. -/
  noncomputable def liftPathTwo
      (h : CoveringMap p) {b₀ b₁ : B}
      (γ : Path b₀ b₁)
      (a c b : unitInterval)
      (h_ac : (a : ℝ) ≤ c ∧ c ≤ b)
      (d₁ : EvenlyCoveredAt p (γ a)) (d₂ : EvenlyCoveredAt p (γ c))
      (eₐ : E) (hₐ : p eₐ = γ a)
      (hγU₁ : ∀ t : unitInterval, γ (Bourbaki.TopologyB.Path.segMap a c t) ∈ d₁.U)
      (hγU₂ : ∀ t : unitInterval, γ (Bourbaki.TopologyB.Path.segMap c b t) ∈ d₂.U) :
      Path eₐ ((liftPathLocalOn (p:=p) h γ c b d₂
        ((liftPathLocalOn (p:=p) h γ a c d₁ eₐ hₐ hγU₁) I1)
        (by
          -- equality `p (Γ₁ 1) = γ c` via apply-level local β at endpoint
          have hβ := liftPathLocal_map_apply (p:=p) h d₁ (Bourbaki.TopologyB.Path.subpath γ a c)
            eₐ hₐ (by intro t; simpa [Bourbaki.TopologyB.Path.subpath, ContinuousMap.comp_apply] using hγU₁ t) I1
          simpa [Bourbaki.TopologyB.Path.subpath, path_map_apply] using hβ)
        hγU₂) I1) :=
  by
    classical
    -- Define the two local lifts and compose them via `Path.trans`.
    let Γ₁ := liftPathLocalOn (p:=p) h γ a c d₁ eₐ hₐ hγU₁
    let e_c := Γ₁ I1
    have hcstart : p e_c = γ c := by
      -- pointwise β at endpoint using the apply-level lemma
      have := liftPathLocal_map_apply (p:=p) h d₁ (Bourbaki.TopologyB.Path.subpath γ a c)
        eₐ hₐ (by intro t; simpa [Bourbaki.TopologyB.Path.subpath, ContinuousMap.comp_apply] using hγU₁ t) I1
      simpa [Γ₁, Bourbaki.TopologyB.Path.subpath, path_map_apply] using this
    let Γ₂ := liftPathLocalOn (p:=p) h γ c b d₂ e_c hcstart hγU₂
    -- Compose the two lifted paths.
    exact Γ₁.trans Γ₂

 end CoveringMap

  /-
  ### Finite path covers and global lifting

  We package a finite partition of the unit interval together with evenly-covered
  charts per subinterval, and glue the corresponding local lifts into a global
  lift over `[0,1]`.
  -/

  /-
  NOTE (temporary): Finite path cover and global fold are deferred; comment out
  to complete early phases first.
  -/
  namespace CoveringMap


variable {E B : Type*} [TopologicalSpace E] [TopologicalSpace B]
variable {p : E → B}

/-- A finite cover of a path by evenly-covered neighborhoods. -/
structure PathCover {b₀ b₁ : B} (p : E → B) (γ : Path b₀ b₁) where
  n : Nat
  pts : Fin (n+1) → unitInterval
  start : pts ⟨0, by exact Nat.succ_pos _⟩ = I0
  stop  : pts ⟨n, by exact Nat.lt_succ_self _⟩ = I1
  charts : ∀ i : Fin n, EvenlyCoveredAt p (γ (pts i.castSucc))
  inU : ∀ i : Fin n, ∀ t : unitInterval,
    γ (Bourbaki.TopologyB.Path.segMap (pts i.castSucc) (pts i.succ) t) ∈ (charts i).U

/-- 左畳みの核：`k : Fin (n+1)` ごとに `b₀ → γ (pts k)` のパスを返す。 -/
noncomputable def coverConcatCore {b₀ b₁ : B}
    (γ : Path b₀ b₁) (cov : PathCover (p:=p) γ) :
    (k : Fin (cov.n + 1)) → Path b₀ (γ (cov.pts k))
| ⟨0, hk0⟩ =>
  -- ★ 0枝は常に b₀ を返す定数関数として定義
  let h0 : b₀ = γ (cov.pts ⟨0, hk0⟩) := by
    have hpts0 : cov.pts (0 : Fin (cov.n+1)) = I0 := by simpa using cov.start
    have hγI0 : γ I0 = b₀ := by cases' γ with _ src _; simpa [I0] using src
    simpa [hpts0] using hγI0.symm
  { toContinuousMap := ⟨(fun _t => b₀), continuous_const⟩,
    source' := rfl,
    target' := by simpa [h0] }
| ⟨Nat.succ k, hk⟩ =>
  let hklt : k < cov.n := Nat.succ_lt_succ_iff.mp hk
  let hk'  : k ≤ cov.n := le_of_lt hklt
  let i    : Fin cov.n := ⟨k, hklt⟩
  (coverConcatCore γ cov ⟨k, Nat.lt_succ_of_le hk'⟩).trans
    (Bourbaki.TopologyB.Path.subpath γ (cov.pts i.castSucc) (cov.pts i.succ))


/- apply レベルで使いやすくする小補題（simp で前に進める） -/

@[simp] lemma coverConcatCore_zero_apply
  {b₀ b₁ : B} (γ : Path b₀ b₁) (cov : PathCover (p:=p) γ) (t : unitInterval) :
  (coverConcatCore (p:=p) γ cov (0 : Fin (cov.n+1))) t = b₀ := by
  change ((coverConcatCore (p:=p) γ cov (0 : Fin (cov.n+1))).toContinuousMap t) = b₀
  have h0idx : (0 : Fin (cov.n+1)) = ⟨0, Nat.succ_pos _⟩ := by ext; rfl
  rw [h0idx]
  unfold coverConcatCore
  rfl





  /-- Succ-branch of `coverConcatCore` exposed as a `Path.trans` equality. -/
  lemma coverConcatCore_succ_path {b₀ b₁ : B}
      (γ : Path b₀ b₁) (cov : PathCover (p:=p) γ)
      (k : Nat) (hk : Nat.succ k < cov.n + 1) :
      let hklt : k < cov.n := Nat.succ_lt_succ_iff.mp hk
      let i : Fin cov.n := ⟨k, hklt⟩
      have hk' : k ≤ cov.n := le_of_lt hklt
      coverConcatCore (p:=p) γ cov ⟨Nat.succ k, hk⟩
        = (coverConcatCore (p:=p) γ cov ⟨k, Nat.lt_succ_of_le hk'⟩).trans
          (Bourbaki.TopologyB.Path.subpath γ (cov.pts i.castSucc) (cov.pts i.succ)) :=
  by
    intro hklt i hk'
    -- Align Fin indices used in the definition
    have hcast : (⟨k, Nat.lt_succ_of_le hk'⟩ : Fin (cov.n+1)) = i.castSucc := by
      ext; rfl
    have hsuc : (⟨k+1, hk⟩ : Fin (cov.n+1)) = i.succ := by
      ext; rfl
    -- Push index equalities through `cov.pts`
    have hcastPts : cov.pts ⟨k, Nat.lt_succ_of_le hk'⟩ = cov.pts i.castSucc := by
      simpa using congrArg (fun j : Fin (cov.n+1) => cov.pts j) hcast
    have hsucPts : cov.pts ⟨k+1, hk⟩ = cov.pts i.succ := by
      simpa using congrArg (fun j : Fin (cov.n+1) => cov.pts j) hsuc
    -- Pointwise equality by unfolding the succ-branch and rewriting indices
    ext t
    simp [coverConcatCore, Nat.lt_succ_of_le hk', hcastPts, hsucPts,
          Bourbaki.TopologyB.Path.subpath, ContinuousMap.comp_apply]






/-- Succ-branch の適用版（`t` で評価した形）。 -/
lemma coverConcatCore_succ_apply {b₀ b₁ : B}
    (γ : Path b₀ b₁) (cov : PathCover (p:=p) γ)
    (k : Nat) (hk : Nat.succ k < cov.n + 1) (t : unitInterval) :
  let hklt : k < cov.n := Nat.succ_lt_succ_iff.mp hk
  let i : Fin cov.n := ⟨k, hklt⟩
  have hk' : k ≤ cov.n := le_of_lt hklt
  ((coverConcatCore (p:=p) γ cov ⟨k, Nat.lt_succ_of_le hk'⟩).trans
      (Bourbaki.TopologyB.Path.subpath γ (cov.pts i.castSucc) (cov.pts i.succ))) t
    = (coverConcatCore (p:=p) γ cov ⟨Nat.succ k, hk⟩) t :=
by
  intro hklt i hk'
  -- パスレベル補題を t で評価して向きを反転
  have H := coverConcatCore_succ_path (p:=p) (γ:=γ) (cov:=cov) k hk
  simpa using (congrArg (fun Δ => Δ t) H).symm

  /-- A finite cover of a path by evenly-covered neighborhoods, indexed by a finite
  increasing sequence of parameters `pts : Fin (n+1) → I`. On each subinterval
  `[pts i, pts (i.succ)]`, the image of the path is contained in the neighborhood
  `charts i`. We keep only the data needed to perform gluing; monotonicity is
  not used explicitly here as we only rely on endpoints of subpaths. -/




-- Concatenation over the whole finite cover (retagged to end at `b₁`). -/
noncomputable def coverConcat {b₀ b₁ : B}
    (γ : Path b₀ b₁) (cov : PathCover (p:=p) γ) : Path b₀ b₁ :=
by
  classical
  let δ := coverConcatCore (p:=p) γ cov ⟨cov.n, by simpa using Nat.lt_succ_self _⟩
  refine
    { toContinuousMap := δ.toContinuousMap
    , source' := by simpa using δ.source'
    , target' := by
        -- `pts n = I1`
        have hidx : (⟨cov.n, by simpa using Nat.lt_succ_self _⟩ : Fin (cov.n+1))
                  = ⟨cov.n, by exact Nat.lt_succ_self _⟩ := by ext; rfl
        have hptsn : cov.pts ⟨cov.n, by simpa using Nat.lt_succ_self _⟩ = I1 := by
          simpa [hidx] using cov.stop
        -- `γ I1 = b₁` を等式で取り、`pts n` に置換
        have hb1 : γ (cov.pts ⟨cov.n, by simpa using Nat.lt_succ_self _⟩) = b₁ := by
          simpa [← hptsn] using (path_target_I1 (γ := γ))
        simpa [hb1] using δ.target' }



  /-- Startpoint of the concatenated path equals `b₀` (apply-level). -/
  lemma coverConcat_I0 {b₀ b₁ : B}
      (γ : Path b₀ b₁) (cov : PathCover (p:=p) γ) :
      (coverConcat (p:=p) γ cov) I0 = b₀ := by
    simpa [I0] using (coverConcat (p:=p) γ cov).source'

  /-- Endpoint of the concatenated path equals `b₁` (apply-level). -/
  lemma coverConcat_I1 {b₀ b₁ : B}
      (γ : Path b₀ b₁) (cov : PathCover (p:=p) γ) :
      (coverConcat (p:=p) γ cov) I1 = b₁ := by
    simpa [I1] using (coverConcat (p:=p) γ cov).target'





-- どの namespace でも良いですが、重複定義にならない位置に置いてください
@[simp] lemma path_refl_apply {X} [TopologicalSpace X] (x : X) (t : unitInterval) :
  (Path.refl x) t = x := rfl


lemma path_map_trans_apply {X Y : Type*}
  [TopologicalSpace X] [TopologicalSpace Y]
  {x y z : X} (α : Path x y) (β : Path y z) (f : X → Y) (hf : Continuous f) (t : unitInterval) :
  ((α.trans β).map (f := f) hf) t
    = ((α.map (f := f) hf).trans (β.map (f := f) hf)) t := by
  simp [path_map_apply]

  /-
  Apply-level identity: evaluating `coverConcat` equals evaluating the fold
  nucleus at the final index. (Commented out on request.)

  lemma coverConcat_apply {b₀ b₁ : B}
      (γ : Path b₀ b₁) (cov : PathCover (p:=p) γ) (t : unitInterval) :
      (coverConcat (p:=p) γ cov) t
        = (coverConcatCore (p:=p) γ cov ⟨cov.n, by simpa using Nat.lt_succ_self _⟩) t := by
    simp [coverConcat]
  -/


  -- We deliberately avoid asserting that `coverConcat` pointwise equals a
  -- single `subpath` of `γ`: the concatenation via `Path.trans` composes
  -- segments with a different (piecewise) reparametrization than a single
  -- linear `segMap`. This keeps the fold nucleus compatible with later β-lemmas.

  /-!
  Small helpers for Phase 6 gluing proofs.
  -/

  -- Mapping commutes with concatenation, path-level (use `ext; simp`). -/




/- Apply-level corollary of `coverConcatCore_succ_path`.
    **Note the symmetry**: we want `((core k).trans …) t = (core (k+1)) t`. -/



  /-
  -- Concatenation of the subpaths determined by a `PathCover`. This is a
  canonical reparametrization of `γ` by the partition points `cov.pts`. -/
  -- NOTE: Phase 6 (coverConcat/liftPathOnCover) legacy version (commented out).
  /- noncomputable def coverConcat {b₀ b₁ : B}
      (γ : Path b₀ b₁) (cov : PathCover (p:=p) γ) : Path b₀ b₁ :=
  by
    classical
    -- Build the concatenation up to step `k` with target `γ (pts k)`.
    let build : ∀ k, (hk : k ≤ cov.n) → Path b₀ (γ (cov.pts ⟨k, Nat.lt_succ_of_le hk⟩))
    | 0, hk =>
      -- At k = 0, `pts 0 = 0`, so the trivial path works.
      have h0 : γ (cov.pts ⟨0, Nat.succ_pos _⟩) = b₀ := by
        simpa [cov.start] using (path_source_I0 (γ := γ))
      -- Adjust the target via rewriting to match the required type.
      { toContinuousMap := (Path.refl b₀).toContinuousMap
      , source' := by simpa using (Path.refl b₀).source'
      , target' := by simpa [h0] using (Path.refl b₀).target' }
    | (Nat.succ k), hk =>
      -- Previous stage
      have hk' : k ≤ cov.n := le_trans (Nat.le_succ k) hk
      have hklt : k < cov.n := lt_of_lt_of_le (Nat.lt_succ_self k) hk
      let i : Fin cov.n := ⟨k, hklt⟩
      -- Glue previous with the subpath on `[pts i, pts i.succ]`.
      (build k hk').trans (Bourbaki.TopologyB.Path.subpath γ (cov.pts i.castSucc) (cov.pts i.succ))
    -- final path ends at `γ 1 = b₁`
    { toContinuousMap := (build cov.n le_rfl).toContinuousMap
    , source' := by simpa using (build cov.n le_rfl).source
    , target' := by
        have : γ (cov.pts ⟨cov.n, Nat.lt_succ_self _⟩) = b₁ := by
          have : γ I1 = b₁ := by simpa using (path_target_I1 (γ := γ))
          simpa [cov.stop] using this
        simpa [this] using (build cov.n le_rfl).target } -/

  /-- Glue local lifts along the subintervals of a `PathCover` to obtain a global lift
  over the whole interval. Returns the endpoint in the fiber and the lifted path. -/
noncomputable def liftPathOnCover
    (h : CoveringMap p) {b₀ b₁ : B}
    (γ : Path b₀ b₁)
    (cov : PathCover (p:=p) γ)
    (e₀ : E) (h₀ : p e₀ = b₀) :
    Σ e : E, Path e₀ e :=
by
  classical
  -- Invariant: p e_k = γ (pts k)
  have build :
      ∀ k, (hk : k ≤ cov.n) →
        Subtype (fun x : Σ e : E, Path e₀ e =>
          p x.1 = γ (cov.pts ⟨k, Nat.lt_succ_of_le hk⟩)) :=
  by
    intro k
    -- 帰納：k = 0 / k+1
    induction' k with k ih
    -- base: k = 0
    · intro hk
      -- ここは一発で閉じる：未解決ゴール（?m）を残さない
      exact
        ⟨⟨e₀, Path.refl e₀⟩, by
          -- pts 0 = I0
          have hpts0 : cov.pts (0 : Fin (cov.n+1)) = I0 := by
            simpa using cov.start
          -- γ I0 = b₀（等式として直接取得；True 化を避ける）
          have hγI0 : γ I0 = b₀ := by
            cases' γ with toγ srcγ tgtγ
            simpa [I0] using srcγ
          -- b₀ = γ (pts 0) を作って右辺を書き換える
          have hb0 : b₀ = γ (cov.pts (0 : Fin (cov.n+1))) := by
            simpa [hpts0] using hγI0.symm
          -- 目標 p e₀ = γ (pts 0)
          simpa [hb0] using h₀
        ⟩
    -- step: k → k+1
    · intro hkSucc
      -- k+1 ≤ n から k ≤ n と k < n を得る
      have hk'  : k ≤ cov.n := le_trans (Nat.le_succ k) hkSucc
      have hklt : k < cov.n := lt_of_lt_of_le (Nat.lt_succ_self k) hkSucc
      -- IH：k 段までの (e_k, Γ_k) と不変量 p e_k = γ (pts k)
      rcases ih hk' with ⟨⟨e_k, Γ_k⟩, hkrel⟩
      -- 次区間のインデックス
      let i : Fin cov.n := ⟨k, hklt⟩
      -- castSucc で添字をそろえる
      have hidx : (⟨k, Nat.lt_succ_of_le hk'⟩ : Fin (cov.n+1)) = i.castSucc := by
        ext; rfl
      have hstart : p e_k = γ (cov.pts i.castSucc) := by
        simpa [hidx] using hkrel
      -- 小区間の持ち上げ
      let Γseg :=
        liftPathLocalOn (p:=p) h γ (cov.pts i.castSucc) (cov.pts i.succ)
          (cov.charts i) e_k hstart (cov.inU i)
      -- k+1 の不変量：p (Γseg 1) = γ (pts i.succ)
      have hend : p (Γseg I1) = γ (cov.pts i.succ) := by
        have hβ :=
          liftPathLocalOn_map_apply (p:=p) h γ (cov.pts i.castSucc) (cov.pts i.succ)
            (cov.charts i) e_k hstart (cov.inU i) I1
        simpa [Γseg, path_map_apply, Bourbaki.TopologyB.Path.subpath,
               ContinuousMap.comp_apply] using hβ
      -- 次状態：終点と貼り合わせた Path
      exact ⟨⟨Γseg I1, Γ_k.trans Γseg⟩, by simpa using hend⟩

  -- k = n の結果を取り出して返す
  let R := build cov.n le_rfl
  exact ⟨R.val.1, R.val.2⟩



/-- (apply レベルの β) グローバル持ち上げの像は、`coverConcat` に一致する。 -/
lemma liftPathOnCover_map_apply
  (h : CoveringMap p) {b₀ b₁ : B}
  (γ : Path b₀ b₁)
  (cov : CoveringMap.PathCover (p:=p) γ)
  (e₀ : E) (h₀ : p e₀ = b₀)
  (t : unitInterval) :
  ((CoveringMap.liftPathOnCover (p:=p) h γ cov e₀ h₀).2.map (f := p) h.continuous) t
    = (CoveringMap.coverConcat (p:=p) γ cov) t :=
by
  classical
  -- 強い帰納：段 k ごとに点毎 β と端点不変量を持つ Σ-データを構築
  have build :
    ∀ k, (hk : k ≤ cov.n) →
      Subtype (fun x : Σ e : E, Path e₀ e =>
        (∀ u : unitInterval,
          ((x.2).map (f := p) h.continuous) u
            = (CoveringMap.coverConcatCore (p:=p) γ cov ⟨k, Nat.lt_succ_of_le hk⟩) u)
        ∧ (p x.1 = γ (cov.pts ⟨k, Nat.lt_succ_of_le hk⟩))) :=
  by
    intro k
    induction' k with k ih
    · -- k = 0
      intro hk
      refine ⟨⟨e₀, Path.refl e₀⟩, ?_⟩
      refine And.intro ?hpath0 ?hend0
      · intro u
        simp [Bourbaki.TopologyB.path_map_apply, CoveringMap.coverConcatCore, h₀]
      ·
        have hpts0 : cov.pts (0 : Fin (cov.n+1)) = Bourbaki.TopologyB.I0 := by
          simpa using cov.start
        have hγI0 : γ Bourbaki.TopologyB.I0 = b₀ := by
          cases' γ with _ src _
          simpa [Bourbaki.TopologyB.I0] using src
        have hb0 : b₀ = γ (cov.pts (0 : Fin (cov.n+1))) := by
          simpa [hpts0] using hγI0.symm
        simpa [hb0] using h₀
    · -- k → k+1
      intro hkSucc
      have hk'  : k ≤ cov.n := Nat.le_trans (Nat.le_succ k) hkSucc
      have hklt : k < cov.n := lt_of_lt_of_le (Nat.lt_succ_self k) hkSucc
      rcases ih hk' with ⟨⟨e_k, Γ_k⟩, hpair_k⟩
      have hpath_k :
        ∀ u : unitInterval,
          (Γ_k.map (f := p) h.continuous) u
            = (CoveringMap.coverConcatCore (p:=p) γ cov ⟨k, Nat.lt_succ_of_le hk'⟩) u :=
        hpair_k.1
      have hend_k :
        p e_k = γ (cov.pts ⟨k, Nat.lt_succ_of_le hk'⟩) :=
        hpair_k.2

      -- インデックス整列と次区間のローカル持ち上げ
      let i : Fin cov.n := ⟨k, hklt⟩
      have hidx :
        (⟨k, Nat.lt_succ_of_le hk'⟩ : Fin (cov.n+1)) = i.castSucc := by
        ext; rfl
      have hstart : p e_k = γ (cov.pts i.castSucc) := by
        simpa [hidx] using hend_k

      let Γseg :=
        CoveringMap.liftPathLocalOn (p:=p) h γ (cov.pts i.castSucc) (cov.pts i.succ)
          (cov.charts i) e_k hstart (cov.inU i)

      -- apply レベル β（区間像）
      have hseg_apply :
        ∀ u : unitInterval,
          (Γseg.map (f := p) h.continuous) u
            = (Bourbaki.TopologyB.Path.subpath γ (cov.pts i.castSucc) (cov.pts i.succ)) u :=
      by
        intro u
        simpa [Γseg, Bourbaki.TopologyB.Path.subpath, ContinuousMap.comp_apply] using
          (CoveringMap.liftPathLocalOn_map_apply (p:=p) h γ
            (cov.pts i.castSucc) (cov.pts i.succ) (cov.charts i)
            e_k hstart (cov.inU i) u)

      -- 端点不変量（k+1）
      have hend_k1 :
        p (Γseg Bourbaki.TopologyB.I1) = γ (cov.pts i.succ) := by
        have hβ :=
          CoveringMap.liftPathLocalOn_map_apply (p:=p) h γ
            (cov.pts i.castSucc) (cov.pts i.succ) (cov.charts i)
            e_k hstart (cov.inU i) Bourbaki.TopologyB.I1
        simpa [Γseg, Bourbaki.TopologyB.Path.subpath, ContinuousMap.comp_apply] using hβ

      -- 段 k+1 の構築
      refine ⟨⟨Γseg Bourbaki.TopologyB.I1, Γ_k.trans Γseg⟩, ?_⟩
      refine And.intro ?hpath_succ ?hend_succ

      · -- pointwise β at stage k+1
        intro u
        -- (1) map と trans の交換（点評価版）
        have hmt :
          ((Γ_k.trans Γseg).map (f := p) h.continuous) u
            = (((Γ_k.map (f := p) h.continuous).trans
                (Γseg.map (f := p) h.continuous)) u) := by
          simpa using
            Bourbaki.TopologyB.map_trans_path_apply
              (α:=Γ_k) (β:=Γseg) (f:=p) (hf:=h.continuous) (t:=u)

        -- (2) 因子の置換（端点を cast で整合）
        have hA_path :
          (Γ_k.map (f := p) h.continuous)
            =
          ((CoveringMap.coverConcatCore (p:=p) γ cov ⟨k, Nat.lt_succ_of_le hk'⟩)
          ).cast (by simpa using h₀)
                  (by simpa using hend_k) := by
          ext s; simpa [Path.cast] using hpath_k s

        have hB_path :
          (Γseg.map (f := p) h.continuous)
            =
          ((Bourbaki.TopologyB.Path.subpath γ (cov.pts i.castSucc) (cov.pts i.succ))
          ).cast (by simpa using hstart)
                  (by simpa using hend_k1) := by
          ext s; simpa [Γseg, Bourbaki.TopologyB.Path.subpath, Path.cast] using hseg_apply s

        -- (3) hmt の右辺だけを書き換える（`simp_rw` で局所置換）
        have hmap_trans₁ :
          ((Γ_k.trans Γseg).map (f := p) h.continuous) u
            =
          ((CoveringMap.coverConcatCore (p:=p) γ cov ⟨k, Nat.lt_succ_of_le hk'⟩).trans
              (Bourbaki.TopologyB.Path.subpath γ (cov.pts i.castSucc) (cov.pts i.succ))) u :=
        by
          have h := hmt
          simp_rw [hA_path, hB_path] at h
          simpa [Path.cast] using h

        -- (4) 添字合わせ： i.castSucc / i.succ → ⟨k⟩ / ⟨k+1⟩
        have hi_succ :
          (i.succ : Fin (cov.n+1)) = ⟨k+1, Nat.lt_succ_of_le hkSucc⟩ := by
          ext; rfl
        have hsub :
          (Bourbaki.TopologyB.Path.subpath γ (cov.pts i.castSucc) (cov.pts i.succ))
            =
          (Bourbaki.TopologyB.Path.subpath γ
            (cov.pts ⟨k, Nat.lt_succ_of_le hk'⟩)
            (cov.pts ⟨k+1, Nat.lt_succ_of_le hkSucc⟩)) := by
          ext s; simp [Bourbaki.TopologyB.Path.subpath, hidx, hi_succ]

        have hmap_trans₂ :
          ((CoveringMap.coverConcatCore (p:=p) γ cov ⟨k, Nat.lt_succ_of_le hk'⟩).trans
              (Bourbaki.TopologyB.Path.subpath γ (cov.pts i.castSucc) (cov.pts i.succ))) u
            =
          ((CoveringMap.coverConcatCore (p:=p) γ cov ⟨k, Nat.lt_succ_of_le hk'⟩).trans
              (Bourbaki.TopologyB.Path.subpath γ
                (cov.pts ⟨k, Nat.lt_succ_of_le hk'⟩)
                (cov.pts ⟨k+1, Nat.lt_succ_of_le hkSucc⟩))) u := by
          simpa [hsub]

        -- (5) succ へ畳む（`coverConcatCore` の定義を展開）
        have hcore_succ :
          ((CoveringMap.coverConcatCore (p:=p) γ cov ⟨k, Nat.lt_succ_of_le hk'⟩).trans
              (Bourbaki.TopologyB.Path.subpath γ
                (cov.pts ⟨k, Nat.lt_succ_of_le hk'⟩)
                (cov.pts ⟨k+1, Nat.lt_succ_of_le hkSucc⟩))) u
            =
          (CoveringMap.coverConcatCore (p:=p) γ cov
            ⟨Nat.succ k, Nat.lt_succ_of_le hkSucc⟩) u := by
          simp [CoveringMap.coverConcatCore, Bourbaki.TopologyB.Path.subpath]

        exact hmap_trans₁.trans (hmap_trans₂.trans hcore_succ)

      · -- endpoint invariant at k+1
        -- 右辺の添字を `⟨k+1, _⟩` に揃えて流すだけ
        have hi_succ :
          (i.succ : Fin (cov.n+1)) = ⟨k+1, Nat.lt_succ_of_le hkSucc⟩ := by
          ext; rfl
        change p (Γseg Bourbaki.TopologyB.I1) = γ (cov.pts ⟨k+1, Nat.lt_succ_of_le hkSucc⟩)
        simpa [hi_succ] using hend_k1

  ----------------------------------------------------------------
  -- k = n のデータを取り出して `coverConcat` に貼り替える
  ----------------------------------------------------------------
  set R := build cov.n le_rfl with hR

  -- (1) R の構成物の像 ＝ core(n) の像
  have hval :
      ((R.val.2).map (f := p) h.continuous) t
        = (CoveringMap.coverConcatCore (p:=p) γ cov
            ⟨cov.n, by simpa using Nat.lt_succ_self _⟩) t :=
    (R.property).1 t

  -- (2) 左辺の lift を R のデータに一致させる（定義を一回だけ展開）
  have hLHS :
    ((CoveringMap.liftPathOnCover (p:=p) h γ cov e₀ h₀).2.map (f := p) h.continuous) t
      = ((R.val.2).map (f := p) h.continuous) t := sorry

  -- (3) coverConcat を core(n) の評価に貼り替える
  have hCC :
      (CoveringMap.coverConcat (p:=p) γ cov) t
        = (CoveringMap.coverConcatCore (p:=p) γ cov
            ⟨cov.n, by simpa using Nat.lt_succ_self _⟩) t := by
    simp [CoveringMap.coverConcat]

  -- (4) 連鎖（`assumption` は不要）
  exact (hLHS.trans hval).trans hCC.symm


  -- ゴールが `p (… t)` 形式に展開されてしまっている環境ではこちらを使う：
  -- simpa [Bourbaki.TopologyB.path_map_apply, CoveringMap.liftPathOnCover, hR] using hLHS


  -- We avoid a path-level equality since endpoints differ; the apply-level β
  -- lemma suffices and gives endpoint corollaries below.

  /-- Endpoint corollary at `I0` for the mapped global lift. -/
  lemma liftPathOnCover_map_I0
      (h : CoveringMap p) {b₀ b₁ : B}
      (γ : Path b₀ b₁)
      (cov : PathCover (p:=p) γ)
      (e₀ : E) (h₀ : p e₀ = b₀) :
      ((liftPathOnCover (p:=p) h γ cov e₀ h₀).2.map (f := p) h.continuous) I0
        = γ I0 :=
  by
    have H0 := liftPathOnCover_map_apply (p:=p) h γ cov e₀ h₀ I0
    have hcov0 := coverConcat_I0 (p:=p) (γ:=γ) (cov:=cov)
    have hγ0 : γ I0 = b₀ := Bourbaki.TopologyB.path_source_I0 (γ:=γ)
    -- chain equalities
    calc
      _ = (coverConcat (p:=p) γ cov) I0 := H0
      _ = b₀ := hcov0
      _ = γ I0 := hγ0.symm

  /-- Endpoint corollary at `I1` for the mapped global lift. -/
  lemma liftPathOnCover_map_I1
      (h : CoveringMap p) {b₀ b₁ : B}
      (γ : Path b₀ b₁)
      (cov : PathCover (p:=p) γ)
      (e₀ : E) (h₀ : p e₀ = b₀) :
      ((liftPathOnCover (p:=p) h γ cov e₀ h₀).2.map (f := p) h.continuous) I1
        = γ I1 :=
  by
    have H1 := liftPathOnCover_map_apply (p:=p) h γ cov e₀ h₀ I1
    have hcov1 := coverConcat_I1 (p:=p) (γ:=γ) (cov:=cov)
    have hγ1 : γ I1 = b₁ := Bourbaki.TopologyB.path_target_I1 (γ:=γ)
    calc
      _ = (coverConcat (p:=p) γ cov) I1 := H1
      _ = b₁ := hcov1
      _ = γ I1 := hγ1.symm

  -- β-rule up to the natural reparametrization by the cover can be shown by
  -- folding over segments using `liftPathLocalOn_map` and pushing `Path.map`
  -- through concatenation. Omitted here to keep the skeleton light.

  /-!
  Local uniqueness, sheet version: evaluate `liftPathLocalOn` under `e`, and
  a uniqueness-on-a-fixed-sheet principle for any other local lift over the
  same chart. These avoid connectedness arguments by assuming the sheet index
  is fixed along the segment.
  -/

  /-- e-level β for the localized lift on `[a,b]`. -/
  lemma liftPathLocalOn_e_apply
      (h : CoveringMap p) {b₀ b₁ : B}
      (γ : Path b₀ b₁)
      (a b : unitInterval)
      (d : EvenlyCoveredAt p (γ a))
      (eₐ : E) (hₐ : p eₐ = γ a)
      (hγU : ∀ t : unitInterval, γ (Bourbaki.TopologyB.Path.segMap a b t) ∈ d.U)
      (t : unitInterval) :
      let i : d.I := d.sheetIndexAt eₐ (by
        have : γ a ∈ d.U := by simpa using hγU I0
        simpa [hₐ] using this)
      d.e ⟨(liftPathLocalOn (p:=p) h γ a b d eₐ hₐ hγU) t,
            by
              -- membership in `p ⁻¹' U` via the apply-level β
              have hβ := liftPathLocalOn_map_apply (p:=p) h γ a b d eₐ hₐ hγU t
              have hx : p ((liftPathLocalOn (p:=p) h γ a b d eₐ hₐ hγU) t)
                        = γ (Bourbaki.TopologyB.Path.segMap a b t) := by
                simpa [path_map_apply] using hβ
              have : γ (Bourbaki.TopologyB.Path.segMap a b t) ∈ d.U := hγU t
              simpa [hx]
        ⟩
        = (⟨γ (Bourbaki.TopologyB.Path.segMap a b t), hγU t⟩, i) :=
  by
    classical
    letI : TopologicalSpace d.I := d.instTopI
    intro i
    -- Unfold the underlying `liftAlong` and apply the e-level β for `liftAlong`.
    -- Build the `ContinuousMap` on the segment.
    have hUa : γ a ∈ d.U := by simpa using hγU I0
    have hi : i = d.sheetIndexAt eₐ (by simpa [hₐ] using hUa) := rfl
    -- the continuous base map on the subinterval
    let γB : ContinuousMap unitInterval B :=
      γ.toContinuousMap.comp (Bourbaki.TopologyB.Path.segMap a b)
    have hγB : ∀ t, γB t ∈ d.U := by intro t; simpa [γB, ContinuousMap.comp_apply] using hγU t
    -- apply `EvenlyCoveredAt.liftAlong_e_apply` pointwise
    -- identify the underlying continuous map in `liftPathLocalOn`.
    have : d.e ⟨(d.liftAlong (p:=p) h i γB hγB) t,
                  by
                    -- membership via sheet β at `s := (toSubtype γB hγB) t`.
                    classical
                    let s := (d.toSubtype γB hγB) t
                    have hβp := EvenlyCoveredAt.sheet_comp_eq_inclB (p:=p) (h:=h) (d:=d) (i:=i)
                    have hpeq : p (((d.inclE).comp (d.sheetMap i)) s) = s.1 := by
                      simpa [ContinuousMap.comp_apply, EvenlyCoveredAt.inclB]
                        using congrArg (fun F => F s) hβp
                    have hxEq : (p (d.inclE ((d.sheetMap i) s)) ∈ d.U) = (s.1 ∈ d.U) := by
                      simpa [ContinuousMap.comp_apply] using congrArg (fun x => x ∈ d.U) hpeq
                    -- rewrite the goal via `liftAlong` def and close by `s.2`.
                    simpa [EvenlyCoveredAt.liftAlong, EvenlyCoveredAt.toSubtype,
                           ContinuousMap.comp_apply]
                      using Eq.mp (hxEq.symm) s.2
              ⟩
            = (⟨γB t, hγB t⟩, i) :=
      d.liftAlong_e_apply (p:=p) (h:=h) (i:=i) (γ:=γB) (hγ:=hγB) t
    -- reconcile `γB` and `subpath` data, and unfold `liftPathLocalOn`.
    simpa [γB, liftPathLocalOn, EvenlyCoveredAt.liftAlong,
           ContinuousMap.comp_apply] using this

  /-- Uniqueness in a fixed sheet for the localized lift on `[a,b]`:
  if another path `Γ` lifts the same base subpath and its chart index is
  constantly the starting `i`, then `Γ = liftPathLocalOn …`. -/
  lemma liftPathLocalOn_unique_in_sheet
      (h : CoveringMap p) {b₀ b₁ : B}
      (γ : Path b₀ b₁)
      (a b : unitInterval)
      (d : EvenlyCoveredAt p (γ a))
      (eₐ : E) (hₐ : p eₐ = γ a)
      (hγU : ∀ t : unitInterval, γ (Bourbaki.TopologyB.Path.segMap a b t) ∈ d.U)
      (Γ : Path eₐ ((liftPathLocalOn (p:=p) h γ a b d eₐ hₐ hγU) I1))
      (hβ : ∀ t, ((Γ.map (f := p) h.continuous) t)
                  = (Bourbaki.TopologyB.Path.subpath γ a b) t)
      (hsheet : ∀ t, let i0 := d.sheetIndexAt eₐ (by
                        have : γ a ∈ d.U := by simpa using hγU I0
                        simpa [hₐ] using this)
                  (d.e ⟨Γ t, by
                    -- membership via `hβ` and `hγU`
                    have hb := hβ t
                    have hx : p (Γ t)
                              = γ (Bourbaki.TopologyB.Path.segMap a b t) := by
                      simpa [path_map_apply] using hb
                    have : γ (Bourbaki.TopologyB.Path.segMap a b t) ∈ d.U := hγU t
                    simpa [hx]
                  ⟩).2 = i0) :
      Γ = liftPathLocalOn (p:=p) h γ a b d eₐ hₐ hγU :=
  by
    classical
    letI : TopologicalSpace d.I := d.instTopI
    -- Work at the `ContinuousMap` level, then upgrade to paths via ext.
    -- Underlying base map on the segment
    let γB : ContinuousMap unitInterval B :=
      γ.toContinuousMap.comp (Bourbaki.TopologyB.Path.segMap a b)
    have hγB : ∀ t, γB t ∈ d.U := by intro t; simpa [γB, ContinuousMap.comp_apply] using hγU t
    -- Pointwise β → bundled equality of continuous maps
    have hβcm : ((⟨p, h.continuous⟩ : ContinuousMap E B)).comp Γ.toContinuousMap = γB := by
      ext t; simpa [γB, path_map_apply, ContinuousMap.comp_apply] using hβ t
    -- Starting sheet index
    have hUa : γ a ∈ d.U := by simpa using hγU I0
    set i0 : d.I := d.sheetIndexAt eₐ (by simpa [hₐ] using hUa) with hi0
    -- Apply uniqueness-on-a-fixed-sheet for `ContinuousMap`s
    have huniq := EvenlyCoveredAt.liftAlong_unique_in_sheet (p:=p) (d:=d) (h:=h)
      (i:=i0) (γ:=γB) (hγ:=hγB) (δ:=Γ.toContinuousMap) (hβ:=hβcm)
      (hsheet:=by intro t; simpa [γB, ContinuousMap.comp_apply, hi0, path_map_apply]
        using hsheet t)
    -- Unpack to paths
    -- The RHS `liftAlong` is exactly the underlying map of `liftPathLocalOn`.
    ext t; simpa [liftPathLocalOn, EvenlyCoveredAt.liftAlong]
      using congrArg (fun F => F t) huniq

  /- β-rule for `liftPathOnCover`: composing with `p` recovers `γ`.
     Proof outline: fold over segments; each segment satisfies the β-rule by
     `liftPathLocalOn_map`, and `Path.map` respects concatenation.
     β-ruleと一意性の補題は、`PathCover` の抽出補題が整ったら追加できる。
     証明自体は `ext; simp` と `map_trans_path` から機械的に出る。 -/
  -- β-rule and uniqueness lemmas for `liftPathOnCover` can be added later.

  end CoveringMap


  /- NOTE (temporary): Extraction `CoveringMap.evenlyCoveredAt` is deferred
     to keep Phase 0–2 build stable while we reintroduce local data. -/
  -- noncomputable def CoveringMap.evenlyCoveredAt
  --     {p : E → B} (h : CoveringMap p) (b : B) :
  --     EvenlyCoveredAt p b := by
  --   classical
  --   -- Stage 1: pick U and its properties
  --   let hexU := h.evenlyCovered b
  --   let U : Set B := Classical.choose hexU
  --   have hU : IsOpen U ∧ b ∈ U ∧
  --       ∃ (I : Type*) (_ : TopologicalSpace I) (_ : DiscreteTopology I),
  --         ∃ e : (Subtype fun e : E => p e ∈ U)
  --               ≃ₜ ((Subtype fun x : B => x ∈ U) × I),
  --           (∀ s, ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1) :=
  --     Classical.choose_spec hexU
  --   -- Stage 2: pick I and the rest for this I via nested `choose`
  --   let I : Type* := Classical.choose hU.2.2
  --   have hI : ∃ (_ : TopologicalSpace I) (_ : DiscreteTopology I),
  --         ∃ e : (Subtype fun e : E => p e ∈ U)
  --               ≃ₜ ((Subtype fun x : B => x ∈ U) × I),
  --           (∀ s, ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1) :=
  --     Classical.choose_spec hU.2.2
  --   -- Stage 3: pick topology and discrete structure
  --   let tI : TopologicalSpace I := Classical.choose hI
  --   have hID : ∃ (_ : DiscreteTopology I),
  --         ∃ e : (Subtype fun e : E => p e ∈ U)
  --               ≃ₜ ((Subtype fun x : B => x ∈ U) × I),
  --           (∀ s, ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1) :=
  --     Classical.choose_spec hI
  --   let dI : DiscreteTopology I := Classical.choose hID
  --   have hIE : ∃ e : (Subtype fun e : E => p e ∈ U)
  --               ≃ₜ ((Subtype fun x : B => x ∈ U) × I),
  --           (∀ s, ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1) :=
  --     Classical.choose_spec hID
  --   -- Stage 4: pick the homeomorphism and base compatibility
  --   let e : (Subtype fun e : E => p e ∈ U)
  --           ≃ₜ ((Subtype fun x : B => x ∈ U) × I) := Classical.choose hIE
  --   have hbase : ∀ s, ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1 :=
  --     Classical.choose_spec hIE
  --   -- Assemble
  --   exact
  --     { U := U
  --     , isOpenU := hU.1
  --     , memU := hU.2.1
  --     , I := I
  --     , instTopI := tI
  --     , instDiscI := dI
  --     , e := e
  --     , base := fun s => hbase s }

  -- (apply-level β for `liftPathOnCover` can be added here later, once the
  -- fold identity is finalized. We keep Phase 6 minimal and green.)

/-
Skeleton of the path-lifting statement: given a covering map, paths in the base
lift uniquely once an initial point in the fiber is fixed. The precise
implementation can follow mathlib’s path/interval conventions.
-/
  theorem path_lifting_theorem_skeleton (p : E → B) (_h : CoveringMap p) : True :=
    True.intro


end CoveringSpaces

/-
## C. Stone–Čech compactification — universal property skeleton

We encode βX together with the canonical map `ι : ContinuousMap X βX` and the universal
property for maps into compact Hausdorff spaces. This mirrors the md design,
yet leaves heavy analysis to future dedicated development.
-/

section StoneCechSkeleton

variable (X : Type*) [TopologicalSpace X]

structure StoneCechCompactification (X : Type*) [TopologicalSpace X] where
  βX : Type*
  instTopβX : TopologicalSpace βX
  instCompβX : CompactSpace βX
  instT2βX : T2Space βX
  ι : ContinuousMap X βX
  dense_range : DenseRange ι
  universal :
    ∀ (K : Type*) (_ : TopologicalSpace K) (_ : CompactSpace K) (_ : T2Space K),
      ∀ f : ContinuousMap X K, ∃! F : ContinuousMap βX K, F.comp ι = f

-- Provide typeclass instances for the carrier `βX` stored inside a compactification.
instance instTopologicalSpace_beta (S : StoneCechCompactification X) :
    TopologicalSpace S.βX := S.instTopβX

instance instCompactSpace_beta (S : StoneCechCompactification X) :
    CompactSpace S.βX := S.instCompβX

instance instT2Space_beta (S : StoneCechCompactification X) :
    T2Space S.βX := S.instT2βX

/-
Convenience API: abstract lifting and its `simp`-friendly consequences from the
universal property. This works for any `StoneCechCompactification X` instance,
including the trivial one below or a mathlib-backed one.
-/

noncomputable def StoneCechCompactification.lift
    {X : Type*} [TopologicalSpace X]
    (S : StoneCechCompactification X)
    (K : Type*) [TopologicalSpace K] [CompactSpace K] [T2Space K]
    (f : ContinuousMap X K) : ContinuousMap S.βX K :=
  Classical.choose (S.universal K (inferInstance) (inferInstance) (inferInstance) f)

@[simp] lemma StoneCechCompactification.lift_comp
    {X : Type*} [TopologicalSpace X]
    (S : StoneCechCompactification X)
    (K : Type*) [TopologicalSpace K] [CompactSpace K] [T2Space K]
    (f : ContinuousMap X K) :
    (S.lift K f).comp S.ι = f := by
  classical
  simpa [StoneCechCompactification.lift]
    using (Classical.choose_spec (S.universal K (inferInstance) (inferInstance) (inferInstance) f)).1

@[simp] lemma StoneCechCompactification.lift_comp_apply
    {X : Type*} [TopologicalSpace X]
    (S : StoneCechCompactification X)
    (K : Type*) [TopologicalSpace K] [CompactSpace K] [T2Space K]
    (f : ContinuousMap X K) (x : X) :
    ((S.lift K f).comp S.ι) x = f x := by
  classical
  have := S.lift_comp (K:=K) f
  exact congrArg (fun (h : ContinuousMap X K) => h x) this

lemma StoneCechCompactification.lift_unique
    {X : Type*} [TopologicalSpace X]
    (S : StoneCechCompactification X)
    (K : Type*) [TopologicalSpace K] [CompactSpace K] [T2Space K]
    (f : ContinuousMap X K) {G : ContinuousMap S.βX K}
    (hG : G.comp S.ι = f) :
    G = S.lift K f := by
  classical
  have huniq :=
    (Classical.choose_spec (S.universal K (inferInstance) (inferInstance) (inferInstance) f)).2
  -- huniq : ∀ y, (y.comp S.ι = f) → y = Classical.choose (...)
  have : G = Classical.choose (S.universal K (inferInstance) (inferInstance) (inferInstance) f) :=
    huniq G hG
  simpa [StoneCechCompactification.lift] using this

/-
Trivial compactification: when `X` is already compact Hausdorff, we can take
βX = X and ι = id. This satisfies the universal property with `F = f`.
This gives a working instance without importing mathlib’s `StoneCech`.
-/

noncomputable def StoneCechCompactification.trivial
    (X : Type*) [TopologicalSpace X]
    [CompactSpace X] [T2Space X] : StoneCechCompactification X :=
{ βX := X
, instTopβX := inferInstance
, instCompβX := inferInstance
, instT2βX := inferInstance
, ι := ContinuousMap.id X
, dense_range := by
    -- range(id) = univ is dense
    classical
    simpa using (denseRange_id : DenseRange (fun x : X => x))
, universal := by
    intro K _ _ _ f
    refine ⟨f, ?comp, ?uniq⟩
    · -- F ∘ ι = f with F = f and ι = id
      ext x; rfl
    · -- uniqueness: if G ∘ id = f then G = f
      intro G hG
      ext x
      -- evaluate both sides; `hG` gives function extensionality pointwise
      -- since `ι = id`, we have `G x = (G.comp (ContinuousMap.id X)) x`
      have := congrArg (fun (h : ContinuousMap X K) => h x) hG
      simpa using this
}

end StoneCechSkeleton

/-
## C'. Stone–Čech from mathlib (integration)

This realizes the abstract `StoneCechCompactification` by mathlib’s `StoneCech`:
βX := `StoneCech X`, ι := the canonical unit embedding, and the universal arrow
provided by `StoneCech.extend`. The uniqueness is discharged by density of ι
and T₂ on the codomain.
-/

section StoneCechFromMathlib

variable (X : Type*) [TopologicalSpace X]

noncomputable def StoneCechCompactification.fromMathlib :
    StoneCechCompactification X :=
{ βX := StoneCech X
, instTopβX := inferInstance
, instCompβX := inferInstance
, instT2βX := inferInstance
, ι := ⟨stoneCechUnit, continuous_stoneCechUnit⟩
, dense_range := by
    simpa using (denseRange_stoneCechUnit : DenseRange (stoneCechUnit : X → StoneCech X))
, universal := by
    intro K _ _ _ f
    classical
    -- Existence: use the canonical continuous extension from mathlib
    let F : ContinuousMap (StoneCech X) K :=
      ⟨stoneCechExtend (α := X) (β := K) (g := fun x => f x) f.continuous,
        continuous_stoneCechExtend (α := X) (β := K) (g := fun x => f x) f.continuous⟩
    refine ⟨F, ?comp, ?uniq⟩
    · -- β-rule: extension comp unit = original
      -- Prove pointwise using `simp` with the extension lemma.
      ext x
      -- Goal: F (stoneCechUnit x) = f x
      -- `simp [F]` unfolds `F` to `stoneCechExtend …`, and then
      -- `stoneCechExtend_extends` reduces it to `f x`.
      simp [F]
    · -- Uniqueness via `stoneCech_hom_ext`
      intro G hG
      have h₁ : Continuous (G : StoneCech X → K) := G.continuous
      have h₂ : Continuous (F : StoneCech X → K) := F.continuous
      -- both sides agree after precomposition with the unit map
      -- Start with equality of bundled maps after composing with `ι`:
      have hFcomp : F.comp ⟨stoneCechUnit, continuous_stoneCechUnit⟩ = f := by
        -- Same pointwise argument, now for `F`.
        ext x; simp [F]
      have hEq : G.comp ⟨stoneCechUnit, continuous_stoneCechUnit⟩
                = F.comp ⟨stoneCechUnit, continuous_stoneCechUnit⟩ := by
        simpa [hFcomp] using hG
      -- Now get pointwise equality on the dense image of `stoneCechUnit`:
      have hcomp : (G ∘ stoneCechUnit) = (F ∘ stoneCechUnit) := by
        ext x; simpa [Function.comp] using
          congrArg (fun (h : ContinuousMap X K) => h x) hEq
      -- Uniqueness of continuous extensions from dense subsets in T₂ spaces:
      -- `stoneCech_hom_ext` yields equality as functions, so we ext to upgrade to `ContinuousMap`.
      have hfun : (fun y => G y) = (fun y => F y) :=
        stoneCech_hom_ext (α := X) (β := K) h₁ h₂ hcomp
      ext y; simpa using congrArg (fun h => h y) hfun
}

end StoneCechFromMathlib

section StoneCechSmoke

variable (X : Type*) [TopologicalSpace X]

-- A tiny smoke test: the β-rule for `lift` reduces by `simp`/`ext`.
example {K : Type*} [TopologicalSpace K] [CompactSpace K] [T2Space K]
    (f : ContinuousMap X K) (x : X) :
  ((StoneCechCompactification.fromMathlib (X:=X)).lift K f).comp
      (StoneCechCompactification.fromMathlib (X:=X)).ι x = f x := by
  exact
    (StoneCechCompactification.lift_comp_apply
      (S := StoneCechCompactification.fromMathlib (X:=X)) (K:=K) f x)

end StoneCechSmoke

end Bourbaki.TopologyB
