/-
  Topology B — Bourbaki-style structuration via ordered pairs and morphisms

  This file is derived from:
    src/MyProjects/Topology/B/claude_topologyB_en.md

  Guiding spirit (Bourbaki):
  - Structure built from sets of ordered pairs (products) and morphisms (projections)
  - Universal properties expressed via factorization through projections
  - Emphasis on diagrammatic uniqueness (existence/uniqueness of mediating maps)

  Contents
  A. Product universality and exponential direction (skeleton)
  B. Covering maps (Bourbaki-flavored definition skeleton) and path lifting (statement stub)
  C. Stone–Čech compactification (universal property skeleton)

  Notes
  - Section A provides concrete lemmas fully in terms of projections and ordered pairs.
  - Sections B and C lay out faithful skeletons of the intended structures and universal properties
    so they can be refined without changing interfaces.
-/

import Mathlib.Topology.Basic
import Mathlib.Topology.Constructions.SumProd
import Mathlib.Topology.ContinuousMap.Basic
import Mathlib.Topology.Instances.Real

namespace Bourbaki.TopologyB

/-! 
## A. Product universality via projections

We formalize the spirit “product = structure generated by projections”:
- continuity of projections `π₁, π₂`;
- continuity criterion for a map into a product via its components;
- existence and uniqueness of the mediating map `⟨f, g⟩`.
!/ -/

section ProductUniversality

variable {T X Y : Type*}
variable [TopologicalSpace T] [TopologicalSpace X] [TopologicalSpace Y]

-- Projections (morphisms) from the ordered pair structure X × Y.
def π₁ : X × Y → X := fun p => p.1
def π₂ : X × Y → Y := fun p => p.2

lemma continuous_π₁ : Continuous (π₁ : X × Y → X) := by
  simpa [π₁] using continuous_fst

lemma continuous_π₂ : Continuous (π₂ : X × Y → Y) := by
  simpa [π₂] using continuous_snd

/-
Continuity into a product is equivalent to continuity of the two components
obtained by composing with the projections. This is the universal property
in Bourbaki’s language: the product topology is the coarsest making π₁, π₂
continuous, and continuity is tested componentwise.
-/
theorem continuous_iff_proj (h : T → X × Y) :
    Continuous h ↔
      Continuous (fun t => (h t).1) ∧ Continuous (fun t => (h t).2) := by
  constructor
  · intro hh
    exact ⟨continuous_fst.comp hh, continuous_snd.comp hh⟩
  · rintro ⟨h₁, h₂⟩
    -- Use `Continuous.prodMk` on the components to build continuity of `h`.
    -- We rewrite `h` as `fun t => ((h t).1, (h t).2)` to `simpa`.
    have : Continuous (fun t => ((h t).1, (h t).2)) := h₁.prodMk h₂
    simpa using this

/-
Existence and uniqueness of the mediating map into a product.
Given continuous `f : T → X` and `g : T → Y`, there is a unique continuous
`h : T → X × Y` such that `π₁ ∘ h = f` and `π₂ ∘ h = g`.
-/
theorem exists_unique_lift_to_prod {f : T → X} {g : T → Y}
    (hf : Continuous f) (hg : Continuous g) :
    ∃! h : T → X × Y,
      Continuous h ∧ (∀ t, (h t).1 = f t) ∧ (∀ t, (h t).2 = g t) := by
  refine ⟨(fun t => (f t, g t)), ?exist, ?uniq⟩
  · -- existence: the canonical pairing is continuous and has the desired components
    refine And.intro ?hcont (And.intro ?hfst ?hsnd)
    · simpa using hf.prodMk hg
    · intro t; rfl
    · intro t; rfl
  · -- uniqueness: any other h with the same components must be pointwise equal
    intro h hh
    rcases hh with ⟨hc, hfst, hsnd⟩
    apply funext
    intro t
    -- Compare components, then use `Prod.ext`.
    -- Expand `h t` into components to apply `Prod.ext` directly.
    cases h t with
    | _ hx hy =>
      -- `hfst t : (hx, hy).1 = f t` and `hsnd t : (hx, hy).2 = g t`.
      exact Prod.ext (by simpa [hfst t]) (by simpa [hsnd t])

/-
As a quick corollary, pairing with projections recovers the map.
This is the β-rule for the universal property.
-/
lemma fst_pair_eq (f : T → X) (g : T → Y) (t : T) : ((f t, g t).1) = f t := rfl
lemma snd_pair_eq (f : T → X) (g : T → Y) (t : T) : ((f t, g t).2) = g t := rfl

end ProductUniversality

/-!
## A'. Exponential direction (skeleton)

We record currying/uncurrying at the level of plain functions (ordered pairs →
functions into function spaces) and reserve continuity/topological refinements
for future development (e.g. under `[LocallyCompactSpace]` hypotheses). This
keeps the Bourbaki pairing perspective explicit and light.
!/ -/

section ExponentialSkeleton

variable {X Y Z : Type*}

/-- Currying: functions on a product are functions returning functions. -/
def curry (f : X × Y → Z) : X → Y → Z :=
  fun x y => f (x, y)

/-- Uncurrying: functions returning functions are functions on a product. -/
def uncurry (g : X → Y → Z) : X × Y → Z :=
  fun p => g p.1 p.2

@[simp] lemma curry_uncurry (g : X → Y → Z) : curry (uncurry g) = g := rfl
@[simp] lemma uncurry_curry (f : X × Y → Z) : uncurry (curry f) = f := by
  funext p; cases p; rfl

end ExponentialSkeleton

/-!
## B. Covering spaces — Bourbaki-style skeleton

We package the essence of an evenly covered neighborhood in terms of a local
homeomorphism to a product `U × I` with discrete fiber `I`. This keeps the
ordered-pair-and-projection viewpoint explicit. The definition below is a
faithful skeleton: it captures the shape and the key data while staying light.
!/ -/

section CoveringSpaces

open scoped Topology

variable {E B : Type*}
variable [TopologicalSpace E] [TopologicalSpace B]

/-
`CoveringMap p` asserts that around every base point `b : B`, the preimage of a
small neighborhood `U` decomposes as a product `U × I` for a discrete index
set `I`. We keep the commuting condition with the projection implicit in this
first skeleton, focusing on the core decomposition datum.
-/
structure CoveringMap (p : E → B) : Prop where
  continuous : Continuous p
  evenlyCovered :
    ∀ b : B,
      ∃ (U : Set B), IsOpen U ∧ b ∈ U ∧
        ∃ (I : Type*) (_ : TopologicalSpace I) (_ : DiscreteTopology I),
        ∃ e : (Subtype fun e : E => p e ∈ U) ≃ₜ ((Subtype fun x : B => x ∈ U) × I),
          True

/-
Skeleton of the path-lifting statement: given a covering map, paths in the base
lift uniquely once an initial point in the fiber is fixed. The precise
implementation can follow mathlib’s path/interval conventions.
-/
theorem path_lifting_theorem_skeleton (p : E → B) (h : CoveringMap p) : True :=
  True.intro

end CoveringSpaces

/-!
## C. Stone–Čech compactification — universal property skeleton

We encode βX together with the canonical map `ι : C(X, βX)` and the universal
property for maps into compact Hausdorff spaces. This mirrors the md design,
yet leaves heavy analysis to future dedicated development.
!/ -/

section StoneCechSkeleton

variable (X : Type*) [TopologicalSpace X]

structure StoneCechCompactification where
  βX : Type*
  instTopβX : TopologicalSpace βX
  instCompβX : CompactSpace βX
  instT2βX : T2Space βX
  ι : C (X) βX
  dense_range : DenseRange ι
  universal :
    ∀ (K : Type*) (_ : TopologicalSpace K) (_ : CompactSpace K) (_ : T2Space K),
      ∀ f : C X K, ∃! F : C βX K, F.comp ι = f

end StoneCechSkeleton

end Bourbaki.TopologyB
