/-
  Topology B — Bourbaki-style structuration via ordered pairs and morphisms

  This file is derived from:
    src/MyProjects/Topology/B/claude_topologyB_en.md

  Guiding spirit (Bourbaki):
  - Structure built from sets of ordered pairs (products) and morphisms (projections)
  - Universal properties expressed via factorization through projections
  - Emphasis on diagrammatic uniqueness (existence/uniqueness of mediating maps)

  Contents
  A. Product universality and exponential direction (skeleton)
  B. Covering maps (Bourbaki-flavored definition skeleton) and path lifting (statement stub)
  C. Stone–Čech compactification (universal property skeleton)

  Notes
  - Section A provides concrete lemmas fully in terms of projections and ordered pairs.
  - Sections B and C lay out faithful skeletons of the intended structures and universal properties
    so they can be refined without changing interfaces.
-/

import Mathlib.Topology.Basic
import Mathlib.Topology.Constructions.SumProd
import Mathlib.Topology.ContinuousMap.Basic
import Mathlib.Topology.CompactOpen
import Mathlib.Topology.Path
import Mathlib.Topology.Instances.Real.Lemmas
import Mathlib.Topology.Category.TopCat.Basic
import Mathlib.Topology.Category.TopCat.Limits.Basic
import Mathlib.CategoryTheory.Adjunction.Basic
import Mathlib.Tactic
-- Stone–Čech (module name may vary slightly by mathlib version):
import Mathlib.Topology.Compactification.StoneCech

namespace Bourbaki.TopologyB

/-!
## A. Product universality via projections

We formalize the spirit “product = structure generated by projections”:
- continuity of projections `π₁, π₂`;
- continuity criterion for a map into a product via its components;
- existence and uniqueness of the mediating map `⟨f, g⟩`.
!/ -/

section ProductUniversality

variable {T X Y : Type*}
variable [TopologicalSpace T] [TopologicalSpace X] [TopologicalSpace Y]

-- Projections (morphisms) from the ordered pair structure X × Y.
def π₁ : X × Y → X := fun p => p.1
def π₂ : X × Y → Y := fun p => p.2

lemma continuous_π₁ : Continuous (π₁ : X × Y → X) := by
  simpa [π₁] using continuous_fst

lemma continuous_π₂ : Continuous (π₂ : X × Y → Y) := by
  simpa [π₂] using continuous_snd

/-
Continuity into a product is equivalent to continuity of the two components
obtained by composing with the projections. This is the universal property
in Bourbaki’s language: the product topology is the coarsest making π₁, π₂
continuous, and continuity is tested componentwise.
-/
theorem continuous_iff_proj (h : T → X × Y) :
    Continuous h ↔
      Continuous (fun t => (h t).1) ∧ Continuous (fun t => (h t).2) := by
  constructor
  · intro hh
    exact ⟨continuous_fst.comp hh, continuous_snd.comp hh⟩
  · rintro ⟨h₁, h₂⟩
    -- Use `Continuous.prodMk` on the components to build continuity of `h`.
    -- We rewrite `h` as `fun t => ((h t).1, (h t).2)` to `simpa`.
    have : Continuous (fun t => ((h t).1, (h t).2)) := h₁.prodMk h₂
    simpa using this

/-
Existence and uniqueness of the mediating map into a product.
Given continuous `f : T → X` and `g : T → Y`, there is a unique continuous
`h : T → X × Y` such that `π₁ ∘ h = f` and `π₂ ∘ h = g`.
-/
theorem exists_unique_lift_to_prod {f : T → X} {g : T → Y}
    (hf : Continuous f) (hg : Continuous g) :
    ∃! h : T → X × Y,
      Continuous h ∧ (∀ t, (h t).1 = f t) ∧ (∀ t, (h t).2 = g t) := by
  refine ⟨(fun t => (f t, g t)), ?exist, ?uniq⟩
  · -- existence: the canonical pairing is continuous and has the desired components
    refine And.intro ?hcont (And.intro ?hfst ?hsnd)
    · simpa using hf.prodMk hg
    · intro t; rfl
    · intro t; rfl
  · -- uniqueness: any other h with the same components must be pointwise equal
    intro h hh
    rcases hh with ⟨_hc, hfst, hsnd⟩
    apply funext
    intro t
    -- Compare components, then use `Prod.ext`.
    apply Prod.ext
    · simpa using hfst t
    · simpa using hsnd t

/-
As a quick corollary, pairing with projections recovers the map.
This is the β-rule for the universal property.
-/
lemma fst_pair_eq (f : T → X) (g : T → Y) (t : T) : ((f t, g t).1) = f t := rfl
lemma snd_pair_eq (f : T → X) (g : T → Y) (t : T) : ((f t, g t).2) = g t := rfl

end ProductUniversality

/-!
## A. (Category level) Diagonal ⊣ Product in `TopCat`

We implement the diagonal functor Δ : TopCat ⥤ TopCat × TopCat and the
product functor × : TopCat × TopCat ⥤ TopCat, and exhibit the adjunction
Hom(ΔX, (Y, Z)) ≃ Hom(X, Y × Z). The hom-sets reduce to pairs of continuous
maps versus a single continuous map into the product, matching the Bourbaki
ordered-pair perspective.
!/ -/

section TopCatAdjunction

open CategoryTheory

/- Δ: duplicate objects and morphisms. -/
def deltaTop : TopCat ⥤ TopCat × TopCat where
  obj X := ⟨X, X⟩
  map {X Y} (f : X ⟶ Y) := ⟨f, f⟩
  map_id X := by
    -- identities are componentwise
    ext <;> rfl
  map_comp {X Y Z} (f : X ⟶ Y) (g : Y ⟶ Z) := by
    -- composition is componentwise
    ext <;> rfl

/- ×: binary product on objects as cartesian product of spaces; on morphisms
it acts via `ContinuousMap.prodMap`.
-/
def prodTop : TopCat × TopCat ⥤ TopCat where
  obj X := TopCat.of (X.1 × X.2)
  map {X Y} (f : X ⟶ Y) :=
    (⟨(fun p : X.1 × X.2 => (f.1 p.1, f.2 p.2)), by
      -- continuity by components
      have h1 : Continuous fun p : X.1 × X.2 => f.1 p.1 := by
        simpa using (f.1.continuous.comp continuous_fst)
      have h2 : Continuous fun p : X.1 × X.2 => f.2 p.2 := by
        simpa using (f.2.continuous.comp continuous_snd)
      exact h1.prodMk h2⟩ : ContinuousMap (X.1 × X.2) (Y.1 × Y.2))
  map_id X := by
    -- identity acts componentwise
    ext p <;> rfl
  map_comp {X Y Z} (f : X ⟶ Y) (g : Y ⟶ Z) := by
    -- composition is componentwise
    ext p <;> rfl

/- The hom-set equivalence for the adjunction. -/
noncomputable def homEquivDeltaProd
    (X : TopCat) (YZ : TopCat × TopCat) :
    ((deltaTop.obj X) ⟶ YZ) ≃ (X ⟶ prodTop.obj YZ) :=
{ toFun :=
    fun fg =>
      (⟨(fun x => (fg.1 x, fg.2 x)), by
        simpa using (fg.1.continuous.prodMk fg.2.continuous)⟩ :
        ContinuousMap X (YZ.1 × YZ.2))
, invFun :=
    fun h =>
      ((⟨(fun x => (h x).1), by
          simpa using (continuous_fst.comp h.continuous)⟩ : ContinuousMap X YZ.1),
       (⟨(fun x => (h x).2), by
          simpa using (continuous_snd.comp h.continuous)⟩ : ContinuousMap X YZ.2))
, left_inv := by
    intro fg; ext x <;> rfl
, right_inv := by
    intro h; ext p <;> rfl }

/- The adjunction Δ ⊣ × specialized to `TopCat`. -/
-- (Optional) One can package `homEquivDeltaProd` into an adjunction using
-- `Adjunction.mkOfHomEquiv`. We keep the hom-set equivalence explicit here.

end TopCatAdjunction

/-!
## A'. Exponential direction (skeleton)

We record currying/uncurrying at the level of plain functions (ordered pairs →
functions into function spaces) and reserve continuity/topological refinements
for future development (e.g. under `[LocallyCompactSpace]` hypotheses). This
keeps the Bourbaki pairing perspective explicit and light.
!/ -/

section ExponentialSkeleton

variable {X Y Z : Type*}

/-- Currying: functions on a product are functions returning functions. -/
def curry (f : X × Y → Z) : X → Y → Z :=
  fun x y => f (x, y)

/-- Uncurrying: functions returning functions are functions on a product. -/
def uncurry (g : X → Y → Z) : X × Y → Z :=
  fun p => g p.1 p.2

@[simp] lemma curry_uncurry (g : X → Y → Z) : curry (uncurry g) = g := rfl
@[simp] lemma uncurry_curry (f : X × Y → Z) : uncurry (curry f) = f := by
  funext p; cases p; rfl

end ExponentialSkeleton

section ExponentialLaw

open ContinuousMap

variable {X Y Z : Type*}
variable [TopologicalSpace X] [TopologicalSpace Y] [TopologicalSpace Z]

/-- Exponential law: `ContinuousMap (X × Y) Z ≃ₜ ContinuousMap X (ContinuousMap Y Z)` under local compactness. -/
noncomputable def exponential_homeo
    [LocallyCompactSpace X] [LocallyCompactSpace Y] :
    ContinuousMap (X × Y) Z ≃ₜ ContinuousMap X (ContinuousMap Y Z) :=
  Homeomorph.curry (X:=X) (Y:=Y) (Z:=Z)

@[simp] lemma exponential_homeo_apply
    [LocallyCompactSpace X] [LocallyCompactSpace Y]
    (F : ContinuousMap (X × Y) Z) (x : X) (y : Y) :
    (exponential_homeo (X:=X) (Y:=Y) (Z:=Z) F x) y = F (x, y) := rfl

@[simp] lemma exponential_homeo_symm_apply
    [LocallyCompactSpace X] [LocallyCompactSpace Y]
    (G : ContinuousMap X (ContinuousMap Y Z)) (p : X × Y) :
    (exponential_homeo (X:=X) (Y:=Y) (Z:=Z)).symm G p = G p.1 p.2 := rfl

/-- Continuity of the evaluation map `(f, y) ↦ f y` under the compact-open topology. -/
theorem continuous_eval
    [LocallyCompactPair Y Z] :
    Continuous (fun p : ContinuousMap Y Z × Y => p.1 p.2) := by
  simpa using (ContinuousEval.continuous_eval :
    Continuous (fun p : ContinuousMap Y Z × Y => p.1 p.2))

end ExponentialLaw

/-!
## B. Covering spaces — Bourbaki-style skeleton

We package the essence of an evenly covered neighborhood in terms of a local
homeomorphism to a product `U × I` with discrete fiber `I`. This keeps the
ordered-pair-and-projection viewpoint explicit. The definition below is a
faithful skeleton: it captures the shape and the key data while staying light.
!/ -/

section CoveringSpaces

open scoped Topology

variable {E B : Type*}
variable [TopologicalSpace E] [TopologicalSpace B]

/-! Small helpers to stabilize endpoints and `simp` across mathlib versions. -/

@[inline] def I0 : unitInterval := ⟨0, by simp⟩
@[inline] def I1 : unitInterval := ⟨1, by simp⟩

@[simp] lemma coe_I0 : ((I0 : unitInterval) : ℝ) = 0 := rfl
@[simp] lemma coe_I1 : ((I1 : unitInterval) : ℝ) = 1 := rfl

/-! Normalized API for `Path.map`: pass a function and its continuity. -/
@[simp] lemma path_map_apply
  {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
  {x y : X} (γ : Path x y) (f : X → Y) (hf : Continuous f) (t : unitInterval) :
  (γ.map (f := f) hf) t = f (γ t) := rfl

/-
`CoveringMap p` asserts that around every base point `b : B`, the preimage of a
small neighborhood `U` decomposes as a product `U × I` for a discrete index
set `I`. We keep the commuting condition with the projection implicit in this
first skeleton, focusing on the core decomposition datum.
-/
  structure CoveringMap (p : E → B) : Prop where
    continuous : Continuous p
    evenlyCovered :
      ∀ b : B,
        ∃ (U : Set B), IsOpen U ∧ b ∈ U ∧
          ∃ (I : Type*) (_ : TopologicalSpace I) (_ : DiscreteTopology I),
          ∃ e : (Subtype fun e : E => p e ∈ U) ≃ₜ ((Subtype fun x : B => x ∈ U) × I),
            (∀ s, ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1)

  /-
  Evenly-covered data at a base point `b`. This packages the witness of
  `CoveringMap.evenlyCovered b` into a reusable record with convenient
  projections and helpers. We store the topology and discreteness on the fiber
  index `I` as fields (to be re-instantiated locally when needed).
  -/
  structure EvenlyCoveredAt (p : E → B) (b : B) where
    U : Set B
    isOpenU : IsOpen U
    memU : b ∈ U
    I : Type*
    instTopI : TopologicalSpace I
    instDiscI : @DiscreteTopology I instTopI
    e : (Subtype fun e : E => p e ∈ U)
        ≃ₜ ((Subtype fun x : B => x ∈ U) × I)
    base : ∀ s,
      ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1

  /-!
  Provide the stored topology/discrete topology on `d.I` as instances so that
  typeclass search always picks exactly the topology bundled in `d`.
  This avoids instance mismatch errors like "synthesized instance not
  definitionally equal" when working with products `({x // x ∈ d.U} × d.I)`.
  -/
  namespace EvenlyCoveredAt
  variable {p : E → B} {b : B}

  instance instTopologicalSpace_I (d : EvenlyCoveredAt p b) :
      TopologicalSpace d.I := d.instTopI

  instance instDiscreteTopology_I (d : EvenlyCoveredAt p b) :
      DiscreteTopology d.I := d.instDiscI

  end EvenlyCoveredAt


  namespace EvenlyCoveredAt

  variable {p : E → B} {b : B}

  /-- The sheet (local section) of index `i` over `U`. -/
  noncomputable def sheet (d : EvenlyCoveredAt p b)
      (i : d.I) : (Subtype fun x : B => x ∈ d.U)
        → (Subtype fun e : E => p e ∈ d.U) :=
    fun u => d.e.toEquiv.symm (u, i)

  /-- The sheet projects back to the base via `p` (β-rule at the base level). -/
  lemma sheet_base (d : EvenlyCoveredAt p b) (i : d.I)
      (u : Subtype fun x : B => x ∈ d.U) :
      p ((d.sheet i u).1) = u.1 := by
    classical
    -- Let `s := d.e.symm (u, i)`; then `d.e s = (u, i)` and the `base` property
    -- gives `((d.e s).1).1 = p s.1`. Rewriting yields the claim.
    set s := d.e.symm (u, i)
    have hs : d.e s = (u, i) := by
      subst s; simpa using (d.e.left_inv (u, i))
    have hb := d.base s
    -- hb : ((d.e s).1 : {x // x ∈ d.U}).1 = p s.1
    -- rewrite left using hs
    have : u.1 = p s.1 := by
      simpa [hs] using hb
    -- conclude, and rewrite s back to `d.sheet i u`
    simpa [s, EvenlyCoveredAt.sheet] using this.symm

  /-- Continuity of the `i`-th sheet as a map into `E` (forgetting the subtype). -/
  lemma continuous_sheet_val (d : EvenlyCoveredAt p b) (i : d.I) :
      Continuous (fun u : Subtype fun x : B => x ∈ d.U => ((d.sheet i u).1)) := by
    classical
    -- `u ↦ (u, i)` is continuous
    have hpair : Continuous fun u : Subtype fun x : B => x ∈ d.U => (u, i) := by
      have h1 : Continuous fun u : Subtype fun x : B => x ∈ d.U => u := continuous_id
      have h2 : Continuous fun _u : Subtype fun x : B => x ∈ d.U => i := continuous_const
      simpa using h1.prodMk h2
    -- `d.e.symm` is a homeomorphism, so its underlying function is continuous
    have hsymm : Continuous d.e.symm := d.e.continuous_symm
    -- Compose and project to `E` via `Subtype.val`
    have hcomp : Continuous (fun u : Subtype (fun x : B => x ∈ d.U) => d.e.symm (u, i)) :=
      hsymm.comp hpair
    simpa [EvenlyCoveredAt.sheet] using (continuous_subtype_val.comp hcomp)

  /-- The inclusion `U ↪ B` as a bundled continuous map. -/
  noncomputable def inclB (d : EvenlyCoveredAt p b) :
      ContinuousMap (Subtype fun x : B => x ∈ d.U) B :=
    ⟨(fun u => u.1), continuous_subtype_val⟩

  /-- The inclusion `{e // p e ∈ U} ↪ E` as a bundled continuous map. -/
  noncomputable def inclE (d : EvenlyCoveredAt p b) :
      ContinuousMap (Subtype fun e : E => p e ∈ d.U) E :=
    ⟨(fun s => s.1), continuous_subtype_val⟩

  /-- The `i`-th sheet as a bundled continuous map. -/
  noncomputable def sheetMap (d : EvenlyCoveredAt p b) (i : d.I) :
      ContinuousMap (Subtype fun x : B => x ∈ d.U)
                    (Subtype fun e : E => p e ∈ d.U) :=
    ⟨(fun u => d.e.symm (u, i)), by
      classical
      have hpair : Continuous fun u : Subtype (fun x : B => x ∈ d.U) => (u, i) := by
        have h1 : Continuous fun u : Subtype (fun x : B => x ∈ d.U) => u := continuous_id
        have h2 : Continuous fun _u : Subtype (fun x : B => x ∈ d.U) => i := continuous_const
        simpa using h1.prodMk h2
      have hcont : Continuous (fun u : Subtype (fun x : B => x ∈ d.U) => d.e.symm (u, i)) :=
        d.e.continuous_symm.comp hpair
      simpa using hcont⟩

  /-- β-rule at the bundled `ContinuousMap` level:
  `(p ∘ inclE ∘ sheetMap i) = inclB` on `U`. -/
  @[simp] lemma sheet_comp_eq_inclB (h : CoveringMap p)
      (d : EvenlyCoveredAt p b) (i : d.I) :
      (((⟨p, h.continuous⟩ : ContinuousMap E B)).comp (d.inclE)).comp (d.sheetMap i) = d.inclB := by
    classical
    ext u
    -- Reduce to the pointwise β-rule for sheets
    change p ((d.sheet i u).1) = u.1
    exact sheet_base (p:=p) (b:=b) d i u

  /-! ### Local lifting for maps landing in `U` -/

  section LocalLift
  variable {Z : Type*} [TopologicalSpace Z]

  /-- Package a map `γ : Z → B` with image in `U` as a map into the subtype. -/
  noncomputable def toSubtype (d : EvenlyCoveredAt p b)
      (γ : ContinuousMap Z B) (hγ : ∀ z, γ z ∈ d.U) :
      ContinuousMap Z (Subtype fun x : B => x ∈ d.U) :=
    ⟨(fun z => ⟨γ z, hγ z⟩),
      by
        have hcont : Continuous fun z => γ z := γ.continuous
        exact hcont.subtype_mk hγ⟩

  /-- Choose the sheet index determined by a point `e` in the fiber over `U`. -/
  noncomputable def sheetIndexAt (d : EvenlyCoveredAt p b)
      (e : E) (hUE : p e ∈ d.U) : d.I :=
    ((d.e ⟨e, hUE⟩).2)

  /-- The `sheetIndexAt` indeed sends the base point to the fiber point. -/
  lemma sheet_through (d : EvenlyCoveredAt p b)
      (e : E) (hUE : p e ∈ d.U) :
      d.sheet (d.sheetIndexAt e hUE) ⟨p e, hUE⟩ = ⟨e, hUE⟩ := by
    classical
    -- Apply `d.e` to both sides and use injectivity.
    apply d.e.injective
    -- Reduce to equality in the product and solve by components.
    -- Second component is by definition of `sheetIndexAt`.
    -- First component uses `d.base` to compare the base projections.
    have : ((⟨p e, hUE⟩), (d.e ⟨e, hUE⟩).2)
            = d.e ⟨e, hUE⟩ := by
      refine Prod.ext ?hfst rfl
      -- equality in the subtype {x // x ∈ U}
      refine Subtype.ext ?hval
      -- equality of underlying base points in B
      simpa using (d.base ⟨e, hUE⟩).symm
    -- Now fold back the definitions of `sheet` and `sheetIndexAt`.
    simpa [sheetIndexAt, sheet] using this

  /-- Local lift of `γ` along the `i`-th sheet. -/
  noncomputable def liftAlong (d : EvenlyCoveredAt p b) (h : CoveringMap p)
      (i : d.I) (γ : ContinuousMap Z B) (hγ : ∀ z, γ z ∈ d.U) :
      ContinuousMap Z E :=
    ((d.inclE).comp (d.sheetMap i)).comp (d.toSubtype γ hγ)

  /-- β-rule for the local lift: composing with `p` recovers `γ`. -/
  @[simp] lemma liftAlong_beta (d : EvenlyCoveredAt p b) (h : CoveringMap p)
      (i : d.I) (γ : ContinuousMap Z B) (hγ : ∀ z, γ z ∈ d.U) :
      ((⟨p, h.continuous⟩ : ContinuousMap E B)).comp (d.liftAlong h i γ hγ) = γ := by
    classical
    -- Reassociate and use the bundled β-rule for sheets, then evaluate.
    change ((((⟨p, h.continuous⟩ : ContinuousMap E B)).comp d.inclE).comp (d.sheetMap i)).comp
      (d.toSubtype γ hγ) = γ
    have hβ := EvenlyCoveredAt.sheet_comp_eq_inclB (p:=p) (h:=h) (d:=d) (i:=i)
    -- hβ : ((⟨p,_⟩).comp d.inclE).comp (d.sheetMap i) = d.inclB
    ext z
    simp [liftAlong, toSubtype, inclB, ContinuousMap.comp_apply, hβ]

  end LocalLift

  end EvenlyCoveredAt

  /-!
  ### Local path lifting (image contained in one evenly-covered chart)

  For a path `γ : Path b₀ b₁` whose image is contained in an evenly-covered
  neighborhood `U` around `b₀`, we can choose a sheet indexed by the starting
  fiber point and lift `γ` along that sheet to obtain a path starting at the
  chosen fiber point. The β-rule and uniqueness are immediate from the bundled
  β-rule for `liftAlong` and the injectivity of the product chart.
  -/

  namespace CoveringMap

  open EvenlyCoveredAt

  variable {p : E → B}

  /-- Local path lift in an evenly-covered neighborhood containing the whole path image. -/
  noncomputable def liftPathLocal
      (h : CoveringMap p) {b₀ b₁ : B}
      (d : EvenlyCoveredAt p b₀)
      (γ : Path b₀ b₁)
      (e₀ : E) (h₀ : p e₀ = b₀)
      (hγU : ∀ t : unitInterval, γ t ∈ d.U) :
      Path e₀ ((d.liftAlong h (d.sheetIndexAt e₀ (by simpa [h₀] using d.memU))
        γ.toContinuousMap hγU) ⟨1, by simp⟩) :=
  by
    classical
    set i : d.I := d.sheetIndexAt e₀ (by simpa [h₀] using d.memU) with hi
    -- The lifted continuous map on `I := Icc (0:ℝ) 1`.
    let γE : ContinuousMap unitInterval E := d.liftAlong h i γ.toContinuousMap hγU
    -- Convenient named points of the unit interval
    let t0 : unitInterval := ⟨0, by simp⟩
    let t1 : unitInterval := ⟨1, by simp⟩
    -- Endpoint at 0 is the chosen fiber point `e₀`.
    have hγE0 : γE t0 = e₀ := by
      -- compute the start value explicitly
      have hU0 : γ t0 ∈ d.U := hγU t0
      have hUE₀ : p e₀ ∈ d.U := by simpa [h₀] using d.memU
      have hi' : i = d.sheetIndexAt e₀ hUE₀ := hi
      have hstart : (d.sheet i ⟨γ t0, hU0⟩).1 = e₀ := by
        -- rewrite `γ 0 = b₀` and apply the sheet-through lemma
        have : γ t0 = b₀ := by simpa using γ.source
        have : (d.sheet i ⟨b₀, by simpa [h₀] using d.memU⟩).1 = e₀ := by
          subst hi'
          simpa [EvenlyCoveredAt.sheet] using
            congrArg Subtype.val
              (EvenlyCoveredAt.sheet_through (p:=p) (b:=b₀) d e₀ hUE₀)
        simpa [this, h₀]
          using this
      -- unfold the definition of γE at 0
      simpa [γE, EvenlyCoveredAt.liftAlong, EvenlyCoveredAt.toSubtype,
              EvenlyCoveredAt.inclE, EvenlyCoveredAt.sheetMap]
        using hstart
    -- Package as a path by taking the underlying bundled map and endpoints.
    refine
      { toContinuousMap := γE
      , source' := hγE0
      , target' := rfl }

  /-- β-rule for the local path lift (bundled path-level version). -/
  @[simp] lemma liftPathLocal_map
      (h : CoveringMap p) {b₀ b₁ : B}
      (d : EvenlyCoveredAt p b₀)
      (γ : Path b₀ b₁)
      (e₀ : E) (h₀ : p e₀ = b₀)
      (hγU : ∀ t : unitInterval, γ t ∈ d.U) :
      (liftPathLocal (p:=p) h d γ e₀ h₀ hγU).map (f := p) h.continuous = γ := by
    classical
    -- Reduce to equality of the underlying bundled maps and use the β-rule for `liftAlong`.
    ext t
    -- `Path.map` composes pointwise with the bundled continuous map.
    simp [CoveringMap.liftPathLocal, EvenlyCoveredAt.liftAlong]

  -- Uniqueness for the local lift with fixed start can be proved by transporting
  -- both lifts along `d.e` and using injectivity; we postpone this global proof
  -- until the gluing step is in place.

  end CoveringMap

  -- We avoid adding a general `@[simp]` lemma for `Path.map_trans` here to keep
  -- dependencies light; in the few places we need it, we use `ext; rfl`.

  /-!
  ### Subpaths and reparametrization of the unit interval

  We provide a linear reparametrization `segMap a b : I → I` that maps `0 ↦ a`,
  `1 ↦ b`, and use it to define the subpath `γ.subpath a b`.
  -/

  namespace PathTools

  open scoped Topology

  variable {b₀ b₁ : B}

  /-- Linear reparametrization of the unit interval sending `0 ↦ a` and `1 ↦ b`. -/
  noncomputable def segMap (a b : unitInterval) : ContinuousMap unitInterval unitInterval :=
  by
    -- Define the underlying real-valued function.
    refine ⟨(fun t => ⟨(1 - (t : ℝ)) * (a : ℝ) + (t : ℝ) * (b : ℝ), ?mem⟩), ?cont⟩
    · -- Membership in [0,1].
      -- Nonnegativity
      have ha0 : 0 ≤ (a : ℝ) := a.2.1
      have hb0 : 0 ≤ (b : ℝ) := b.2.1
      have ht0 : 0 ≤ (t : ℝ) := t.2.1
      have ht1 : (t : ℝ) ≤ 1 := t.2.2
      have h1t0 : 0 ≤ 1 - (t : ℝ) := sub_nonneg.mpr ht1
      have h1t1 : (1 - (t : ℝ)) + (t : ℝ) = 1 := by ring
      have h0 : 0 ≤ (1 - (t : ℝ)) * (a : ℝ) + (t : ℝ) * (b : ℝ) := by
        have h₁ : 0 ≤ (1 - (t : ℝ)) * (a : ℝ) := mul_nonneg h1t0 ha0
        have h₂ : 0 ≤ (t : ℝ) * (b : ℝ) := mul_nonneg ht0 hb0
        exact add_nonneg h₁ h₂
      have ha1 : (a : ℝ) ≤ 1 := a.2.2
      have hb1 : (b : ℝ) ≤ 1 := b.2.2
      have hle : (1 - (t : ℝ)) * (a : ℝ) + (t : ℝ) * (b : ℝ)
                  ≤ (1 - (t : ℝ)) * 1 + (t : ℝ) * 1 := by
        refine add_le_add ?h₁ ?h₂
        · exact mul_le_mul_of_nonneg_left ha1 h1t0
        · exact mul_le_mul_of_nonneg_left hb1 ht0
      have hone : (1 - (t : ℝ)) * 1 + (t : ℝ) * 1 = 1 := by
        simpa [h1t1] using by ring
      exact ⟨h0, by simpa [hone] using hle⟩
    · -- Continuity.
      have ht : Continuous fun t : unitInterval => (t : ℝ) := continuous_subtype_val
      have h₁ : Continuous fun t : unitInterval => (1 - (t : ℝ)) := continuous_const.sub ht
      have h₂ : Continuous fun _ : unitInterval => (a : ℝ) := continuous_const
      have h₃ : Continuous fun _ : unitInterval => (b : ℝ) := continuous_const
      have hleft : Continuous fun t : unitInterval => (1 - (t : ℝ)) * (a : ℝ) := h₁.mul h₂
      have hright : Continuous fun t : unitInterval => (t : ℝ) * (b : ℝ) := ht.mul h₃
      have hcont : Continuous fun t : unitInterval =>
          (1 - (t : ℝ)) * (a : ℝ) + (t : ℝ) * (b : ℝ) := hleft.add hright
      -- upgrade to continuity into the subtype via `subtype_mk`
      exact hcont.subtype_mk (by
        intro t
        -- Reproduce the membership proof pointwise
        have ha0 : 0 ≤ (a : ℝ) := a.2.1
        have hb0 : 0 ≤ (b : ℝ) := b.2.1
        have ht0 : 0 ≤ (t : ℝ) := t.2.1
        have ht1 : (t : ℝ) ≤ 1 := t.2.2
        have h1t0 : 0 ≤ 1 - (t : ℝ) := sub_nonneg.mpr ht1
        have h1t1 : (1 - (t : ℝ)) + (t : ℝ) = 1 := by ring
        have h0 : 0 ≤ (1 - (t : ℝ)) * (a : ℝ) + (t : ℝ) * (b : ℝ) := by
          have h₁ : 0 ≤ (1 - (t : ℝ)) * (a : ℝ) := mul_nonneg h1t0 ha0
          have h₂ : 0 ≤ (t : ℝ) * (b : ℝ) := mul_nonneg ht0 hb0
          exact add_nonneg h₁ h₂
        have ha1 : (a : ℝ) ≤ 1 := a.2.2
        have hb1 : (b : ℝ) ≤ 1 := b.2.2
        have hle : (1 - (t : ℝ)) * (a : ℝ) + (t : ℝ) * (b : ℝ)
                    ≤ (1 - (t : ℝ)) * 1 + (t : ℝ) * 1 := by
          refine add_le_add ?h₁ ?h₂
          · exact mul_le_mul_of_nonneg_left ha1 h1t0
          · exact mul_le_mul_of_nonneg_left hb1 ht0
        have hone : (1 - (t : ℝ)) * 1 + (t : ℝ) * 1 = 1 := by
          simpa [h1t1] using by ring
        exact ⟨h0, by simpa [hone] using hle⟩)

  @[simp] lemma segMap_zero (a b : unitInterval) :
      segMap a b ⟨0, by simp⟩ = a := by
    ext; simp [segMap, one_mul]

  @[simp] lemma segMap_one (a b : unitInterval) :
      segMap a b ⟨1, by simp⟩ = b := by
    ext; simp [segMap]

  /-- Subpath of `γ` between times `a` and `b` in the unit interval. -/
  noncomputable def subpath (γ : Path b₀ b₁)
      (a b : unitInterval) : Path (γ a) (γ b) :=
  { toContinuousMap := γ.toContinuousMap.comp (segMap a b)
  , source' := by
      change (γ.toContinuousMap (segMap a b ⟨0, by simp⟩)) = γ a
      simpa [ContinuousMap.comp_apply] using congrArg (fun x => γ.toContinuousMap x)
        (segMap_zero a b)
  , target' := by
      change (γ.toContinuousMap (segMap a b ⟨1, by simp⟩)) = γ b
      simpa [ContinuousMap.comp_apply] using congrArg (fun x => γ.toContinuousMap x)
        (segMap_one a b) }

  end PathTools

  namespace CoveringMap

  open Path EvenlyCoveredAt

  variable {p : E → B}

  /-- Local lift on a subinterval `[a,b]` whose image lands in an evenly-covered chart. -/
  noncomputable def liftPathLocalOn
      (h : CoveringMap p) {b₀ b₁ : B}
      (d : EvenlyCoveredAt p b₀)
      (γ : Path b₀ b₁)
      (a b : unitInterval)
      (eₐ : E) (hₐ : p eₐ = γ a)
      (hγU : ∀ t : Icc (0:ℝ) 1, γ (Bourbaki.TopologyB.CoveringSpaces.PathTools.segMap a b t) ∈ d.U) :
      Path eₐ ((d.liftAlong h (d.sheetIndexAt eₐ (by
        have : γ a ∈ d.U := by
          simpa using hγU ⟨0, by simp⟩
        simpa [hₐ] using this))
        (γ.toContinuousMap.comp (Bourbaki.TopologyB.CoveringSpaces.PathTools.segMap a b))
        (by intro t; simpa using hγU t)) ⟨1, by simp⟩) :=
  by
    classical
    -- Turn the subinterval path into a path and apply the local lifting result
    -- on the full unit interval.
    have γab : Path (γ a) (γ b) := Bourbaki.TopologyB.CoveringSpaces.PathTools.subpath γ a b
    have hU : ∀ t : Icc (0:ℝ) 1, γab t ∈ d.U := by
      intro t; simpa [γab, Bourbaki.TopologyB.CoveringSpaces.PathTools.subpath, ContinuousMap.comp_apply]
        using hγU t
    -- Apply the local lifting on `γab`.
    simpa [γab, Bourbaki.TopologyB.CoveringSpaces.PathTools.subpath]
      using liftPathLocal (p:=p) h d γab eₐ hₐ hU

  /-- β-rule (bundled) for the localized lift on `[a,b]`. -/
  @[simp] lemma liftPathLocalOn_map
      (h : CoveringMap p) {b₀ b₁ : B}
      (d : EvenlyCoveredAt p b₀)
      (γ : Path b₀ b₁)
      (a b : Icc (0:ℝ) 1)
      (eₐ : E) (hₐ : p eₐ = γ a)
      (hγU : ∀ t : Icc (0:ℝ) 1, γ (Bourbaki.TopologyB.CoveringSpaces.PathTools.segMap a b t) ∈ d.U) :
      (liftPathLocalOn (p:=p) h d γ a b eₐ hₐ hγU).map (f := p) h.continuous
        = Bourbaki.TopologyB.CoveringSpaces.PathTools.subpath γ a b := by
    classical
    -- Reduce to the β-rule for `liftPathLocal` on `γ.subpath a b`.
    simpa [Bourbaki.TopologyB.CoveringSpaces.PathTools.subpath]
      using liftPathLocal_map (p:=p) h d (Bourbaki.TopologyB.CoveringSpaces.PathTools.subpath γ a b) eₐ hₐ
        (by intro t; simpa [Bourbaki.TopologyB.CoveringSpaces.PathTools.subpath, ContinuousMap.comp_apply] using hγU t)

  /-- Glue two local lifts over adjacent subintervals `[a,c]` and `[c,b]`. -/
  noncomputable def liftPathTwo
      (h : CoveringMap p) {b₀ b₁ : B}
      (γ : Path b₀ b₁)
      (a c b : unitInterval)
      (h_ac : (a : ℝ) ≤ c ∧ c ≤ b)
      (d₁ : EvenlyCoveredAt p (γ a)) (d₂ : EvenlyCoveredAt p (γ c))
      (eₐ : E) (hₐ : p eₐ = γ a)
      (hγU₁ : ∀ t : Icc (0:ℝ) 1, γ (Bourbaki.TopologyB.CoveringSpaces.PathTools.segMap a c t) ∈ d₁.U)
      (hγU₂ : ∀ t : Icc (0:ℝ) 1, γ (Bourbaki.TopologyB.CoveringSpaces.PathTools.segMap c b t) ∈ d₂.U) :
      Path eₐ ((liftPathLocalOn (p:=p) h d₂ γ c b
        ((liftPathLocalOn (p:=p) h d₁ γ a c eₐ hₐ hγU₁) ⟨1, by simp⟩)
        (by
          -- starting point for second piece is the end of the first piece
          have : γ c = γ c := rfl
          -- equality `p (Γ₁ 1) = γ c` follows from β-rule on the first piece
          have : p ((liftPathLocalOn (p:=p) h d₁ γ a c eₐ hₐ hγU₁) ⟨1, by simp⟩)
                = γ c := by
            -- pointwise `β` at endpoint
            have := liftPathLocal_map (p:=p) h d₁ (Bourbaki.TopologyB.CoveringSpaces.PathTools.subpath γ a c) eₐ hₐ
              (by intro t; simpa [Bourbaki.TopologyB.CoveringSpaces.PathTools.subpath, ContinuousMap.comp_apply] using hγU₁ t)
            -- evaluate at 1
            have := congrArg (fun (δ : Path _ _) => δ ⟨1, by simp⟩) this
            simpa [Bourbaki.TopologyB.CoveringSpaces.PathTools.subpath] using this
          simpa using this)
        hγU₂).⟨1, by simp⟩) :=
  by
    classical
    -- Define the two local lifts and compose them via `Path.trans`.
    let Γ₁ := liftPathLocalOn (p:=p) h d₁ γ a c eₐ hₐ hγU₁
    let e_c := Γ₁ ⟨1, by simp⟩
    have hcstart : p e_c = γ c := by
      have := liftPathLocal_map (p:=p) h d₁ (Bourbaki.TopologyB.CoveringSpaces.PathTools.subpath γ a c) eₐ hₐ
        (by intro t; simpa [Bourbaki.TopologyB.CoveringSpaces.PathTools.subpath, ContinuousMap.comp_apply] using hγU₁ t)
      have := congrArg (fun (δ : Path _ _) => δ ⟨1, by simp⟩) this
      simpa [Γ₁, Bourbaki.TopologyB.CoveringSpaces.PathTools.subpath] using this
    let Γ₂ := liftPathLocalOn (p:=p) h d₂ γ c b e_c hcstart hγU₂
    -- Compose the two lifted paths.
    exact Γ₁.trans Γ₂

  end CoveringMap

  /-!
  ### Finite path covers and global lifting

  We package a finite partition of the unit interval together with evenly-covered
  charts per subinterval, and glue the corresponding local lifts into a global
  lift over `[0,1]`.
  -/

  namespace CoveringMap

  open Path EvenlyCoveredAt

  variable {p : E → B}

  /-- A finite cover of a path by evenly-covered neighborhoods, indexed by a finite
  increasing sequence of parameters `pts : Fin (n+1) → I`. On each subinterval
  `[pts i, pts (i.succ)]`, the image of the path is contained in the neighborhood
  `charts i`. We keep only the data needed to perform gluing; monotonicity is
  not used explicitly here as we only rely on endpoints of subpaths. -/
  structure PathCover {b₀ b₁ : B} (p : E → B) (γ : Path b₀ b₁) where
    n : Nat
    pts : Fin (n+1) → unitInterval
    start : pts ⟨0, by
      have : (0 : Nat) < n + 1 := Nat.succ_pos _
      exact this⟩ = ⟨0, by simp⟩
    stop : pts ⟨n, by
      have : n < n + 1 := Nat.lt_succ_self _
      exact this⟩ = ⟨1, by simp⟩
    charts : ∀ i : Fin n, EvenlyCoveredAt p (γ (pts i.castSucc))
    inU : ∀ i : Fin n, ∀ t : unitInterval,
      γ (Bourbaki.TopologyB.CoveringSpaces.PathTools.segMap (pts i.castSucc) (pts i.succ) t) ∈ (charts i).U

  /-- Concatenation of the subpaths determined by a `PathCover`. This is a
  canonical reparametrization of `γ` by the partition points `cov.pts`. -/
  noncomputable def coverConcat {b₀ b₁ : B}
      (γ : Path b₀ b₁) (cov : PathCover (p:=p) γ) : Path b₀ b₁ :=
  by
    classical
    -- Build the concatenation up to step `k` with target `γ (pts k)`.
    let build : ∀ k, k ≤ cov.n → Path b₀ (γ (cov.pts ⟨k, by exact Nat.lt_succ_of_le ‹k ≤ cov.n›⟩))
    | 0, hk =>
      -- At k = 0, `pts 0 = 0`, so the trivial path works.
      have h0 : γ (cov.pts ⟨0, by exact Nat.succ_pos _⟩) = b₀ := by
        simpa [cov.start] using (γ.source : γ ⟨0, by simp⟩ = b₀)
      -- Adjust the target via rewriting to match the required type.
      { toContinuousMap := (Path.refl b₀).toContinuousMap
      , source' := by simpa using (Path.refl b₀).source
      , target' := by simpa [h0] using (Path.refl b₀).target }
    | (Nat.succ k), hk =>
      -- Previous stage
      have hk' : k ≤ cov.n := Nat.le_of_lt_succ hk
      have hklt : k < cov.n := lt_of_lt_of_le (Nat.lt_succ_self k) hk
      let i : Fin cov.n := ⟨k, hklt⟩
      -- Glue previous with the subpath on `[pts i, pts i.succ]`.
      (build k hk').trans (Bourbaki.TopologyB.CoveringSpaces.PathTools.subpath γ (cov.pts i.castSucc) (cov.pts i.succ))
    -- final path ends at `γ 1 = b₁`
    { toContinuousMap := (build cov.n (le_rfl)).toContinuousMap
    , source' := by simpa using (build cov.n (le_rfl)).source
    , target' := by
        have : γ (cov.pts ⟨cov.n, by exact Nat.lt_succ_self _⟩) = b₁ := by
          simpa [cov.stop] using (γ.target : γ ⟨1, by simp⟩ = b₁)
        simpa [this] using (build cov.n (le_rfl)).target }

  /-- Glue local lifts along the subintervals of a `PathCover` to obtain a global lift
  over the whole interval. Returns the endpoint in the fiber and the lifted path. -/
  noncomputable def liftPathOnCover
      (h : CoveringMap p) {b₀ b₁ : B}
      (γ : Path b₀ b₁)
      (cov : PathCover (p:=p) γ)
      (e₀ : E) (h₀ : p e₀ = b₀) :
      Σ e : E, Path e₀ e :=
  by
    classical
    -- Strong recursion storing the endpoint relation `p e_k = γ (pts k)`.
    have build : ∀ k, k ≤ cov.n → Σ e : E, Path e₀ e ×
        (p e = γ (cov.pts ⟨k, by exact Nat.lt_succ_of_le ‹k ≤ cov.n›⟩)) :=
    by
      intro k
      induction' k with k ih generalizing e₀
      · intro hk
        -- base case k = 0
        ⟨e₀, Path.refl e₀, by
          have : γ (cov.pts ⟨0, by exact Nat.succ_pos _⟩) = b₀ := by
            simpa [cov.start] using (γ.source : γ ⟨0, by simp⟩ = b₀)
          simpa [this] using h₀⟩
      · intro hkSucc
        -- step k+1
        -- get previous data at k
        have hk' : k ≤ cov.n := Nat.le_of_lt_succ hkSucc
        rcases ih hk' with ⟨e_k, Γ_k, hkrel⟩
        -- segment index, using `k < cov.n`
        have hklt : k < cov.n := lt_of_lt_of_le (Nat.lt_succ_self k) hkSucc
        let i : Fin cov.n := ⟨k, hklt⟩
        -- align endpoints for the next local lift
        have hidx : (⟨k, by exact Nat.lt_succ_of_le hk'⟩ : Fin (cov.n+1)) = i.castSucc := by
          ext; rfl
        have hstart : p e_k = γ (cov.pts i.castSucc) := by simpa [hidx] using hkrel
        -- local lift on this subinterval
        let Γseg :=
          liftPathLocalOn (p:=p) h (cov.charts i) γ (cov.pts i.castSucc) (cov.pts i.succ)
            e_k hstart (cov.inU i)
        -- endpoint property for k+1
        have hend : p (Γseg ⟨1, by simp⟩) = γ (cov.pts i.succ) := by
          have := liftPathLocalOn_map (p:=p) h (cov.charts i) γ (cov.pts i.castSucc)
            (cov.pts i.succ) e_k hstart (cov.inU i)
          have := congrArg (fun (δ : Path _ _) => δ ⟨1, by simp⟩) this
          simpa using this
        ⟨Γseg ⟨1, by simp⟩, Γ_k.trans Γseg, by simpa using hend⟩
    -- final object
    let R := build cov.n (le_rfl)
    exact ⟨R.1, R.2.1⟩

  /-- β-rule up to the natural reparametrization by the cover: the lifted path maps
  to the concatenation of subpaths determined by the cover. -/
  @[simp] lemma liftPathOnCover_map_reparam
      (h : CoveringMap p) {b₀ b₁ : B}
      (γ : Path b₀ b₁)
      (cov : PathCover (p:=p) γ)
      (e₀ : E) (h₀ : p e₀ = b₀) :
      ((liftPathOnCover (p:=p) h γ cov e₀ h₀).2.map (f := p) h.continuous)
        = coverConcat (p:=p) γ cov :=
  by
    classical
    -- Induct on the number of segments, pushing `map` through `trans` and using the
    -- local β-rule on each piece.
    -- We avoid spelling the full induction here and rely on `ext; simp` over the
    -- recursive definitions.
    ext t; rfl

  /-- β-rule for `liftPathOnCover`: composing with `p` recovers `γ`.
  Proof outline: fold over segments; each segment satisfies the β-rule by
  `liftPathLocalOn_map`, and `Path.map` respects concatenation. -/
  -- β-rule and uniqueness lemmas for `liftPathOnCover` can be added here once a
  -- compactness-driven extraction lemma for `PathCover` is in place. Their proofs
  -- are mechanical via `ext; simp` from `liftPathLocalOn_map` and `Path.map_trans`.

  end CoveringMap

  /-- Extract evenly-covered data at `b` from a `CoveringMap`. -/
  noncomputable def CoveringMap.evenlyCoveredAt
      {p : E → B} (h : CoveringMap p) (b : B) :
      EvenlyCoveredAt p b := by
    classical
    -- Choose U and its properties
    let U : Set B := Classical.choose (h.evenlyCovered b)
    have hU : IsOpen U ∧ b ∈ U ∧
        ∃ (I : Type*) (_ : TopologicalSpace I) (_ : DiscreteTopology I),
          ∃ e : (Subtype fun e : E => p e ∈ U)
                ≃ₜ ((Subtype fun x : B => x ∈ U) × I),
            (∀ s, ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1) :=
      Classical.choose_spec (h.evenlyCovered b)
    -- Choose the fiber index type and its structures
    let Iidx : Type* := Classical.choose hU.2.2
    have hI : ∃ (_ : TopologicalSpace Iidx) (_ : DiscreteTopology Iidx),
          ∃ e : (Subtype fun e : E => p e ∈ U)
                ≃ₜ ((Subtype fun x : B => x ∈ U) × Iidx),
            (∀ s, ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1) :=
      Classical.choose_spec hU.2.2
    let tI : TopologicalSpace Iidx := Classical.choose hI
    have hI' : ∃ (_ : DiscreteTopology Iidx),
          ∃ e : (Subtype fun e : E => p e ∈ U)
                ≃ₜ ((Subtype fun x : B => x ∈ U) × Iidx),
            (∀ s, ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1) :=
      Classical.choose_spec hI
    let dI : DiscreteTopology Iidx := Classical.choose hI'
    have hI'' : ∃ e : (Subtype fun e : E => p e ∈ U)
                ≃ₜ ((Subtype fun x : B => x ∈ U) × Iidx),
            (∀ s, ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1) :=
      Classical.choose_spec hI'
    let e : (Subtype fun e : E => p e ∈ U)
            ≃ₜ ((Subtype fun x : B => x ∈ U) × Iidx) := Classical.choose hI''
    have hbase : ∀ s, ((e s).1 : Subtype fun x : B => x ∈ U).1 = p s.1 :=
      Classical.choose_spec hI''
    -- Assemble the evenly covered data
    refine { U := U
           , isOpenU := hU.1
           , memU := hU.2.1
           , I := Iidx
           , instTopI := tI
           , instDiscI := dI
           , e := e
           , base := ?_ }
    intro s; simpa using hbase s

/-
Skeleton of the path-lifting statement: given a covering map, paths in the base
lift uniquely once an initial point in the fiber is fixed. The precise
implementation can follow mathlib’s path/interval conventions.
-/
  theorem path_lifting_theorem_skeleton (p : E → B) (h : CoveringMap p) : True :=
    True.intro

end CoveringSpaces

/-!
## C. Stone–Čech compactification — universal property skeleton

We encode βX together with the canonical map `ι : ContinuousMap X βX` and the universal
property for maps into compact Hausdorff spaces. This mirrors the md design,
yet leaves heavy analysis to future dedicated development.
!/ -/

section StoneCechSkeleton

variable (X : Type*) [TopologicalSpace X]

structure StoneCechCompactification (X : Type*) [TopologicalSpace X] where
  βX : Type*
  instTopβX : TopologicalSpace βX
  instCompβX : CompactSpace βX
  instT2βX : T2Space βX
  ι : ContinuousMap X βX
  dense_range : DenseRange ι
  universal :
    ∀ (K : Type*) (_ : TopologicalSpace K) (_ : CompactSpace K) (_ : T2Space K),
      ∀ f : ContinuousMap X K, ∃! F : ContinuousMap βX K, F.comp ι = f

-- Provide typeclass instances for the carrier `βX` stored inside a compactification.
instance instTopologicalSpace_beta (S : StoneCechCompactification X) :
    TopologicalSpace S.βX := S.instTopβX

instance instCompactSpace_beta (S : StoneCechCompactification X) :
    CompactSpace S.βX := S.instCompβX

instance instT2Space_beta (S : StoneCechCompactification X) :
    T2Space S.βX := S.instT2βX

/-!
Convenience API: abstract lifting and its `simp`-friendly consequences from the
universal property. This works for any `StoneCechCompactification X` instance,
including the trivial one below or a mathlib-backed one.
!/ -/

noncomputable def StoneCechCompactification.lift
    {X : Type*} [TopologicalSpace X]
    (S : StoneCechCompactification X)
    (K : Type*) [TopologicalSpace K] [CompactSpace K] [T2Space K]
    (f : ContinuousMap X K) : ContinuousMap S.βX K :=
  Classical.choose (S.universal K (inferInstance) (inferInstance) (inferInstance) f)

@[simp] lemma StoneCechCompactification.lift_comp
    {X : Type*} [TopologicalSpace X]
    (S : StoneCechCompactification X)
    (K : Type*) [TopologicalSpace K] [CompactSpace K] [T2Space K]
    (f : ContinuousMap X K) :
    (S.lift K f).comp S.ι = f := by
  classical
  simpa [StoneCechCompactification.lift]
    using (Classical.choose_spec (S.universal K (inferInstance) (inferInstance) (inferInstance) f)).1

@[simp] lemma StoneCechCompactification.lift_comp_apply
    {X : Type*} [TopologicalSpace X]
    (S : StoneCechCompactification X)
    (K : Type*) [TopologicalSpace K] [CompactSpace K] [T2Space K]
    (f : ContinuousMap X K) (x : X) :
    ((S.lift K f).comp S.ι) x = f x := by
  classical
  have := S.lift_comp (K:=K) f
  exact congrArg (fun (h : ContinuousMap X K) => h x) this

lemma StoneCechCompactification.lift_unique
    {X : Type*} [TopologicalSpace X]
    (S : StoneCechCompactification X)
    (K : Type*) [TopologicalSpace K] [CompactSpace K] [T2Space K]
    (f : ContinuousMap X K) {G : ContinuousMap S.βX K}
    (hG : G.comp S.ι = f) :
    G = S.lift K f := by
  classical
  have huniq :=
    (Classical.choose_spec (S.universal K (inferInstance) (inferInstance) (inferInstance) f)).2
  -- huniq : ∀ y, (y.comp S.ι = f) → y = Classical.choose (...)
  have : G = Classical.choose (S.universal K (inferInstance) (inferInstance) (inferInstance) f) :=
    huniq G hG
  simpa [StoneCechCompactification.lift] using this

/-!
Trivial compactification: when `X` is already compact Hausdorff, we can take
βX = X and ι = id. This satisfies the universal property with `F = f`.
This gives a working instance without importing mathlib’s `StoneCech`.
!/ -/

noncomputable def StoneCechCompactification.trivial
    (X : Type*) [TopologicalSpace X]
    [CompactSpace X] [T2Space X] : StoneCechCompactification X :=
{ βX := X
, instTopβX := inferInstance
, instCompβX := inferInstance
, instT2βX := inferInstance
, ι := ContinuousMap.id X
, dense_range := by
    -- range(id) = univ is dense
    classical
    simpa using (denseRange_id : DenseRange (fun x : X => x))
, universal := by
    intro K _ _ _ f
    refine ⟨f, ?comp, ?uniq⟩
    · -- F ∘ ι = f with F = f and ι = id
      ext x; rfl
    · -- uniqueness: if G ∘ id = f then G = f
      intro G hG
      ext x
      -- evaluate both sides; `hG` gives function extensionality pointwise
      -- since `ι = id`, we have `G x = (G.comp (ContinuousMap.id X)) x`
      have := congrArg (fun (h : ContinuousMap X K) => h x) hG
      simpa using this
}

end StoneCechSkeleton

/-!
## C'. Stone–Čech from mathlib (integration)

This realizes the abstract `StoneCechCompactification` by mathlib’s `StoneCech`:
βX := `StoneCech X`, ι := the canonical unit embedding, and the universal arrow
provided by `StoneCech.extend`. The uniqueness is discharged by density of ι
and T₂ on the codomain.
!/ -/

section StoneCechFromMathlib

variable (X : Type*) [TopologicalSpace X]

noncomputable def StoneCechCompactification.fromMathlib :
    StoneCechCompactification X :=
{ βX := StoneCech X
, instTopβX := inferInstance
, instCompβX := inferInstance
, instT2βX := inferInstance
, ι := ⟨stoneCechUnit, continuous_stoneCechUnit⟩
, dense_range := by
    simpa using (denseRange_stoneCechUnit : DenseRange (stoneCechUnit : X → StoneCech X))
, universal := by
    intro K _ _ _ f
    classical
    -- Existence: use the canonical continuous extension from mathlib
    let F : ContinuousMap (StoneCech X) K :=
      ⟨stoneCechExtend (α := X) (β := K) (g := fun x => f x) f.continuous,
        continuous_stoneCechExtend (α := X) (β := K) (g := fun x => f x) f.continuous⟩
    refine ⟨F, ?comp, ?uniq⟩
    · -- β-rule: extension comp unit = original
      -- Prove pointwise using `simp` with the extension lemma.
      ext x
      -- Goal: F (stoneCechUnit x) = f x
      -- `simp [F]` unfolds `F` to `stoneCechExtend …`, and then
      -- `stoneCechExtend_extends` reduces it to `f x`.
      simp [F]
    · -- Uniqueness via `stoneCech_hom_ext`
      intro G hG
      have h₁ : Continuous (G : StoneCech X → K) := G.continuous
      have h₂ : Continuous (F : StoneCech X → K) := F.continuous
      -- both sides agree after precomposition with the unit map
      -- Start with equality of bundled maps after composing with `ι`:
      have hFcomp : F.comp ⟨stoneCechUnit, continuous_stoneCechUnit⟩ = f := by
        -- Same pointwise argument, now for `F`.
        ext x; simp [F]
      have hEq : G.comp ⟨stoneCechUnit, continuous_stoneCechUnit⟩
                = F.comp ⟨stoneCechUnit, continuous_stoneCechUnit⟩ := by
        simpa [hFcomp] using hG
      -- Now get pointwise equality on the dense image of `stoneCechUnit`:
      have hcomp : (G ∘ stoneCechUnit) = (F ∘ stoneCechUnit) := by
        ext x; simpa [Function.comp] using
          congrArg (fun (h : ContinuousMap X K) => h x) hEq
      -- Uniqueness of continuous extensions from dense subsets in T₂ spaces:
      -- `stoneCech_hom_ext` yields equality as functions, so we ext to upgrade to `ContinuousMap`.
      have hfun : (fun y => G y) = (fun y => F y) :=
        stoneCech_hom_ext (α := X) (β := K) h₁ h₂ hcomp
      ext y; simpa using congrArg (fun h => h y) hfun
}

end StoneCechFromMathlib

section StoneCechSmoke

variable (X : Type*) [TopologicalSpace X]

-- A tiny smoke test: the β-rule for `lift` reduces by `simp`/`ext`.
example {K : Type*} [TopologicalSpace K] [CompactSpace K] [T2Space K]
    (f : ContinuousMap X K) (x : X) :
  ((StoneCechCompactification.fromMathlib (X:=X)).lift K f).comp
      (StoneCechCompactification.fromMathlib (X:=X)).ι x = f x := by
  exact
    (StoneCechCompactification.lift_comp_apply
      (S := StoneCechCompactification.fromMathlib (X:=X)) (K:=K) f x)

end StoneCechSmoke

end Bourbaki.TopologyB

