import Mathlib.RingTheory.Ideal.Basic
import MyProjects.ST.RankCore.Basic

/-!
# PrincipalIdeal (A4 skeleton)

A minimal "principal ideal" example intended as a stepping stone toward Krull / ACC narratives.

We separate:
- the *carrier* of generators `a : R`,
- the *semantic* principal ideal `(a)` as `Ideal.span {a}`,
- a Nat-valued "norm" used as a rank on generators.

This avoids committing to a specific norm (EuclideanDomain, etc.) at A4.
Later milestones can specialize `NatNorm` to concrete norms (e.g. `Int.natAbs`, polynomial degree, ...),
and relate ideal containment to rank decrease.
-/

namespace ST

universe u

namespace PrincipalIdeal

variable {R : Type u} [CommRing R]

/-- A user-supplied Nat-valued norm on a ring. -/
structure NatNorm (R : Type u) where
  norm : R → Nat

variable (N : NatNorm (R := R))

/-- The principal ideal generated by `a`. -/
def principal (a : R) : Ideal R :=
  Ideal.span ({a} : Set R)

/-- Ranked structure on generators, using the chosen norm. -/
def principalRanked : Ranked Nat R where
  rank := N.norm

@[simp] lemma rank_def (a : R) : (principalRanked (R := R) N).rank a = N.norm a := rfl

end PrincipalIdeal

end ST
