# Lean証明エラー修正履歴記録システム
# Version: 1.0.0

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [ValidateSet("record", "analyze", "report", "recovery", "pattern-match")]
    [string]$Action,
    
    [string]$ProofFile = "",
    [string]$ErrorType = "",
    [string]$ErrorMessage = "",
    [string]$Solution = "",
    [string]$TimeSpent = "",
    [ValidateSet("syntax", "type", "tactic", "import", "mathlib", "logic", "performance", "other")]
    [string]$Category = "other",
    [int]$Days = 7
)

# 設定とパス
$WorkflowRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$ErrorLogsPath = Join-Path $WorkflowRoot "error-tracking\logs"
$PatternsPath = Join-Path $WorkflowRoot "error-tracking\patterns"
$RecoveryPath = Join-Path $WorkflowRoot "error-tracking\recovery"

# ディレクトリ確保
@($ErrorLogsPath, $PatternsPath, $RecoveryPath) | ForEach-Object {
    if (-not (Test-Path $_)) {
        New-Item -Path $_ -ItemType Directory -Force | Out-Null
    }
}

# ログ記録関数
function Write-ErrorLog {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logEntry = "[$timestamp] [$Level] $Message"
    
    switch ($Level) {
        "ERROR" { Write-Host $logEntry -ForegroundColor Red }
        "WARNING" { Write-Host $logEntry -ForegroundColor Yellow }
        "SUCCESS" { Write-Host $logEntry -ForegroundColor Green }
        "INFO" { Write-Host $logEntry -ForegroundColor Cyan }
        default { Write-Host $logEntry -ForegroundColor White }
    }
    
    $logFile = Join-Path $ErrorLogsPath "error-tracker-$(Get-Date -Format 'yyyy-MM-dd').log"
    $logEntry | Out-File -FilePath $logFile -Append -Encoding UTF8
}

# エラー記録機能
function Record-ErrorFix {
    param(
        [string]$File,
        [string]$Type,
        [string]$Message,
        [string]$Solution,
        [string]$Category,
        [string]$TimeSpent
    )
    
    Write-ErrorLog "エラー修正記録を作成中..." "INFO"
    
    # 現在のGit情報取得
    $gitInfo = @{
        CommitBefore = ""
        CommitAfter = ""
        Branch = ""
        FileDiff = ""
    }
    
    try {
        $gitInfo.CommitBefore = & git rev-parse HEAD 2>$null
        $gitInfo.Branch = & git branch --show-current 2>$null
        $gitInfo.FileDiff = & git diff HEAD -- $File 2>$null
    } catch {
        Write-ErrorLog "Git情報の取得に部分的に失敗しました" "WARNING"
    }
    
    # エラーレコード作成
    $errorRecord = [PSCustomObject]@{
        Id = [guid]::NewGuid().ToString().Substring(0,8)
        Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        File = $File
        ErrorType = $Type
        ErrorMessage = $Message
        Solution = $Solution
        Category = $Category
        TimeSpentMinutes = if($TimeSpent) { [int]$TimeSpent } else { $null }
        GitInfo = $gitInfo
        Environment = @{
            LeanVersion = (& lean --version 2>$null) -replace "Lean \(version ([^,]+).*", '$1'
            LakeVersion = (& lake --version 2>$null)
            Platform = $env:OS
            Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        }
        Resolution = @{
            Status = "Fixed"
            VerificationPassed = $false
            AutoGenerated = $false
        }
    }
    
    # 検証実行
    if (Test-Path $File) {
        Write-ErrorLog "修正後の検証を実行中..." "INFO"
        $verification = & lake check $File 2>&1
        $errorRecord.Resolution.VerificationPassed = ($LASTEXITCODE -eq 0)
        
        if ($errorRecord.Resolution.VerificationPassed) {
            $gitInfo.CommitAfter = & git rev-parse HEAD 2>$null
            Write-ErrorLog "検証成功: 修正が確認されました" "SUCCESS"
        } else {
            Write-ErrorLog "検証失敗: まだエラーが残っています" "WARNING"
            $errorRecord.Resolution.Status = "Partial"
        }
    }
    
    # レコード保存
    $monthlyLogFile = Join-Path $ErrorLogsPath "error-fixes-$(Get-Date -Format 'yyyy-MM').json"
    
    $existingRecords = @()
    if (Test-Path $monthlyLogFile) {
        try {
            $existingRecords = Get-Content $monthlyLogFile | ConvertFrom-Json
        } catch {
            Write-ErrorLog "既存ログファイルの読み込みに失敗しました" "WARNING"
        }
    }
    
    $allRecords = @($existingRecords) + @($errorRecord)
    $allRecords | ConvertTo-Json -Depth 4 | Out-File -FilePath $monthlyLogFile -Encoding UTF8
    
    Write-ErrorLog "エラー修正記録を保存しました: ID $($errorRecord.Id)" "SUCCESS"
    
    # パターン学習
    Update-ErrorPattern $errorRecord
    
    return $errorRecord
}

# エラーパターン更新
function Update-ErrorPattern {
    param([PSCustomObject]$ErrorRecord)
    
    $patternFile = Join-Path $PatternsPath "error-patterns.json"
    
    $patterns = @{}
    if (Test-Path $patternFile) {
        try {
            $patterns = Get-Content $patternFile | ConvertFrom-Json -AsHashtable
        } catch {
            Write-ErrorLog "パターンファイルの読み込みに失敗しました" "WARNING"
        }
    }
    
    # パターンキー生成
    $patternKey = "$($ErrorRecord.Category)-$($ErrorRecord.ErrorType)"
    
    if (-not $patterns.ContainsKey($patternKey)) {
        $patterns[$patternKey] = @{
            Category = $ErrorRecord.Category
            ErrorType = $ErrorRecord.ErrorType
            Count = 0
            CommonSolutions = @()
            AverageTimeMinutes = 0
            LastSeen = ""
            Examples = @()
        }
    }
    
    # パターン更新
    $pattern = $patterns[$patternKey]
    $pattern.Count++
    $pattern.LastSeen = $ErrorRecord.Timestamp
    
    # 解決策を追加
    if ($ErrorRecord.Solution -and $ErrorRecord.Solution -notin $pattern.CommonSolutions) {
        $pattern.CommonSolutions += $ErrorRecord.Solution
        # 最大5つまで保持
        if ($pattern.CommonSolutions.Count -gt 5) {
            $pattern.CommonSolutions = $pattern.CommonSolutions | Select-Object -Last 5
        }
    }
    
    # 平均時間更新
    if ($ErrorRecord.TimeSpentMinutes) {
        $pattern.AverageTimeMinutes = [math]::Round(($pattern.AverageTimeMinutes + $ErrorRecord.TimeSpentMinutes) / 2, 1)
    }
    
    # 例を追加
    $example = @{
        File = $ErrorRecord.File
        Message = $ErrorRecord.ErrorMessage
        Solution = $ErrorRecord.Solution
        Date = $ErrorRecord.Timestamp
    }
    
    $pattern.Examples += $example
    if ($pattern.Examples.Count -gt 3) {
        $pattern.Examples = $pattern.Examples | Select-Object -Last 3
    }
    
    # パターンファイル保存
    $patterns | ConvertTo-Json -Depth 4 | Out-File -FilePath $patternFile -Encoding UTF8
    
    Write-ErrorLog "エラーパターンを更新しました: $patternKey" "INFO"
}

# エラー分析機能
function Analyze-Errors {
    param([int]$Days)
    
    Write-ErrorLog "$Days 日間のエラー分析を実行中..." "INFO"
    
    $analysisResults = @{
        Period = "$Days days"
        TotalErrors = 0
        ByCategory = @{}
        ByFile = @{}
        TopErrors = @()
        AverageResolutionTime = 0
        TrendAnalysis = @{}
        Recommendations = @()
    }
    
    # 過去のログファイルを収集
    $startDate = (Get-Date).AddDays(-$Days)
    $logFiles = Get-ChildItem -Path $ErrorLogsPath -Filter "error-fixes-*.json" | Where-Object {
        $fileDate = [datetime]::ParseExact($_.BaseName.Split('-')[2] + "-" + $_.BaseName.Split('-')[3], "yyyy-MM", $null)
        $fileDate -ge $startDate.AddMonths(-1)  # 月単位なので少し範囲を広げる
    }
    
    $allErrors = @()
    foreach ($logFile in $logFiles) {
        try {
            $errors = Get-Content $logFile.FullName | ConvertFrom-Json
            $filteredErrors = $errors | Where-Object {
                [datetime]$_.Timestamp -ge $startDate
            }
            $allErrors += $filteredErrors
        } catch {
            Write-ErrorLog "ログファイル読み込みエラー: $($logFile.Name)" "WARNING"
        }
    }
    
    $analysisResults.TotalErrors = $allErrors.Count
    
    if ($allErrors.Count -eq 0) {
        Write-ErrorLog "指定期間にエラーレコードが見つかりませんでした" "INFO"
        return $analysisResults
    }
    
    # カテゴリ別集計
    $analysisResults.ByCategory = $allErrors | Group-Object Category | ForEach-Object {
        @{
            Category = $_.Name
            Count = $_.Count
            Percentage = [math]::Round(($_.Count / $allErrors.Count) * 100, 1)
        }
    }
    
    # ファイル別集計
    $analysisResults.ByFile = $allErrors | Group-Object File | Sort-Object Count -Descending | Select-Object -First 10 | ForEach-Object {
        @{
            File = $_.Name
            ErrorCount = $_.Count
        }
    }
    
    # よくあるエラー
    $analysisResults.TopErrors = $allErrors | Group-Object ErrorType | Sort-Object Count -Descending | Select-Object -First 5 | ForEach-Object {
        @{
            ErrorType = $_.Name
            Count = $_.Count
            Examples = ($_.Group | Select-Object -First 2 | ForEach-Object { $_.ErrorMessage })
        }
    }
    
    # 平均解決時間
    $timeEntries = $allErrors | Where-Object { $_.TimeSpentMinutes -gt 0 }
    if ($timeEntries.Count -gt 0) {
        $analysisResults.AverageResolutionTime = [math]::Round(($timeEntries.TimeSpentMinutes | Measure-Object -Average).Average, 1)
    }
    
    # 推奨事項生成
    $analysisResults.Recommendations = Generate-Recommendations $analysisResults
    
    Write-ErrorLog "分析完了: $($allErrors.Count)件のエラーを分析しました" "SUCCESS"
    
    return $analysisResults
}

# 推奨事項生成
function Generate-Recommendations {
    param($Analysis)
    
    $recommendations = @()
    
    # 最も多いカテゴリに基づく推奨
    $topCategory = $Analysis.ByCategory | Sort-Object Count -Descending | Select-Object -First 1
    if ($topCategory -and $topCategory.Count -gt 2) {
        switch ($topCategory.Category) {
            "syntax" { $recommendations += "構文エラーが多発しています。Lean構文チェッカーの利用を検討してください。" }
            "type" { $recommendations += "型エラーが頻発しています。型注釈の明示的な記述を推奨します。" }
            "tactic" { $recommendations += "戦術エラーが多いです。基本戦術の復習と事前検証を推奨します。" }
            "import" { $recommendations += "インポートエラーが多発しています。依存関係の整理を行ってください。" }
            "mathlib" { $recommendations += "Mathlibエラーが多いです。バージョン互換性を確認してください。" }
        }
    }
    
    # 解決時間が長い場合の推奨
    if ($Analysis.AverageResolutionTime -gt 30) {
        $recommendations += "平均解決時間が長いです($($Analysis.AverageResolutionTime)分)。エラーパターン学習の活用を推奨します。"
    }
    
    # 特定ファイルでエラーが集中している場合
    $problematicFile = $Analysis.ByFile | Where-Object { $_.ErrorCount -gt 3 } | Select-Object -First 1
    if ($problematicFile) {
        $recommendations += "ファイル '$($problematicFile.File)' でエラーが集中しています($($problematicFile.ErrorCount)件)。リファクタリングを検討してください。"
    }
    
    if ($recommendations.Count -eq 0) {
        $recommendations += "エラー発生状況は良好です。現在の開発手法を継続してください。"
    }
    
    return $recommendations
}

# レポート生成
function New-ErrorReport {
    param([int]$Days)
    
    Write-ErrorLog "エラーレポートを生成中..." "INFO"
    
    $analysis = Analyze-Errors $Days
    $reportDate = Get-Date -Format "yyyy-MM-dd"
    $reportFile = Join-Path $WorkflowRoot "reports\error-analysis-$reportDate.md"
    
    $report = @"
# Lean証明エラー分析レポート

**生成日時**: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
**分析期間**: 過去 $Days 日間

## 📊 エラー統計サマリー

- **総エラー件数**: $($analysis.TotalErrors)件
- **平均解決時間**: $($analysis.AverageResolutionTime)分
- **分析期間**: $($analysis.Period)

## 📈 カテゴリ別エラー分布

$(foreach ($cat in ($analysis.ByCategory | Sort-Object Count -Descending)) {
"- **$($cat.Category)**: $($cat.Count)件 ($($cat.Percentage)%)"
})

## 🔍 最も多いエラータイプ (TOP 5)

$(foreach ($error in $analysis.TopErrors) {
"### $($error.ErrorType) ($($error.Count)件)
$(foreach ($example in $error.Examples) { "- ``$example``" })
"
})

## 📄 問題のあるファイル (TOP 10)

$(foreach ($file in $analysis.ByFile) {
"- **$($file.File)**: $($file.ErrorCount)件"
})

## 💡 推奨事項

$(foreach ($rec in $analysis.Recommendations) {
"- $rec"
})

## 🔧 対策アクション

### 即座に実行可能
1. 最頻出エラーパターンの自動修正スクリプト作成
2. 問題ファイルの優先的リファクタリング
3. エラー予防チェックリストの作成

### 中長期的改善
1. 自動エラー検出システムの導入
2. 証明パターンライブラリの構築
3. 開発プロセスの最適化

---
*自動生成レポート - Leanエラー追跡システム*
"@
    
    # レポート保存
    if (-not (Test-Path (Split-Path $reportFile))) {
        New-Item -Path (Split-Path $reportFile) -ItemType Directory -Force | Out-Null
    }
    
    $report | Out-File -FilePath $reportFile -Encoding UTF8
    
    Write-ErrorLog "エラー分析レポートを生成しました: $reportFile" "SUCCESS"
    
    return $reportFile
}

# パターンマッチング機能
function Find-ErrorPattern {
    param([string]$ErrorMessage, [string]$ErrorType = "")
    
    Write-ErrorLog "エラーパターンをマッチング中..." "INFO"
    
    $patternFile = Join-Path $PatternsPath "error-patterns.json"
    if (-not (Test-Path $patternFile)) {
        Write-ErrorLog "パターンファイルが見つかりません" "WARNING"
        return $null
    }
    
    try {
        $patterns = Get-Content $patternFile | ConvertFrom-Json -AsHashtable
    } catch {
        Write-ErrorLog "パターンファイルの読み込みに失敗しました" "ERROR"
        return $null
    }
    
    # 類似パターンを検索
    $matches = @()
    
    foreach ($patternKey in $patterns.Keys) {
        $pattern = $patterns[$patternKey]
        
        # エラータイプが一致する場合は高スコア
        $score = 0
        if ($ErrorType -and $pattern.ErrorType -eq $ErrorType) {
            $score += 50
        }
        
        # エラーメッセージの類似度チェック（簡単な文字列マッチング）
        foreach ($example in $pattern.Examples) {
            $similarity = Get-StringSimilarity $ErrorMessage $example.Message
            if ($similarity -gt 0.3) {
                $score += ($similarity * 30)
            }
        }
        
        if ($score -gt 20) {  # 閾値
            $matches += @{
                Pattern = $pattern
                PatternKey = $patternKey
                Score = $score
                Confidence = [math]::Round($score / 80 * 100, 1)  # パーセンテージ
            }
        }
    }
    
    # スコア順でソート
    $matches = $matches | Sort-Object Score -Descending | Select-Object -First 3
    
    if ($matches.Count -gt 0) {
        Write-ErrorLog "パターンマッチング完了: $($matches.Count)件の候補を発見" "SUCCESS"
        return $matches
    } else {
        Write-ErrorLog "マッチするパターンが見つかりませんでした" "INFO"
        return $null
    }
}

# 文字列類似度計算（簡易版）
function Get-StringSimilarity {
    param([string]$String1, [string]$String2)
    
    if ([string]::IsNullOrEmpty($String1) -or [string]::IsNullOrEmpty($String2)) {
        return 0
    }
    
    # Levenshtein距離ベースの簡易計算
    $longer = if ($String1.Length -gt $String2.Length) { $String1 } else { $String2 }
    $shorter = if ($String1.Length -le $String2.Length) { $String1 } else { $String2 }
    
    if ($longer.Length -eq 0) { return 1 }
    
    # 簡易的な類似度計算
    $commonChars = 0
    for ($i = 0; $i -lt $shorter.Length; $i++) {
        if ($i -lt $longer.Length -and $shorter[$i] -eq $longer[$i]) {
            $commonChars++
        }
    }
    
    return $commonChars / $longer.Length
}

# リカバリ推奨機能
function Get-RecoveryRecommendation {
    param([string]$ErrorMessage, [string]$ErrorType, [string]$File)
    
    Write-ErrorLog "リカバリ推奨を生成中..." "INFO"
    
    # パターンマッチング結果を取得
    $matches = Find-ErrorPattern $ErrorMessage $ErrorType
    
    $recommendations = @{
        ImmediateActions = @()
        Solutions = @()
        PreventionTips = @()
        EstimatedTime = "不明"
        Confidence = 0
    }
    
    if ($matches -and $matches.Count -gt 0) {
        $bestMatch = $matches[0]
        $recommendations.Confidence = $bestMatch.Confidence
        $recommendations.EstimatedTime = "$($bestMatch.Pattern.AverageTimeMinutes)分"
        
        # 過去の解決策を提案
        foreach ($solution in $bestMatch.Pattern.CommonSolutions) {
            $recommendations.Solutions += $solution
        }
    }
    
    # エラータイプ別の一般的な推奨事項
    switch ($ErrorType) {
        "syntax" {
            $recommendations.ImmediateActions += "lake check でファイル全体の構文をチェック"
            $recommendations.ImmediateActions += "Lean Language Server の診断メッセージを確認"
            $recommendations.PreventionTips += "コミット前に必ず構文チェックを実行"
        }
        "type" {
            $recommendations.ImmediateActions += "型注釈を明示的に追加"
            $recommendations.ImmediateActions += "#check コマンドで型を確認"
            $recommendations.PreventionTips += "複雑な式には型注釈を付ける習慣を"
        }
        "tactic" {
            $recommendations.ImmediateActions += "tactic state を確認"
            $recommendations.ImmediateActions += "より基本的な戦術に分解"
            $recommendations.PreventionTips += "戦術の適用前にgoalを明確にする"
        }
        "import" {
            $recommendations.ImmediateActions += "lake update で依存関係を更新"
            $recommendations.ImmediateActions += "import文の順序を確認"
            $recommendations.PreventionTips += "必要最小限のimportのみを行う"
        }
        "mathlib" {
            $recommendations.ImmediateActions += "Mathlib バージョンを確認"
            $recommendations.ImmediateActions += "lake clean && lake build で再ビルド"
            $recommendations.PreventionTips += "Mathlib更新時は段階的に適用"
        }
    }
    
    Write-ErrorLog "リカバリ推奨を生成しました (信頼度: $($recommendations.Confidence)%)" "SUCCESS"
    
    return $recommendations
}

# メイン実行ロジック
switch ($Action) {
    "record" {
        if (-not $ProofFile -or -not $ErrorType) {
            Write-ErrorLog "必須パラメータが不足しています: -ProofFile, -ErrorType" "ERROR"
            exit 1
        }
        
        $record = Record-ErrorFix -File $ProofFile -Type $ErrorType -Message $ErrorMessage -Solution $Solution -Category $Category -TimeSpent $TimeSpent
        Write-Host "`n✅ エラー修正記録を作成しました" -ForegroundColor Green
        Write-Host "記録ID: $($record.Id)"
        Write-Host "ファイル: $($record.File)"
        Write-Host "カテゴリ: $($record.Category)"
    }
    
    "analyze" {
        $analysis = Analyze-Errors $Days
        Write-Host "`n📊 エラー分析結果 (過去 $Days 日間)" -ForegroundColor Cyan
        Write-Host "総エラー数: $($analysis.TotalErrors)"
        Write-Host "平均解決時間: $($analysis.AverageResolutionTime)分"
        Write-Host "`nカテゴリ別:"
        $analysis.ByCategory | ForEach-Object { Write-Host "  $($_.Category): $($_.Count)件" }
    }
    
    "report" {
        $reportFile = New-ErrorReport $Days
        Write-Host "`n📄 エラー分析レポートを生成しました" -ForegroundColor Green
        Write-Host "ファイル: $reportFile"
    }
    
    "recovery" {
        if (-not $ErrorMessage) {
            Write-ErrorLog "エラーメッセージが必要です: -ErrorMessage" "ERROR"
            exit 1
        }
        
        $recommendation = Get-RecoveryRecommendation $ErrorMessage $ErrorType $ProofFile
        Write-Host "`n🔧 リカバリ推奨事項" -ForegroundColor Cyan
        Write-Host "信頼度: $($recommendation.Confidence)%"
        Write-Host "推定時間: $($recommendation.EstimatedTime)"
        Write-Host "`n即座の対応:"
        $recommendation.ImmediateActions | ForEach-Object { Write-Host "  - $_" }
        Write-Host "`n推奨解決策:"
        $recommendation.Solutions | ForEach-Object { Write-Host "  - $_" }
    }
    
    "pattern-match" {
        if (-not $ErrorMessage) {
            Write-ErrorLog "エラーメッセージが必要です: -ErrorMessage" "ERROR"
            exit 1
        }
        
        $matches = Find-ErrorPattern $ErrorMessage $ErrorType
        if ($matches) {
            Write-Host "`n🔍 パターンマッチング結果" -ForegroundColor Cyan
            foreach ($match in $matches) {
                Write-Host "パターン: $($match.PatternKey) (信頼度: $($match.Confidence)%)"
                Write-Host "  発生回数: $($match.Pattern.Count)"
                Write-Host "  推奨解決策: $($match.Pattern.CommonSolutions -join ', ')"
                Write-Host ""
            }
        } else {
            Write-Host "マッチするパターンが見つかりませんでした" -ForegroundColor Yellow
        }
    }
    
    default {
        Write-Host "不明なアクション: $Action" -ForegroundColor Red
        Write-Host "使用可能なアクション: record, analyze, report, recovery, pattern-match"
        exit 1
    }
}