import Mathlib

open scoped BigOperators

namespace HW_IUT1_S15

/-!
# Solutions for sheet S15

We formalise several classical number theoretic statements in Lean.  Every
proof is carried out inside `mathlib`, following the structural style of
Bourbaki.

The main results are:

* `S15_P01`: Every non-zero ideal of `ℤ` is principal.
* `S15_P02`: Two integers that agree modulo every prime number are equal.
* `S15_P03`: A Hensel lifting argument for `x² = 2` in the `7`-adic integers
  and all residue class rings `ℤ/7ⁿℤ`.
* `S15_P04`: The degree of the 12th cyclotomic polynomial over `ℚ` is `4`.
* `S15_P05`: The element `2` is not prime in `ℤ[√-5]`.
* `S15_CH`: An `abc`-style inequality for the triple `(1, 2ⁿ - 1, 2ⁿ)` under a
  squarefreeness hypothesis.
-/

noncomputable section

/-- The radical of a natural number: the product of its distinct prime factors. -/
def rad (n : ℕ) : ℕ := ∏ p ∈ n.primeFactors, p

@[simp] lemma rad_one : rad 1 = 1 := by
  classical
  simp [rad]

lemma rad_mul_of_coprime {m n : ℕ} (h : Nat.Coprime m n) :
    rad (m * n) = rad m * rad n := by
  classical
  have hdisj : Disjoint m.primeFactors n.primeFactors := h.disjoint_primeFactors
  have hunion : (m * n).primeFactors = m.primeFactors ∪ n.primeFactors :=
    h.primeFactors_mul
  have hprod : ∏ p ∈ m.primeFactors ∪ n.primeFactors, p =
      (∏ p ∈ m.primeFactors, p) * ∏ p ∈ n.primeFactors, p := by
    simpa using
      Finset.prod_union (s₁ := m.primeFactors) (s₂ := n.primeFactors)
        (f := fun p : ℕ => p) hdisj
  simpa [rad, hunion] using hprod

lemma rad_pow {n k : ℕ} (hk : k ≠ 0) : rad (n ^ k) = rad n := by
  classical
  simpa [rad, Nat.primeFactors_pow n hk]

lemma rad_prime_pow {p n : ℕ} (hp : Nat.Prime p) (hn : 0 < n) :
    rad (p ^ n) = p := by
  classical
  have hk : n ≠ 0 := Nat.pos_iff_ne_zero.mp hn
  have hpf : (p ^ n).primeFactors = {p} := Nat.primeFactors_prime_pow hk hp
  simp [rad, hpf]

lemma rad_of_squarefree {n : ℕ} (hn : Squarefree n) : rad n = n := by
  classical
  simpa [rad] using Nat.prod_primeFactors_of_squarefree hn

/-- Any non-zero ideal of `ℤ` is generated by a single integer. -/
theorem S15_P01 :
    ∀ I : Ideal ℤ, I ≠ ⊥ → ∃ n : ℤ, I = Ideal.span ({n} : Set ℤ) := by
  classical
  intro I _
  obtain ⟨n, hn⟩ := IsPrincipalIdealRing.principal I
  exact ⟨n, hn⟩

/-- If the reductions of two integers modulo every prime coincide, then the
integers themselves are equal. -/
theorem S15_P02 :
    ∀ a b : ℤ,
      (∀ p : ℕ, Nat.Prime p → (a : ZMod p) = (b : ZMod p)) →
        a = b := by
  classical
  intro a b h
  by_contra hne
  have hsub : a - b ≠ 0 := sub_ne_zero.mpr hne
  have hd_pos : 0 < Int.natAbs (a - b) := Int.natAbs_pos.mpr hsub
  obtain ⟨p, hp_ge, hp_prime⟩ :=
    Nat.exists_infinite_primes (Int.natAbs (a - b) + 1)
  have hcongr := h p hp_prime
  have hdiv' : ((p : ℤ) ∣ b - a) :=
    (ZMod.intCast_eq_intCast_iff_dvd_sub a b p).1 (by simpa using hcongr)
  have hdiv : ((p : ℤ) ∣ a - b) := by
    simpa [sub_eq_add_neg, add_comm, add_left_comm, add_assoc] using
      Int.dvd_neg.mpr hdiv'
  have hnatdiv : p ∣ Int.natAbs (a - b) :=
    (Int.natCast_dvd_natCast).1 (Int.dvd_natAbs.2 hdiv)
  have hp_le : p ≤ Int.natAbs (a - b) :=
    Nat.le_of_dvd hd_pos hnatdiv
  have hlt : Int.natAbs (a - b) < p :=
    Nat.lt_of_lt_of_le (Nat.lt_succ_self _) hp_ge
  exact lt_irrefl _ (lt_of_le_of_lt hp_le hlt)

open Polynomial

/-- Hensel lifting of the square root of `2` in the 7-adic integers. -/
theorem S15_P03 :
    (3 : ZMod 7) ^ 2 = (2 : ZMod 7) ∧
      ∀ n : ℕ, 1 ≤ n → ∃ x : ZMod (7 ^ n), x ^ 2 = 2 := by
  classical
  have hbase : (3 : ZMod 7) ^ 2 = (2 : ZMod 7) := by norm_num
  let p : ℕ := 7
  have hp : Nat.Prime p := by decide
  haveI : Fact (Nat.Prime p) := ⟨hp⟩
  let a : ℤ_[p] := (3 : ℤ_[p])
  let f : Polynomial ℤ_[p] := X ^ 2 - Polynomial.C (2 : ℤ_[p])
  have h₁ : f.aeval a = (p : ℤ_[p]) := by
    simp [f, pow_two]
  have h₂ : f.derivative.aeval a = (6 : ℤ_[p]) := by
    simp [f, pow_two]
  have hf_norm : ‖f.aeval a‖ = (p : ℝ)⁻¹ := by
    simpa [h₁] using (PadicInt.norm_p (p := p))
  have hder_norm : ‖f.derivative.aeval a‖ = 1 := by
    have : ‖(6 : ℤ_[p])‖ = 1 :=
      (PadicInt.norm_intCast_eq_one_iff (p := p) (z := 6)).2 (by decide)
    simpa [h₂] using this
  have hnorm : ‖f.aeval a‖ < ‖f.derivative.aeval a‖ ^ 2 := by
    have : (p : ℝ)⁻¹ < 1 := by simpa [p] using (by norm_num : (1 / (7 : ℝ)) < 1)
    simpa [hf_norm, hder_norm] using this
  obtain ⟨z, hz, -, -, _⟩ := hensels_lemma (p := p) (F := f) (a := a) hnorm
  have hz_sq' : z * z = (2 : ℤ_[p]) := by
    have : z ^ 2 - (2 : ℤ_[p]) = 0 := by
      simpa [f, pow_two, sub_eq_add_neg] using hz
    simpa [pow_two] using sub_eq_zero.mp this
  have hz_sq : z ^ 2 = (2 : ℤ_[p]) := by
    simpa [pow_two] using hz_sq'
  refine ⟨hbase, ?_⟩
  intro n _
  refine ⟨PadicInt.toZModPow n z, ?_⟩
  have hmap := congrArg (PadicInt.toZModPow n) hz_sq
  simpa [pow_two] using hmap

/-- The degree of the 12-th cyclotomic polynomial is `4`. -/
theorem S15_P04 : Polynomial.natDegree (cyclotomic 12 ℚ) = 4 := by
  classical
  have htot : Nat.totient 12 = 4 := by decide
  simpa [htot] using Polynomial.natDegree_cyclotomic 12 ℚ

/-- The element `2` is not a prime element of `ℤ[√-5]`. -/
theorem S15_P05 : ¬ IsPrime (2 : Zsqrtd (-5)) := by
  classical
  set R := Zsqrtd (-5)
  let α : R := ⟨1, 1⟩
  let β : R := ⟨1, -1⟩
  have hαβ : α * β = (6 : R) := by
    ext <;> simp [α, β]
  have hα_norm : Zsqrtd.norm α = (6 : ℤ) := by
    simp [α, Zsqrtd.norm]
  have hβ_norm : Zsqrtd.norm β = (6 : ℤ) := by
    simp [β, Zsqrtd.norm]
  have htwo_norm : Zsqrtd.norm (2 : R) = (4 : ℤ) := by
    simp [Zsqrtd.norm]
  have hdiv : (2 : R) ∣ α * β := by
    refine ⟨(3 : R), ?_⟩
    simp [hαβ]
  intro hprime
  have := hprime.dvd_or_dvd hdiv
  rcases this with hα | hβ'
  · rcases hα with ⟨x, hx⟩
    have hx_norm := congrArg Zsqrtd.norm hx
    simp [hx, hα_norm, Zsqrtd.norm_mul, htwo_norm] at hx_norm
    have : (4 : ℤ) ∣ (6 : ℤ) := ⟨Zsqrtd.norm x, hx_norm.symm⟩
    exact (by decide : ¬((4 : ℤ) ∣ (6 : ℤ))) this
  · rcases hβ' with ⟨x, hx⟩
    have hx_norm := congrArg Zsqrtd.norm hx
    simp [hx, hβ_norm, Zsqrtd.norm_mul, htwo_norm] at hx_norm
    have : (4 : ℤ) ∣ (6 : ℤ) := ⟨Zsqrtd.norm x, hx_norm.symm⟩
    exact (by decide : ¬((4 : ℤ) ∣ (6 : ℤ))) this

/-- An `abc`-style inequality for the triple `(1, 2ⁿ - 1, 2ⁿ)` under the
assumption that `2ⁿ - 1` is squarefree. -/
theorem S15_CH :
    ∀ n : ℕ, 2 ≤ n → Squarefree (2 ^ n - 1) →
      let a := 1; let b := 2 ^ n - 1; let c := 2 ^ n;
      Nat.Coprime a b ∧ c < (rad (a * b * c)) ^ 2 := by
  classical
  intro n hn hsq
  intro a b c
  dsimp only at a b c
  have hpow : 1 ≤ 2 ^ n :=
    Nat.succ_le_of_lt (pow_pos (by decide : (0 : ℕ) < 2) _)
  have hcop : Nat.Coprime (2 ^ n - 1) (2 ^ n) := by
    have hx :=
      (Nat.coprime_self_add_right (m := 2 ^ n - 1) (n := 1)).2
        (Nat.coprime_one_right _)
    simpa [Nat.sub_add_cancel hpow] using hx
  have hrad_b : rad (2 ^ n - 1) = 2 ^ n - 1 := rad_of_squarefree hsq
  have hrad_c : rad (2 ^ n) = 2 := by
    have hnpos : 0 < n := lt_of_lt_of_le (by decide : 0 < 2) hn
    simpa using rad_prime_pow (p := 2) (n := n) (by decide) hnpos
  have hrad : rad (1 * (2 ^ n - 1) * 2 ^ n) = 2 * (2 ^ n - 1) := by
    have := rad_mul_of_coprime (m := 2 ^ n - 1) (n := 2 ^ n) hcop
    simpa [hrad_b, hrad_c, Nat.mul_comm, Nat.mul_left_comm, Nat.mul_assoc] using this
  have hcop_ab : Nat.Coprime 1 (2 ^ n - 1) := Nat.coprime_one_left _
  refine ⟨hcop_ab, ?_⟩
  have hx_nat : (2 ^ n : ℝ) < (2 * ((2 ^ n : ℝ) - 1)) ^ 2 := by
    set x : ℝ := (2 : ℝ) ^ n
    have hx_ge4 : (4 : ℝ) ≤ x := by
      have : (2 : ℕ) ≤ n := hn
      have hx_nat : (2 : ℕ) ^ 2 ≤ 2 ^ n :=
        Nat.pow_le_pow_of_le_left (by decide : 0 < 2) this
      exact_mod_cast hx_nat
    have hx_nonneg : 0 ≤ x := pow_nonneg (show (0 : ℝ) ≤ 2 by norm_num) _
    have hx_pos : 0 < 4 * x ^ 2 - 9 * x + 4 := by
      nlinarith [hx_ge4, hx_nonneg]
    have hx_pos' : 0 < (2 * (x - 1)) ^ 2 - x := by
      have : (2 * (x - 1)) ^ 2 - x = 4 * x ^ 2 - 9 * x + 4 := by ring
      simpa [this] using hx_pos
    have hx_lt : x < (2 * (x - 1)) ^ 2 := sub_pos.mp hx_pos'
    convert hx_lt using 1 <;> simp [x, pow_two, sub_eq_add_neg, two_mul]
  have hx_nat' : (2 ^ n : ℕ) < (2 * (2 ^ n - 1)) ^ 2 := by
    have hx_cast : ((2 ^ n : ℕ) : ℝ) < ((2 * (2 ^ n - 1)) ^ 2 : ℝ) := by
      have hcast : ((2 * (2 ^ n - 1)) ^ 2 : ℝ) = (2 * ((2 ^ n : ℝ) - 1)) ^ 2 := by
        simp [pow_two, Nat.cast_mul, Nat.cast_pow, Nat.cast_sub hpow]
      simpa [hcast] using hx_nat
    exact_mod_cast hx_cast
  have hx_goal : (2 ^ n : ℕ) < (rad (1 * (2 ^ n - 1) * 2 ^ n)) ^ 2 := by
    simpa [hrad] using hx_nat'
  exact hx_goal

/-- A simple sanity check. -/
example : rad 2 = 2 := by
  have : 0 < (1 : ℕ) := by decide
  simpa using rad_prime_pow (p := 2) (n := 1) (by decide) this

end HW_IUT1_S15






