/-
  Topology B 窶・Bourbaki-style structuration via ordered pairs and morphisms

  This file is derived from:
    src/MyProjects/Topology/B/claude_topologyB_en.md

  Guiding spirit (Bourbaki):
  - Structure built from sets of ordered pairs (products) and morphisms (projections)
  - Universal properties expressed via factorization through projections
  - Emphasis on diagrammatic uniqueness (existence/uniqueness of mediating maps)

  Contents
  A. Product universality and exponential direction (skeleton)
  B. Covering maps (Bourbaki-flavored definition skeleton) and path lifting (statement stub)
  C. Stone窶篤憩ch compactification (universal property skeleton)

  Notes
  - Section A provides concrete lemmas fully in terms of projections and ordered pairs.
  - Sections B and C lay out faithful skeletons of the intended structures and universal properties
    so they can be refined without changing interfaces.
-/

import Mathlib.Topology.Basic
import Mathlib.Topology.Constructions.SumProd
import Mathlib.Topology.ContinuousMap.Basic
import Mathlib.Topology.CompactOpen
import Mathlib.Topology.Instances.Real.Lemmas
import Mathlib.Topology.Category.TopCat.Basic
import Mathlib.Topology.Category.TopCat.Limits.Basic
import Mathlib.CategoryTheory.Adjunction.Basic
-- Stone窶篤憩ch (module name may vary slightly by mathlib version):
import Mathlib.Topology.Compactification.StoneCech

namespace Bourbaki.TopologyB











/-!
## A. Product universality via projections

We formalize the spirit 窶徘roduct = structure generated by projections窶・
- continuity of projections `ﾏ竄・ ﾏ竄Ａ;
- continuity criterion for a map into a product via its components;
- existence and uniqueness of the mediating map `筺ｨf, g筺ｩ`.
!/ -/

section ProductUniversality

variable {T X Y : Type*}
variable [TopologicalSpace T] [TopologicalSpace X] [TopologicalSpace Y]

-- Projections (morphisms) from the ordered pair structure X ﾃ・Y.
def ﾏ竄・: X ﾃ・Y 竊・X := fun p => p.1
def ﾏ竄・: X ﾃ・Y 竊・Y := fun p => p.2

lemma continuous_ﾏ竄・: Continuous (ﾏ竄・: X ﾃ・Y 竊・X) := by
  simpa [ﾏ竄‐ using continuous_fst

lemma continuous_ﾏ竄・: Continuous (ﾏ竄・: X ﾃ・Y 竊・Y) := by
  simpa [ﾏ竄・ using continuous_snd

/-
Continuity into a product is equivalent to continuity of the two components
obtained by composing with the projections. This is the universal property
in Bourbaki窶冱 language: the product topology is the coarsest making ﾏ竄・ ﾏ竄・continuous, and continuity is tested componentwise.
-/
theorem continuous_iff_proj (h : T 竊・X ﾃ・Y) :
    Continuous h 竊・      Continuous (fun t => (h t).1) 竏ｧ Continuous (fun t => (h t).2) := by
  constructor
  ﾂｷ intro hh
    exact 筺ｨcontinuous_fst.comp hh, continuous_snd.comp hh筺ｩ
  ﾂｷ rintro 筺ｨh竄・ h竄や洸
    -- Use `Continuous.prodMk` on the components to build continuity of `h`.
    -- We rewrite `h` as `fun t => ((h t).1, (h t).2)` to `simpa`.
    have : Continuous (fun t => ((h t).1, (h t).2)) := h竄・prodMk h竄・    simpa using this

/-
Existence and uniqueness of the mediating map into a product.
Given continuous `f : T 竊・X` and `g : T 竊・Y`, there is a unique continuous
`h : T 竊・X ﾃ・Y` such that `ﾏ竄・竏・h = f` and `ﾏ竄・竏・h = g`.
-/
theorem exists_unique_lift_to_prod {f : T 竊・X} {g : T 竊・Y}
    (hf : Continuous f) (hg : Continuous g) :
    竏・ h : T 竊・X ﾃ・Y,
      Continuous h 竏ｧ (竏 t, (h t).1 = f t) 竏ｧ (竏 t, (h t).2 = g t) := by
  refine 筺ｨ(fun t => (f t, g t)), ?exist, ?uniq筺ｩ
  ﾂｷ -- existence: the canonical pairing is continuous and has the desired components
    refine And.intro ?hcont (And.intro ?hfst ?hsnd)
    ﾂｷ simpa using hf.prodMk hg
    ﾂｷ intro t; rfl
    ﾂｷ intro t; rfl
  ﾂｷ -- uniqueness: any other h with the same components must be pointwise equal
    intro h hh
    rcases hh with 筺ｨ_hc, hfst, hsnd筺ｩ
    apply funext
    intro t
    -- Compare components, then use `Prod.ext`.
    apply Prod.ext
    ﾂｷ simpa using hfst t
    ﾂｷ simpa using hsnd t

/-
As a quick corollary, pairing with projections recovers the map.
This is the ﾎｲ-rule for the universal property.
-/
lemma fst_pair_eq (f : T 竊・X) (g : T 竊・Y) (t : T) : ((f t, g t).1) = f t := rfl
lemma snd_pair_eq (f : T 竊・X) (g : T 竊・Y) (t : T) : ((f t, g t).2) = g t := rfl

end ProductUniversality

/-!
## A. (Category level) Diagonal 竓｣ Product in `TopCat`

We implement the diagonal functor ﾎ・: TopCat 筵､ TopCat ﾃ・TopCat and the
product functor ﾃ・: TopCat ﾃ・TopCat 筵､ TopCat, and exhibit the adjunction
Hom(ﾎ嚢, (Y, Z)) 竕・Hom(X, Y ﾃ・Z). The hom-sets reduce to pairs of continuous
maps versus a single continuous map into the product, matching the Bourbaki
ordered-pair perspective.
!/ -/

section TopCatAdjunction

open CategoryTheory

/- ﾎ・ duplicate objects and morphisms. -/
def deltaTop : TopCat 筵､ TopCat ﾃ・TopCat where
  obj X := 筺ｨX, X筺ｩ
  map {X Y} (f : X 筺ｶ Y) := 筺ｨf, f筺ｩ
  map_id X := by
    -- identities are componentwise
    ext <;> rfl
  map_comp {X Y Z} (f : X 筺ｶ Y) (g : Y 筺ｶ Z) := by
    -- composition is componentwise
    ext <;> rfl

/- ﾃ・ binary product on objects as cartesian product of spaces; on morphisms
it acts via `ContinuousMap.prodMap`.
-/
def prodTop : TopCat ﾃ・TopCat 筵､ TopCat where
  obj X := TopCat.of (X.1 ﾃ・X.2)
  map {X Y} (f : X 筺ｶ Y) :=
    筺ｨ(fun p : X.1 ﾃ・X.2 => (f.1 p.1, f.2 p.2)), by
      -- continuity by components
      have h1 : Continuous fun p : X.1 ﾃ・X.2 => f.1 p.1 := by
        simpa using (f.1.continuous.comp continuous_fst)
      have h2 : Continuous fun p : X.1 ﾃ・X.2 => f.2 p.2 := by
        simpa using (f.2.continuous.comp continuous_snd)
      exact h1.prodMk h2筺ｩ
  map_id X := by
    -- identity acts componentwise
    ext p <;> rfl
  map_comp {X Y Z} (f : X 筺ｶ Y) (g : Y 筺ｶ Z) := by
    -- composition is componentwise
    ext p <;> rfl

/- The hom-set equivalence for the adjunction. -/
noncomputable def homEquivDeltaProd
    (X : TopCat) (YZ : TopCat ﾃ・TopCat) :
    ((deltaTop.obj X) 筺ｶ YZ) 竕・(X 筺ｶ prodTop.obj YZ) :=
{ toFun :=
    fun fg =>
      筺ｨ(fun x => (fg.1 x, fg.2 x)), by
        simpa using (fg.1.continuous.prodMk fg.2.continuous)筺ｩ
, invFun :=
    fun h =>
      (筺ｨ(fun x => (h x).1), by
          simpa using (continuous_fst.comp h.continuous)筺ｩ,
       筺ｨ(fun x => (h x).2), by
          simpa using (continuous_snd.comp h.continuous)筺ｩ)
, left_inv := by
    intro fg; ext x <;> rfl
, right_inv := by
    intro h; ext p <;> rfl }

/- The adjunction ﾎ・竓｣ ﾃ・specialized to `TopCat`. -/
-- (Optional) One can package `homEquivDeltaProd` into an adjunction using
-- `Adjunction.mkOfHomEquiv`. We keep the hom-set equivalence explicit here.

end TopCatAdjunction

/-!
## A'. Exponential direction (skeleton)

We record currying/uncurrying at the level of plain functions (ordered pairs 竊・functions into function spaces) and reserve continuity/topological refinements
for future development (e.g. under `[LocallyCompactSpace]` hypotheses). This
keeps the Bourbaki pairing perspective explicit and light.
!/ -/

section ExponentialSkeleton

variable {X Y Z : Type*}

/-- Currying: functions on a product are functions returning functions. -/
def curry (f : X ﾃ・Y 竊・Z) : X 竊・Y 竊・Z :=
  fun x y => f (x, y)

/-- Uncurrying: functions returning functions are functions on a product. -/
def uncurry (g : X 竊・Y 竊・Z) : X ﾃ・Y 竊・Z :=
  fun p => g p.1 p.2

@[simp] lemma curry_uncurry (g : X 竊・Y 竊・Z) : curry (uncurry g) = g := rfl
@[simp] lemma uncurry_curry (f : X ﾃ・Y 竊・Z) : uncurry (curry f) = f := by
  funext p; cases p; rfl

end ExponentialSkeleton

section ExponentialLaw

open ContinuousMap

variable {X Y Z : Type*}
variable [TopologicalSpace X] [TopologicalSpace Y] [TopologicalSpace Z]

/-- Exponential law: `ContinuousMap (X ﾃ・Y) Z 竕・・ ContinuousMap X (ContinuousMap Y Z)` under local compactness. -/
noncomputable def exponential_homeo
    [LocallyCompactSpace X] [LocallyCompactSpace Y] :
    ContinuousMap (X ﾃ・Y) Z 竕・・ ContinuousMap X (ContinuousMap Y Z) :=
  Homeomorph.curry (X:=X) (Y:=Y) (Z:=Z)

@[simp] lemma exponential_homeo_apply
    [LocallyCompactSpace X] [LocallyCompactSpace Y]
    (F : ContinuousMap (X ﾃ・Y) Z) (x : X) (y : Y) :
    (exponential_homeo (X:=X) (Y:=Y) (Z:=Z) F x) y = F (x, y) := rfl

@[simp] lemma exponential_homeo_symm_apply
    [LocallyCompactSpace X] [LocallyCompactSpace Y]
    (G : ContinuousMap X (ContinuousMap Y Z)) (p : X ﾃ・Y) :
    (exponential_homeo (X:=X) (Y:=Y) (Z:=Z)).symm G p = G p.1 p.2 := rfl

/-- Continuity of the evaluation map `(f, y) 竊ｦ f y` under the compact-open topology. -/
theorem continuous_eval
    [LocallyCompactPair Y Z] :
    Continuous (fun p : ContinuousMap Y Z ﾃ・Y => p.1 p.2) := by
  simpa using (ContinuousEval.continuous_eval :
    Continuous (fun p : ContinuousMap Y Z ﾃ・Y => p.1 p.2))

end ExponentialLaw

/-!
## B. Covering spaces 窶・Bourbaki-style skeleton

We package the essence of an evenly covered neighborhood in terms of a local
homeomorphism to a product `U ﾃ・I` with discrete fiber `I`. This keeps the
ordered-pair-and-projection viewpoint explicit. The definition below is a
faithful skeleton: it captures the shape and the key data while staying light.
!/ -/

section CoveringSpaces

open scoped Topology

variable {E B : Type*}
variable [TopologicalSpace E] [TopologicalSpace B]

/-
`CoveringMap p` asserts that around every base point `b : B`, the preimage of a
small neighborhood `U` decomposes as a product `U ﾃ・I` for a discrete index
set `I`. We keep the commuting condition with the projection implicit in this
first skeleton, focusing on the core decomposition datum.
-/
structure CoveringMap (p : E 竊・B) : Prop where
  continuous : Continuous p
  evenlyCovered :
    竏 b : B,
      竏・(U : Set B), IsOpen U 竏ｧ b 竏・U 竏ｧ
        竏・(I : Type*) (_ : TopologicalSpace I) (_ : DiscreteTopology I),
        竏・e : (Subtype fun e : E => p e 竏・U) 竕・・ ((Subtype fun x : B => x 竏・U) ﾃ・I),
          (竏 s, ((e s).1 : Subtype fun x : B => x 竏・U).1 = p s.1)

/-
Skeleton of the path-lifting statement: given a covering map, paths in the base
lift uniquely once an initial point in the fiber is fixed. The precise
implementation can follow mathlib窶冱 path/interval conventions.
-/
theorem path_lifting_theorem_skeleton (p : E 竊・B) (h : CoveringMap p) : True :=
  True.intro

end CoveringSpaces

/-!
## C. Stone窶篤憩ch compactification 窶・universal property skeleton

We encode ﾎｲX together with the canonical map `ﾎｹ : ContinuousMap X ﾎｲX` and the universal
property for maps into compact Hausdorff spaces. This mirrors the md design,
yet leaves heavy analysis to future dedicated development.
!/ -/

section StoneCechSkeleton

variable (X : Type*) [TopologicalSpace X]

-- Provide typeclass instances for the carrier `ﾎｲX` stored inside a compactification.
-- instance instTopologicalSpace_beta (S : StoneCechCompactification X) :
--     TopologicalSpace S.ﾎｲX := S.instTopﾎｲX

-- instance instCompactSpace_beta (S : StoneCechCompactification X) :
--     CompactSpace S.ﾎｲX := S.instCompﾎｲX

-- instance instT2Space_beta (S : StoneCechCompactification X) :
--     T2Space S.ﾎｲX := S.instT2ﾎｲX

structure StoneCechCompactification where
  ﾎｲX : Type*
  instTopﾎｲX : TopologicalSpace ﾎｲX
  instCompﾎｲX : CompactSpace ﾎｲX
  instT2ﾎｲX : T2Space ﾎｲX
  ﾎｹ : ContinuousMap X ﾎｲX
  dense_range : DenseRange ﾎｹ
  universal :
    竏 (K : Type*) (_ : TopologicalSpace K) (_ : CompactSpace K) (_ : T2Space K),
      ∀ f : ContinuousMap X K, ∃ ! F : ContinuousMap βX K, F.comp ι = f 

instance instTopologicalSpace_beta (S : StoneCechCompactification X) :
    TopologicalSpace S.βX := S.instTopβX

instance instCompactSpace_beta (S : StoneCechCompactification X) :
    CompactSpace S.βX := S.instCompβX

instance instT2Space_beta (S : StoneCechCompactification X) :
    T2Space S.βX := S.instT2βX


/-!
Convenience API: abstract lifting and its `simp`-friendly consequences from the
universal property. This works for any `StoneCechCompactification X` instance,
including the trivial one below or a mathlib-backed one.
!/ -/

noncomputable def StoneCechCompactification.lift
    {X : Type*} [TopologicalSpace X]
    (S : StoneCechCompactification X)
    (K : Type*) [TopologicalSpace K] [CompactSpace K] [T2Space K]
    (f : ContinuousMap X K) : ContinuousMap S.ﾎｲX K :=
  Classical.choose (S.universal K _ _ _ f)

@[simp] lemma StoneCechCompactification.lift_comp
    {X : Type*} [TopologicalSpace X]
    (S : StoneCechCompactification X)
    (K : Type*) [TopologicalSpace K] [CompactSpace K] [T2Space K]
    (f : ContinuousMap X K) :
    (S.lift K f).comp S.ﾎｹ = f := by
  classical
  simpa using (Classical.choose_spec (S.universal K _ _ _ f)).1

@[simp] lemma StoneCechCompactification.lift_comp_apply
    {X : Type*} [TopologicalSpace X]
    (S : StoneCechCompactification X)
    (K : Type*) [TopologicalSpace K] [CompactSpace K] [T2Space K]
    (f : ContinuousMap X K) (x : X) :
    ((S.lift K f).comp S.ﾎｹ) x = f x := by
  classical
  have := S.lift_comp (K:=K) f
  simpa using congrArg (fun (h : ContinuousMap X K) => h x) this

lemma StoneCechCompactification.lift_unique
    {X : Type*} [TopologicalSpace X]
    (S : StoneCechCompactification X)
    (K : Type*) [TopologicalSpace K] [CompactSpace K] [T2Space K]
    (f : ContinuousMap X K) {G : ContinuousMap S.ﾎｲX K}
    (hG : G.comp S.ﾎｹ = f) :
    G = S.lift K f := by
  classical
  have h := (Classical.choose_spec (S.universal K _ _ _ f)).2
  exact h G hG

/-!
Trivial compactification: when `X` is already compact Hausdorff, we can take
ﾎｲX = X and ﾎｹ = id. This satisfies the universal property with `F = f`.
This gives a working instance without importing mathlib窶冱 `StoneCech`.
!/ -/

noncomputable def StoneCechCompactification.trivial
    (X : Type*) [TopologicalSpace X]
    [CompactSpace X] [T2Space X] : StoneCechCompactification X :=
{ ﾎｲX := X
, instTopﾎｲX := inferInstance
, instCompﾎｲX := inferInstance
, instT2ﾎｲX := inferInstance
, ﾎｹ := ContinuousMap.id X
, dense_range := by
    -- range(id) = univ is dense
    classical
    simpa using (denseRange_id : DenseRange (fun x : X => x))
, universal := by
    intro K _ _ _ f
    refine 筺ｨf, ?comp, ?uniq筺ｩ
    ﾂｷ -- F 竏・ﾎｹ = f with F = f and ﾎｹ = id
      ext x; rfl
    ﾂｷ -- uniqueness: if G 竏・id = f then G = f
      intro G hG
      ext x
      -- evaluate both sides; `hG` gives function extensionality pointwise
      -- since `ﾎｹ = id`, we have `G x = (G.comp (ContinuousMap.id X)) x`
      have := congrArg (fun (h : ContinuousMap X K) => h x) hG
      simpa using this
}

end StoneCechSkeleton

/-!
## C'. Stone窶篤憩ch from mathlib (integration)

This realizes the abstract `StoneCechCompactification` by mathlib窶冱 `StoneCech`:
ﾎｲX := `StoneCech X`, ﾎｹ := the canonical unit embedding, and the universal arrow
provided by `StoneCech.extend`. The uniqueness is discharged by density of ﾎｹ
and T竄・on the codomain.
!/ -/

section StoneCechFromMathlib

variable (X : Type*) [TopologicalSpace X]

noncomputable def StoneCechCompactification.fromMathlib :
    StoneCechCompactification X :=
{ ﾎｲX := StoneCech X
, instTopﾎｲX := inferInstance
, instCompﾎｲX := inferInstance
, instT2ﾎｲX := inferInstance
, ﾎｹ := 筺ｨstoneCechUnit, continuous_stoneCechUnit筺ｩ
, dense_range := by
    simpa using (denseRange_stoneCechUnit : DenseRange (stoneCechUnit : X 竊・StoneCech X))
, universal := by
    intro K _ _ _ f
    classical
    -- Existence: use the canonical continuous extension from mathlib
    let F : ContinuousMap (StoneCech X) K :=
      筺ｨstoneCechExtend (ﾎｱ := X) (ﾎｲ := K) (g := fun x => f x) f.continuous,
        continuous_stoneCechExtend (ﾎｱ := X) (ﾎｲ := K) (g := fun x => f x) f.continuous筺ｩ
    refine 筺ｨF, ?comp, ?uniq筺ｩ
    ﾂｷ -- ﾎｲ-rule: extension comp unit = original
      -- Use the function-level statement then evaluate at points.
      have hfun := (stoneCechExtend_extends (α := X) (β := K)
          (g := fun x => f x) (hg := f.continuous))
        simpa using (stoneCechExtend_extends (ﾎｱ := X) (ﾎｲ := K)
          (g := fun x => f x) (hg := f.continuous))
      ext x
      simp [Function.comp] using congrArg (fun (h : X → K) => h x) hfun
    ﾂｷ -- Uniqueness via `stoneCech_hom_ext`
      intro G hG
      -- continuity of G and F are available as `G.continuous` and `F.continuous`

      -- both sides agree after precomposition with the unit map
      -- Start with equality of bundled maps after composing with `ﾎｹ`:
      have hFcomp : F.comp 筺ｨstoneCechUnit, continuous_stoneCechUnit筺ｩ = f := by
        -- As above, use the function-level version and ext.
        have hfun := (stoneCechExtend_extends (α := X) (β := K)
            (g := fun x => f x) (hg := f.continuous))
          simpa using (stoneCechExtend_extends (ﾎｱ := X) (ﾎｲ := K)
            (g := fun x => f x) (hg := f.continuous))
        ext x; simp [Function.comp] using congrArg (fun (h : X → K) => h x) hfun
      have hEq : G.comp 筺ｨstoneCechUnit, continuous_stoneCechUnit筺ｩ
                = F.comp 筺ｨstoneCechUnit, continuous_stoneCechUnit筺ｩ := by
        simpa [hFcomp] using hG
      -- Now get pointwise equality on the dense image of `stoneCechUnit`:
      have hcomp : (fun x => G (stoneCechUnit x)) = (fun x => F (stoneCechUnit x)) := by
        ext x; simpa [Function.comp] using
          congrArg (fun (h : ContinuousMap X K) => h x) hEq
      -- Uniqueness of continuous extensions from dense subsets in T竄・spaces:
      -- `stoneCech_hom_ext` yields equality as functions, so we ext to upgrade to `ContinuousMap`.
      have hfun : (fun y => G y) = (fun y => F y) :=
        stoneCech_hom_ext (α := X) (β := K) (G.continuous) (F.continuous) hcomp
      ext y; simpa using congrArg (fun h => h y) hfun
}

end StoneCechFromMathlib

section StoneCechSmoke

variable (X : Type*) [TopologicalSpace X]

-- A tiny smoke test: the ﾎｲ-rule for `lift` reduces by `simp`/`ext`.
example {K : Type*} [TopologicalSpace K] [CompactSpace K] [T2Space K]
    (f : ContinuousMap X K) (x : X) :
  ((StoneCechCompactification.fromMathlib (X:=X)).lift K f).comp
      (StoneCechCompactification.fromMathlib (X:=X)).ﾎｹ x = f x := by
  simpa using
    (StoneCechCompactification.lift_comp_apply
      (S := StoneCechCompactification.fromMathlib (X:=X)) (K:=K) f x)

end StoneCechSmoke

end Bourbaki.TopologyB


